// frontend/src/components/BranchSwitcher.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { fetchBranches, switchBranch } from '../lib/api.js';
import type { BranchInfo } from '../lib/types.js';
import CipherText from './CipherText';
import TuiMenuItem from './TuiMenuItem';
import TuiMenuPanel from './TuiMenuPanel';
import './BranchSwitcher.css';

export interface BranchSwitcherProps {
  repoPath: string;
  currentBranch: string;
  onSwitch: (branch: string) => void;
  disabled?: boolean;
  currentWorktreePath?: string;
  onJumpToSession?: (sessionId: string) => void;
  onStartSession?: (worktreePath: string) => void;
  onCreateBranch?: (branchName: string) => void;
}

export function BranchSwitcher({
  repoPath,
  currentBranch,
  onSwitch,
  disabled = false,
  currentWorktreePath,
  onJumpToSession,
  onStartSession,
  onCreateBranch,
}: BranchSwitcherProps) {
  const [open, setOpen] = useState(false);
  const [filterText, setFilterText] = useState('');
  const [branches, setBranches] = useState<BranchInfo[]>([]);
  const [loading, setLoading] = useState(false);
  const [switching, setSwitching] = useState<string | null>(null);
  const [switchError, setSwitchError] = useState<string | null>(null);

  const wrapperRef = useRef<HTMLDivElement>(null);
  const filterInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!open) return;

    let cancelled = false;
    setLoading(true);

    void fetchBranches(repoPath)
      .then((nextBranches) => {
        if (!cancelled) setBranches(nextBranches);
      })
      .catch(() => {
        if (!cancelled) setBranches([]);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [open, repoPath]);

  useEffect(() => {
    if (!open) return;

    const raf = window.requestAnimationFrame(() => {
      filterInputRef.current?.focus();
    });

    return () => window.cancelAnimationFrame(raf);
  }, [open]);

  useEffect(() => {
    if (!open) return;

    const handleWindowClick = (event: MouseEvent) => {
      const target = event.target as Node | null;
      if (target && wrapperRef.current && !wrapperRef.current.contains(target)) {
        setOpen(false);
        setFilterText('');
      }
    };

    window.addEventListener('click', handleWindowClick);
    return () => window.removeEventListener('click', handleWindowClick);
  }, [open]);

  const filteredBranches = useMemo(() => {
    if (!filterText.trim()) return branches;
    const lower = filterText.toLowerCase();
    return branches.filter((branch) => branch.name.toLowerCase().includes(lower));
  }, [branches, filterText]);

  const showCreateOption = useMemo(() => {
    const trimmed = filterText.trim();
    if (!trimmed) return false;
    return !branches.some((branch) => branch.name === trimmed);
  }, [branches, filterText]);

  const closeDropdown = () => {
    setOpen(false);
    setFilterText('');
  };

  const openDropdown = () => {
    if (disabled) return;
    setOpen(true);
    setFilterText('');
    setSwitchError(null);
  };

  const handleSelect = async (branchName: string) => {
    if (branchName === currentBranch) {
      closeDropdown();
      return;
    }

    setSwitching(branchName);
    setSwitchError(null);

    try {
      const result = await switchBranch(repoPath, branchName);
      if (result.success) {
        closeDropdown();
        onSwitch(branchName);
      } else {
        setSwitchError(result.error ?? 'Failed to switch branch');
      }
    } catch {
      setSwitchError('Failed to switch branch');
    } finally {
      setSwitching(null);
    }
  };

  const isCheckedOutElsewhere = (branch: BranchInfo) => {
    if (!currentWorktreePath || !branch.checkedOutIn) return false;
    return branch.checkedOutIn.worktreePath !== currentWorktreePath;
  };

  const handleJump = (branch: BranchInfo, event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    event.preventDefault();
    if (!branch.checkedOutIn) return;

    if (branch.checkedOutIn.sessionId && onJumpToSession) {
      onJumpToSession(branch.checkedOutIn.sessionId);
    } else if (onStartSession) {
      onStartSession(branch.checkedOutIn.worktreePath);
    }
  };

  const onKeyDown = (event: React.KeyboardEvent<HTMLDivElement | HTMLInputElement>) => {
    if (event.key === 'Escape' && open) {
      closeDropdown();
      event.stopPropagation();
    }
  };

  return (
    <div className="branch-switcher" ref={wrapperRef}>
      <button
        className={`branch-trigger${disabled ? ' branch-disabled' : ''}`}
        onClick={openDropdown}
        title={disabled ? 'Unavailable while agent is running' : undefined}
        aria-label="Switch branch"
        aria-expanded={open}
        aria-haspopup="listbox"
        type="button"
      >
        <span className="branch-icon">⑂</span>
        <span className="branch-name">{currentBranch}</span>
        <svg className="branch-caret" width="10" height="6" viewBox="0 0 10 6" aria-hidden="true">
          <path d="M1 1l4 4 4-4" stroke="currentColor" fill="none" strokeWidth="1.5" strokeLinecap="round" />
        </svg>
      </button>

      {open ? (
        <div className="branch-dropdown" role="listbox" tabIndex={-1} aria-label="Branches" onKeyDown={onKeyDown}>
          <TuiMenuPanel>
            <div className="branch-filter-wrap">
              <input
                ref={filterInputRef}
                type="text"
                className="branch-filter"
                placeholder="Filter branches..."
                value={filterText}
                onChange={(event) => setFilterText(event.currentTarget.value)}
                onKeyDown={onKeyDown}
                aria-label="Filter branches"
              />
            </div>

            {switchError ? <div className="branch-error">{switchError}</div> : null}

            {showCreateOption && onCreateBranch ? (
              <div
                className="branch-create"
                role="option"
                aria-selected={false}
                tabIndex={-1}
                onMouseDown={() => onCreateBranch?.(filterText.trim())}
              >
                <span className="branch-create-icon">+</span>
                <span>
                  Create "<strong>{filterText.trim()}</strong>"
                </span>
              </div>
            ) : null}

            {loading ? (
              <div className="branch-loading">
                <CipherText loading text="Fetching branches..." />
              </div>
            ) : filteredBranches.length === 0 && !showCreateOption ? (
              <div className="branch-empty">No branches match</div>
            ) : (
              <div className="branch-list">
                {filteredBranches.map((branch) => {
                  const checkedOutElsewhere = isCheckedOutElsewhere(branch);

                  return (
                    <TuiMenuItem
                      key={branch.name}
                      role="option"
                      ariaSelected={branch.name === currentBranch}
                      disabled={checkedOutElsewhere || switching === branch.name}
                      onMouseDown={() => void handleSelect(branch.name)}
                    >
                      <>
                        <span className="branch-check">
                          {branch.name === currentBranch ? '✓' : <span className="branch-check--empty" />}
                        </span>
                        <span
                          className={`branch-option-name${branch.name === currentBranch ? ' branch-current' : ''}${checkedOutElsewhere ? ' branch-checked-out' : ''}`}
                        >
                          {branch.name}
                        </span>

                        {checkedOutElsewhere && branch.checkedOutIn && (onJumpToSession || onStartSession) ? (
                          <>
                            <span className="branch-worktree-name">({branch.checkedOutIn.worktreeName})</span>
                            <button
                              className="branch-jump-btn"
                              title="Jump to worktree"
                              type="button"
                              onMouseDown={(event) => handleJump(branch, event)}
                            >
                              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
                                <path d="M4.5 2H2.5C2.22 2 2 2.22 2 2.5V9.5C2 9.78 2.22 10 2.5 10H9.5C9.78 10 10 9.78 10 9.5V7.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" />
                                <path d="M7 2H10V5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
                                <path d="M10 2L5.5 6.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" />
                              </svg>
                            </button>
                          </>
                        ) : null}

                        {switching === branch.name ? <span className="branch-spinner">&hellip;</span> : null}
                      </>
                    </TuiMenuItem>
                  );
                })}
              </div>
            )}
          </TuiMenuPanel>
        </div>
      ) : null}
    </div>
  );
}

export default BranchSwitcher;

// frontend/src/components/BranchSwitcher.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query';
  import { fetchBranches, switchBranch } from '../lib/api.js';
  import type { BranchInfo } from '../lib/types.js';
  import CipherText from './CipherText.svelte';
  import TuiMenuItem from './TuiMenuItem.svelte';
  import TuiMenuPanel from './TuiMenuPanel.svelte';

  let {
    repoPath,
    currentBranch,
    onSwitch,
    disabled = false,
    currentWorktreePath,
    onJumpToSession,
    onStartSession,
    onCreateBranch,
  }: {
    repoPath: string;
    currentBranch: string;
    onSwitch: (branch: string) => void;
    disabled?: boolean;
    currentWorktreePath?: string;
    onJumpToSession?: (sessionId: string) => void;
    onStartSession?: (worktreePath: string) => void;
    onCreateBranch?: (branchName: string) => void;
  } = $props();

  let open = $state(false);
  let filterText = $state('');
  let wrapperEl = $state<HTMLDivElement | null>(null);
  let filterInputEl = $state<HTMLInputElement | null>(null);
  let switching = $state<string | null>(null);
  let switchError = $state<string | null>(null);

  const branchQuery = createQuery<BranchInfo[]>(() => ({
    queryKey: ['branches', repoPath],
    queryFn: () => fetchBranches(repoPath),
    staleTime: 30_000,
    enabled: open,
  }));

  let filteredBranches = $derived.by(() => {
    const branches = branchQuery.data ?? [];
    if (!filterText.trim()) return branches;
    const lower = filterText.toLowerCase();
    return branches.filter(b => b.name.toLowerCase().includes(lower));
  });

  let showCreateOption = $derived.by(() => {
    if (!filterText.trim()) return false;
    const branches = branchQuery.data ?? [];
    return !branches.some(b => b.name === filterText.trim());
  });

  function openDropdown() {
    if (disabled) return;
    open = true;
    filterText = '';
    switchError = null;
    requestAnimationFrame(() => filterInputEl?.focus());
  }

  function closeDropdown() {
    open = false;
    filterText = '';
  }

  async function handleSelect(branchName: string) {
    if (branchName === currentBranch) {
      closeDropdown();
      return;
    }
    switching = branchName;
    switchError = null;
    try {
      const result = await switchBranch(repoPath, branchName);
      if (result.success) {
        closeDropdown();
        onSwitch(branchName);
      } else {
        switchError = result.error ?? 'Failed to switch branch';
      }
    } catch {
      switchError = 'Failed to switch branch';
    } finally {
      switching = null;
    }
  }

  function isCheckedOutElsewhere(branch: BranchInfo): boolean {
    if (!currentWorktreePath || !branch.checkedOutIn) return false;
    return branch.checkedOutIn.worktreePath !== currentWorktreePath;
  }

  function handleJump(branch: BranchInfo, e: MouseEvent) {
    e.stopPropagation();
    e.preventDefault();
    if (!branch.checkedOutIn) return;
    if (branch.checkedOutIn.sessionId && onJumpToSession) {
      onJumpToSession(branch.checkedOutIn.sessionId);
    } else if (onStartSession) {
      onStartSession(branch.checkedOutIn.worktreePath);
    }
  }

  function onWindowClick(e: MouseEvent) {
    if (open && wrapperEl && document.contains(e.target as Node) && !wrapperEl.contains(e.target as Node)) {
      closeDropdown();
    }
  }

  function onKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && open) {
      closeDropdown();
      e.stopPropagation();
    }
  }
</script>

<svelte:window onclick={onWindowClick} />

<div class="branch-switcher" bind:this={wrapperEl}>
  <button
    class="branch-trigger"
    class:branch-disabled={disabled}
    onclick={openDropdown}
    title={disabled ? 'Unavailable while agent is running' : undefined}
    aria-label="Switch branch"
    aria-expanded={open}
    aria-haspopup="listbox"
  >
    <span class="branch-icon">⑂</span>
    <span class="branch-name">{currentBranch}</span>
    <svg class="branch-caret" width="10" height="6" viewBox="0 0 10 6" aria-hidden="true">
      <path d="M1 1l4 4 4-4" stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round"/>
    </svg>
  </button>

  {#if open}
    <div class="branch-dropdown" role="listbox" tabindex="-1" aria-label="Branches" onkeydown={onKeydown}>
      <TuiMenuPanel>
        <div class="branch-filter-wrap">
          <input
            bind:this={filterInputEl}
            type="text"
            class="branch-filter"
            placeholder="Filter branches..."
            bind:value={filterText}
            onkeydown={onKeydown}
            aria-label="Filter branches"
          />
        </div>

        {#if switchError}
          <div class="branch-error">{switchError}</div>
        {/if}

        {#if showCreateOption && onCreateBranch}
          <div class="branch-create" role="option" aria-selected={false} tabindex="-1" onmousedown={() => onCreateBranch?.(filterText.trim())}>
            <span class="branch-create-icon">+</span>
            <span>Create "<strong>{filterText.trim()}</strong>"</span>
          </div>
        {/if}

        {#if branchQuery.isLoading}
          <div class="branch-loading"><CipherText loading={true} text="Fetching branches..." /></div>
        {:else if filteredBranches.length === 0 && !showCreateOption}
          <div class="branch-empty">No branches match</div>
        {:else}
          <div class="branch-list">
            {#each filteredBranches as branch (branch.name)}
              {@const checkedOutElsewhere = isCheckedOutElsewhere(branch)}
              <TuiMenuItem
                role="option"
                ariaSelected={branch.name === currentBranch}
                disabled={checkedOutElsewhere || switching === branch.name}
                onmousedown={() => handleSelect(branch.name)}
              >
                {#snippet icon()}
                  {#if branch.name === currentBranch}
                    <span class="branch-check">&#10003;</span>
                  {:else}
                    <span class="branch-check branch-check--empty"></span>
                  {/if}
                {/snippet}
                <span class="branch-option-name" class:branch-current={branch.name === currentBranch} class:branch-checked-out={checkedOutElsewhere}>{branch.name}</span>
                {#if checkedOutElsewhere && branch.checkedOutIn && (onJumpToSession || onStartSession)}
                  <span class="branch-worktree-name">({branch.checkedOutIn.worktreeName})</span>
                  <button
                    class="branch-jump-btn"
                    title="Jump to worktree"
                    onmousedown={(e) => handleJump(branch, e)}
                  >
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
                      <path d="M4.5 2H2.5C2.22 2 2 2.22 2 2.5V9.5C2 9.78 2.22 10 2.5 10H9.5C9.78 10 10 9.78 10 9.5V7.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
                      <path d="M7 2H10V5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
                      <path d="M10 2L5.5 6.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
                    </svg>
                  </button>
                {/if}
                {#if switching === branch.name}
                  <span class="branch-spinner">&hellip;</span>
                {/if}
              </TuiMenuItem>
            {/each}
          </div>
        {/if}
      </TuiMenuPanel>
    </div>
  {/if}
</div>

<style>
  .branch-switcher {
    position: relative;
  }

  .branch-trigger {
    display: flex;
    align-items: center;
    gap: 4px;
    background: none;
    border: none;
    color: var(--text);
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    cursor: pointer;
    padding: 4px 8px;
    border-radius: 0;
    transition: background 0.12s;
    white-space: nowrap;
    min-width: 0;
  }

  .branch-trigger:hover {
    background: var(--surface-hover);
  }

  .branch-trigger.branch-disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .branch-trigger.branch-disabled:hover {
    background: none;
  }

  .branch-icon {
    color: var(--text-muted);
    font-size: var(--font-size-base);
    flex-shrink: 0;
  }

  .branch-name {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    max-width: 180px;
  }

  .branch-caret {
    flex-shrink: 0;
    color: var(--text-muted);
    margin-left: 1px;
  }

  .branch-dropdown {
    position: absolute;
    top: calc(100% + 4px);
    left: 0;
    min-width: 220px;
    max-width: 340px;
    z-index: 200;
  }

  .branch-filter-wrap {
    padding: 8px 8px 4px;
    border-bottom: 1px solid var(--border);
  }

  .branch-filter {
    width: 100%;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 0;
    color: var(--text);
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    padding: 4px 8px;
    outline: none;
    box-sizing: border-box;
  }

  .branch-filter:focus {
    border-color: var(--accent);
  }

  .branch-error {
    font-size: var(--font-size-xs);
    color: var(--status-error);
    padding: 4px 8px;
  }

  .branch-loading,
  .branch-empty {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    padding: 8px 12px;
    font-style: italic;
  }

  .branch-create {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 4px 8px;
    font-size: var(--font-size-xs);
    cursor: pointer;
    color: var(--accent);
    border-bottom: 1px solid var(--border);
    transition: background 0.1s;
  }

  .branch-create:hover {
    background: var(--surface-hover);
  }

  .branch-create-icon {
    font-weight: bold;
    flex-shrink: 0;
  }

  .branch-list {
    max-height: 240px;
    overflow-y: auto;
  }

  .branch-current {
    color: var(--accent);
  }

  .branch-checked-out {
    text-decoration: line-through;
    opacity: 0.5;
  }

  .branch-worktree-name {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    opacity: 0.7;
    flex-shrink: 0;
  }

  .branch-jump-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 18px;
    height: 18px;
    border: none;
    background: transparent;
    color: var(--text-muted);
    cursor: pointer;
    padding: 0;
    flex-shrink: 0;
    border-radius: 0;
    transition: color 0.12s, background 0.12s;
  }

  .branch-jump-btn:hover {
    color: var(--accent);
    background: var(--surface-hover);
  }

  .branch-check {
    font-size: var(--font-size-xs);
    width: 10px;
    flex-shrink: 0;
    color: var(--accent);
  }

  .branch-check--empty {
    display: inline-block;
  }

  .branch-option-name {
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 1;
    min-width: 0;
  }

  .branch-spinner {
    color: var(--text-muted);
    font-size: var(--font-size-xs);
    flex-shrink: 0;
  }
</style>
