// frontend/src/components/ChangedFiles.svelte
<script lang="ts">
  import type { Column } from './DataTable.svelte';
  import DataTable from './DataTable.svelte';
  import DiffViewer from './DiffViewer.svelte';
  import DiffSourceToggle from './DiffSourceToggle.svelte';
  import { fetchChangedFiles, fetchFileDiff, fetchDefaultBranch } from '../lib/api.js';
  import { generateFileSummary } from '../lib/diff-summary.js';
  import { statusIcon, statusColor, diffSourceToBase } from '../lib/diff-utils.js';
  import { rootShortName } from '../lib/utils.js';
  import type { ChangedFile, DiffSource } from '../lib/types.js';

  let {
    workspacePath,
    onExpandFile,
  }: {
    workspacePath: string;
    onExpandFile?: (file: ChangedFile, base: string | undefined) => void;
  } = $props();

  let files = $state<ChangedFile[]>([]);
  let aggregate = $state({ additions: 0, deletions: 0, fileCount: 0 });
  let loading = $state(false);
  let error = $state<string | undefined>(undefined);
  let expanded = $state(false);
  let expandedFile = $state<string | null>(null);
  let fileDiff = $state<string>('');
  let diffLoading = $state(false);
  let diffError = $state<string | undefined>(undefined);
  let sortBy = $state('path');
  let sortDir = $state<'asc' | 'desc'>('asc');
  let summaries = $state(new Map<string, string>());

  let diffSource = $state<DiffSource>('working');
  let defaultBranch = $state('main');

  let base = $derived(diffSourceToBase(diffSource, defaultBranch));

  const columns: Column[] = [
    { key: 'status', label: '', width: '24px' },
    { key: 'path', label: 'file', sortable: true },
    { key: 'additions', label: '+', sortable: true, width: '50px' },
    { key: 'deletions', label: '-', sortable: true, width: '50px' },
  ];

  let sortedFiles = $derived.by(() => {
    const sorted = [...files];
    sorted.sort((a, b) => {
      const aVal = (a as unknown as Record<string, unknown>)[sortBy];
      const bVal = (b as unknown as Record<string, unknown>)[sortBy];
      if (typeof aVal === 'number' && typeof bVal === 'number') {
        return sortDir === 'asc' ? aVal - bVal : bVal - aVal;
      }
      const aStr = String(aVal ?? '');
      const bStr = String(bVal ?? '');
      return sortDir === 'asc' ? aStr.localeCompare(bStr) : bStr.localeCompare(aStr);
    });
    return sorted;
  });

  export async function refresh() {
    if (!workspacePath) return;
    loading = true;
    error = undefined;
    try {
      const data = await fetchChangedFiles(workspacePath, base);
      files = data.files;
      aggregate = data.aggregate;
      error = data.error;
      summaries = new Map();
      expandedFile = null;
      fileDiff = '';
    } catch (err: unknown) {
      console.error('[ChangedFiles] refresh failed:', err instanceof Error ? err.message : String(err));
      error = 'Failed to fetch changed files';
      files = [];
    } finally {
      loading = false;
    }
  }

  // $effect is intentional here: refresh() is async and writes to $state — cannot be $derived.
  $effect(() => {
    void workspacePath;
    void base;
    if (workspacePath) void refresh();
  });

  $effect(() => {
    if (workspacePath) {
      fetchDefaultBranch(workspacePath).then(b => { defaultBranch = b; });
    }
  });

  function handleSort(col: string) {
    if (sortBy === col) {
      sortDir = sortDir === 'asc' ? 'desc' : 'asc';
    } else {
      sortBy = col;
      sortDir = 'asc';
    }
  }

  async function handleRowAction(file: ChangedFile) {
    if (expandedFile === file.path) {
      expandedFile = null;
      fileDiff = '';
      return;
    }
    const targetPath = file.path;
    expandedFile = targetPath;
    diffLoading = true;
    diffError = undefined;
    try {
      const data = await fetchFileDiff(workspacePath, file.path, base);
      if (expandedFile !== targetPath) return; // stale — user clicked a different file
      if (data.error) {
        diffError = data.error;
        fileDiff = '';
      } else {
        fileDiff = data.diff;
        if (!summaries.get(file.path) && fileDiff) {
          summaries.set(file.path, generateFileSummary(fileDiff, file.path, file.status));
          summaries = new Map(summaries); // trigger reactivity
        }
      }
    } catch (err: unknown) {
      if (expandedFile !== targetPath) return; // stale
      const message = err instanceof Error ? err.message : 'unknown error';
      diffError = `failed to load diff: ${message}`;
      fileDiff = '';
    } finally {
      if (expandedFile === targetPath) diffLoading = false;
    }
  }

</script>

<div class="changed-files-panel">
  <button
    class="summary-bar"
    onclick={() => { expanded = !expanded; if (expanded && files.length === 0) refresh(); }}
    aria-expanded={expanded}
  >
    <span class="summary-label">changed files</span>
    {#if aggregate.fileCount > 0}
      <span class="summary-stats">
        {aggregate.fileCount} file{aggregate.fileCount !== 1 ? 's' : ''}
        <span class="stat-add">+{aggregate.additions}</span>
        <span class="stat-del">-{aggregate.deletions}</span>
      </span>
    {:else if loading}
      <span class="summary-stats loading-text">scanning...</span>
    {:else}
      <span class="summary-stats muted">no changes</span>
    {/if}
    <span class="expand-indicator">{expanded ? '▾' : '▸'}</span>
  </button>

  {#if expanded}
    <div class="files-content">
      <div class="files-toolbar">
        <DiffSourceToggle
          value={diffSource}
          onchange={(s) => { diffSource = s; }}
          {defaultBranch}
        />
      </div>
      <DataTable
        {columns}
        rows={sortedFiles}
        groupBy="directory"
        {sortBy}
        {sortDir}
        onSort={handleSort}
        {loading}
        {error}
        emptyMessage="no changes detected"
        onRowAction={handleRowAction}
        maxHeight="300px"
      >
        {#snippet row(file: ChangedFile, _index: number)}
          <div class="file-row" class:expanded-row={expandedFile === file.path}>
            <span class="status-icon" style="color: {statusColor[file.status] ?? 'var(--text-muted)'}">{statusIcon[file.status] ?? '?'}</span>
            <span class="file-name" title={file.path}>
              {rootShortName(file.path)}
              {#if summaries.get(file.path)}
                <span class="file-summary">{summaries.get(file.path)}</span>
              {/if}
            </span>
            <span class="stat stat-add">+{file.additions}</span>
            <span class="stat stat-del">-{file.deletions}</span>
            {#if onExpandFile}
              <button
                class="expand-btn"
                title="open full diff"
                onclick={(e) => { e.stopPropagation(); onExpandFile(file, base); }}
                aria-label="expand diff for {file.path}"
              >[↗]</button>
            {/if}
          </div>
          {#if expandedFile === file.path}
            <div class="inline-diff">
              {#if diffError}
                <div class="diff-error">{diffError}</div>
              {:else}
                <DiffViewer diff={fileDiff} filePath={file.path} loading={diffLoading} />
              {/if}
            </div>
          {/if}
        {/snippet}

        {#snippet mobileCard(file: ChangedFile, _index: number)}
          <button class="mobile-file-card" onclick={() => handleRowAction(file)}>
            <div class="card-header">
              <span class="status-icon" style="color: {statusColor[file.status] ?? 'var(--text-muted)'}">{statusIcon[file.status] ?? '?'}</span>
              <span class="file-name">{rootShortName(file.path)}</span>
              <span class="card-stats">
                <span class="stat-add">+{file.additions}</span>
                <span class="stat-del">-{file.deletions}</span>
              </span>
            </div>
            {#if summaries.get(file.path)}
              <div class="card-summary">{summaries.get(file.path)}</div>
            {/if}
            {#if expandedFile === file.path}
              <div class="inline-diff">
                {#if diffError}
                  <div class="diff-error">{diffError}</div>
                {:else}
                  <DiffViewer diff={fileDiff} filePath={file.path} loading={diffLoading} />
                {/if}
              </div>
            {/if}
          </button>
        {/snippet}
      </DataTable>
    </div>
  {/if}
</div>

<style>
  .changed-files-panel {
    border-top: 1px solid var(--border, #333);
  }

  .summary-bar {
    display: flex;
    align-items: center;
    gap: 8px;
    width: 100%;
    padding: 6px 12px;
    background: transparent;
    border: none;
    cursor: pointer;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
    text-align: left;
  }

  .summary-bar:hover {
    background: var(--surface-hover, #141414);
  }

  .summary-label {
    color: var(--text, #e0e0e0);
  }

  .summary-stats {
    flex: 1;
  }

  .loading-text {
    opacity: 0.6;
  }

  .muted {
    opacity: 0.5;
  }

  .stat-add { color: var(--status-success, #4ade80); }
  .stat-del { color: var(--status-error, #f87171); }

  .diff-error {
    padding: 8px 12px;
    color: var(--status-error, #f87171);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
  }

  .expand-indicator {
    flex-shrink: 0;
    opacity: 0.5;
  }

  .files-content {
    border-top: 1px solid var(--border, #333);
  }

  .files-toolbar {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 4px 8px;
    border-bottom: 1px solid var(--border, #333);
  }

  .expand-btn {
    flex-shrink: 0;
    padding: 0 4px;
    background: transparent;
    border: 1px solid var(--border, #333);
    color: var(--text-muted, #888);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    cursor: pointer;
  }

  .expand-btn:hover {
    color: var(--accent, #d97757);
    border-color: var(--accent, #d97757);
  }

  .file-row {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 4px 8px;
    cursor: pointer;
  }

  .file-row:hover {
    background: var(--surface-hover, #141414);
  }

  .expanded-row {
    background: var(--surface-hover, #141414);
  }

  .status-icon {
    flex-shrink: 0;
    width: 16px;
    text-align: center;
    font-weight: bold;
  }

  .file-name {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text, #e0e0e0);
  }

  .file-summary {
    margin-left: 8px;
    color: var(--text-muted, #888);
    font-size: var(--font-size-xs, 0.75rem);
  }

  .stat {
    flex-shrink: 0;
    width: 40px;
    text-align: right;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
  }

  .inline-diff {
    margin: 4px 0 4px 24px;
  }

  .mobile-file-card {
    display: block;
    width: 100%;
    padding: 8px 12px;
    border: none;
    border-bottom: 1px solid var(--border, #333);
    background: transparent;
    cursor: pointer;
    text-align: left;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text, #e0e0e0);
  }

  .mobile-file-card:active {
    background: var(--surface-hover, #141414);
  }

  .card-header {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .card-stats {
    margin-left: auto;
    display: flex;
    gap: 8px;
  }

  .card-summary {
    margin-top: 4px;
    padding-left: 24px;
    color: var(--text-muted, #888);
  }
</style>

// frontend/src/components/ChangedFiles.tsx
import React, { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import type { ChangedFile, DiffSource } from '../lib/types.js';
import { fetchChangedFiles, fetchFileDiff, fetchDefaultBranch } from '../lib/api.js';
import { generateFileSummary } from '../lib/diff-summary.js';
import { statusIcon, statusColor, diffSourceToBase } from '../lib/diff-utils.js';
import { rootShortName } from '../lib/utils.js';
import { DiffViewer } from './DiffViewer.js';
import './ChangedFiles.css';

export interface ChangedFilesHandle {
  refresh: (force?: boolean) => Promise<void>;
}

export interface ChangedFilesProps {
  workspacePath: string;
  onExpandFile?: (file: ChangedFile, base: string | undefined) => void;
}

interface AggregateStats { additions: number; deletions: number; fileCount: number; }

const DIFF_SOURCES: { value: DiffSource; label: string }[] = [
  { value: 'working', label: 'working tree' },
  { value: 'staged', label: 'staged' },
  { value: 'branch', label: 'branch' },
];

function useIsMobile() {
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    const mql = window.matchMedia('(max-width: 600px)');
    setIsMobile(mql.matches);
    const handler = (e: MediaQueryListEvent) => setIsMobile(e.matches);
    mql.addEventListener('change', handler);
    return () => mql.removeEventListener('change', handler);
  }, []);
  return isMobile;
}

interface FileRowProps { file: ChangedFile; summary: string | undefined; expanded: boolean; fileDiff: string; diffLoading: boolean; diffError: string | undefined; onExpandFile?: (file: ChangedFile, base: string | undefined) => void; base: string | undefined; onClick: () => void; }

function FileRow({ file, summary, expanded, fileDiff, diffLoading, diffError, onExpandFile, base, onClick }: FileRowProps) {
  return (
    <button className="table-row" onClick={onClick}>
      <span className="cell cell--status" style={{ color: statusColor[file.status] ?? 'var(--text-muted)' }}>{statusIcon[file.status] ?? '?'}</span>
      <span className="cell cell--path" title={file.path}>{rootShortName(file.path)}{summary && <span className="file-summary">{summary}</span>}</span>
      <span className="cell cell--stat stat-add">+{file.additions}</span>
      <span className="cell cell--stat stat-del">-{file.deletions}</span>
      {onExpandFile && <button className="expand-btn" title="open full diff" onClick={(e) => { e.stopPropagation(); onExpandFile(file, base); }} aria-label={`expand diff for ${file.path}`}>[↗]</button>}
      {expanded && (
        <div className="inline-diff" onClick={(e) => e.stopPropagation()}>
          {diffError ? <div className="diff-error">{diffError}</div> : <DiffViewer diff={fileDiff} filePath={file.path} loading={diffLoading} />}
        </div>
      )}
    </button>
  );
}

function MobileCard({ file, summary, expanded, fileDiff, diffLoading, diffError, onClick }: Omit<FileRowProps, 'onExpandFile' | 'base'>) {
  return (
    <button className="mobile-file-card" onClick={onClick}>
      <div className="card-header">
        <span style={{ color: statusColor[file.status] ?? 'var(--text-muted)' }}>{statusIcon[file.status] ?? '?'}</span>
        <span>{rootShortName(file.path)}</span>
        <span className="card-stats"><span className="stat-add">+{file.additions}</span><span className="stat-del">-{file.deletions}</span></span>
      </div>
      {summary && <div className="card-summary">{summary}</div>}
      {expanded && (
        <div className="inline-diff" onClick={(e) => e.stopPropagation()}>
          {diffError ? <div className="diff-error">{diffError}</div> : <DiffViewer diff={fileDiff} filePath={file.path} loading={diffLoading} />}
        </div>
      )}
    </button>
  );
}

const COLUMNS = [
  { key: 'status', label: '', width: '24px' },
  { key: 'path', label: 'file', sortable: true },
  { key: 'additions', label: '+', sortable: true, width: '50px' },
  { key: 'deletions', label: '-', sortable: true, width: '50px' },
];

function useChangedFilesData(workspacePath: string, base: string | undefined) {
  const [files, setFiles] = useState<ChangedFile[]>([]);
  const [aggregate, setAggregate] = useState<AggregateStats>({ additions: 0, deletions: 0, fileCount: 0 });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | undefined>(undefined);
  const filesRef = useRef(files);
  const errorRef = useRef(error);
  filesRef.current = files;
  errorRef.current = error;

  const refresh = useCallback(async (force = false, expanded = true) => {
    if (!workspacePath || (!force && !expanded)) return;
    const showLoading = filesRef.current.length === 0 && !errorRef.current;
    if (showLoading) setLoading(true);
    try {
      const data = await fetchChangedFiles(workspacePath, base);
      setFiles(data.files);
      setAggregate(data.aggregate);
      setError(data.error);
    } catch {
      setError('Failed to fetch changed files');
      setFiles([]);
    } finally {
      setLoading(false);
    }
  }, [workspacePath, base]);

  return { files, setFiles, aggregate, loading, error, refresh };
}

function useFileDiff(workspacePath: string, base: string | undefined, summaries: Map<string, string>, setSummaries: React.Dispatch<React.SetStateAction<Map<string, string>>>) {
  const [expandedFile, setExpandedFile] = useState<string | null>(null);
  const [fileDiff, setFileDiff] = useState('');
  const [diffLoading, setDiffLoading] = useState(false);
  const [diffError, setDiffError] = useState<string | undefined>(undefined);

  const handleRowAction = useCallback(async (file: ChangedFile) => {
    if (expandedFile === file.path) { setExpandedFile(null); setFileDiff(''); return; }
    const targetPath = file.path;
    setExpandedFile(targetPath);
    setDiffLoading(true);
    setDiffError(undefined);
    try {
      const data = await fetchFileDiff(workspacePath, file.path, base);
      if (expandedFile !== targetPath) return;
      if (data.error) { setDiffError(data.error); setFileDiff(''); return; }
      setFileDiff(data.diff);
      if (!summaries.get(file.path) && data.diff) {
        setSummaries((prev) => new Map([...prev, [file.path, generateFileSummary(data.diff, file.path, file.status)]]));
      }
    } catch (err: unknown) {
      if (expandedFile !== targetPath) return;
      setDiffError(`failed to load diff: ${err instanceof Error ? err.message : 'unknown error'}`);
      setFileDiff('');
    } finally {
      setDiffLoading(false);
    }
  }, [expandedFile, workspacePath, base, summaries, setSummaries]);

  return { expandedFile, fileDiff, diffLoading, diffError, handleRowAction };
}

export const ChangedFiles = forwardRef<ChangedFilesHandle, ChangedFilesProps>(
  function ChangedFiles({ workspacePath, onExpandFile }, ref) {
    const [expanded, setExpanded] = useState(false);
    const [summaries, setSummaries] = useState(new Map<string, string>());
    const [sortBy, setSortBy] = useState('path');
    const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');
    const [diffSource, setDiffSource] = useState<DiffSource>('working');
    const [defaultBranch, setDefaultBranch] = useState('main');
    const isMobile = useIsMobile();
    const base = useMemo(() => diffSourceToBase(diffSource, defaultBranch), [diffSource, defaultBranch]);

    const { files, aggregate, loading, error, refresh } = useChangedFilesData(workspacePath, base);
    const { expandedFile, fileDiff, diffLoading, diffError, handleRowAction } = useFileDiff(workspacePath, base, summaries, setSummaries);

    const publicRefresh = useCallback((force = false) => refresh(force, expanded), [refresh, expanded]);
    useImperativeHandle(ref, () => ({ refresh: publicRefresh }), [publicRefresh]);

    useEffect(() => { if (workspacePath) void refresh(true, true); }, [workspacePath, base, refresh]);
    useEffect(() => {
      if (workspacePath) fetchDefaultBranch(workspacePath).then((b) => setDefaultBranch(b)).catch(() => {});
    }, [workspacePath]);

    const sortedFiles = useMemo(() => {
      const sorted = [...files];
      sorted.sort((a, b) => {
        const av = (a as unknown as Record<string, unknown>)[sortBy];
        const bv = (b as unknown as Record<string, unknown>)[sortBy];
        if (typeof av === 'number' && typeof bv === 'number') return sortDir === 'asc' ? av - bv : bv - av;
        return sortDir === 'asc' ? String(av ?? '').localeCompare(String(bv ?? '')) : String(bv ?? '').localeCompare(String(av ?? ''));
      });
      return sorted;
    }, [files, sortBy, sortDir]);

    const handleSort = useCallback((col: string) => {
      if (sortBy === col) setSortDir((d) => (d === 'asc' ? 'desc' : 'asc'));
      else { setSortBy(col); setSortDir('asc'); }
    }, [sortBy]);

    const handleToggle = useCallback(() => {
      setExpanded((prev) => { if (!prev && files.length === 0) void refresh(); return !prev; });
    }, [files.length, refresh]);

    return (
      <div className="changed-files-panel">
        <button className="summary-bar" onClick={handleToggle} aria-expanded={expanded}>
          <span className="summary-label">changed files</span>
          {aggregate.fileCount > 0 ? (
            <span className="summary-stats">{aggregate.fileCount} file{aggregate.fileCount !== 1 ? 's' : ''}{' '}<span className="stat-add">+{aggregate.additions}</span>{' '}<span className="stat-del">-{aggregate.deletions}</span></span>
          ) : loading ? (
            <span className="summary-stats loading-text">scanning...</span>
          ) : (
            <span className="summary-stats muted">no changes</span>
          )}
          <span className="expand-indicator">{expanded ? '▾' : '▸'}</span>
        </button>
        {expanded && (
          <div className="files-content">
            <div className="files-toolbar">
              <div className="diff-source-toggle" role="radiogroup" aria-label="diff source">
                {DIFF_SOURCES.map((opt) => (
                  <button key={opt.value} className={['toggle-option', diffSource === opt.value && 'active'].filter(Boolean).join(' ')} role="radio" aria-checked={diffSource === opt.value} onClick={() => setDiffSource(opt.value)}>
                    {opt.value === 'branch' ? `vs ${defaultBranch}` : opt.label}
                  </button>
                ))}
              </div>
            </div>
            {!isMobile && (
              <div className="data-table-header">
                {COLUMNS.map((col) => (
                  <div key={col.key} className="data-table-th" style={{ width: col.width, flex: col.width ? 'none' : '1' }}>
                    {col.sortable ? <button className="sort-trigger" onClick={() => handleSort(col.key)}>{col.label}{sortBy === col.key && <span>{sortDir === 'asc' ? ' ▲' : ' ▼'}</span>}</button> : col.label}
                  </div>
                ))}
              </div>
            )}
            <div className="scroll-container" style={{ maxHeight: '300px' }}>
              {loading && <div className="state-message">scanning...</div>}
              {error && <div className="state-message state-message--error">{error}</div>}
              {!loading && !error && sortedFiles.length === 0 && <div className="state-message">no changes detected</div>}
              {sortedFiles.map((file) => isMobile ? (
                <MobileCard key={file.path} file={file} summary={summaries.get(file.path)} expanded={expandedFile === file.path} fileDiff={fileDiff} diffLoading={diffLoading} diffError={diffError} onClick={() => void handleRowAction(file)} />
              ) : (
                <FileRow key={file.path} file={file} summary={summaries.get(file.path)} expanded={expandedFile === file.path} fileDiff={fileDiff} diffLoading={diffLoading} diffError={diffError} {...(onExpandFile ? { onExpandFile } : {})} base={base} onClick={() => void handleRowAction(file)} />
              ))}
            </div>
          </div>
        )}
      </div>
    );
  }
);

export default ChangedFiles;
