// frontend/src/components/CommandPalette.tsx
import React, {
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo,
} from 'react';
import { useQueryClient } from '@tanstack/react-query';
import type {
  Repo,
  SessionSummary,
  PullRequest,
  OrgPrsResponse,
  GitHubIssue,
  GitHubIssuesResponse,
  JiraIssue,
  JiraIssuesResponse,
} from '../lib/types.js';
import { derivePrDotStatus } from '../lib/pr-status.js';
import StatusDot from './StatusDot.js';
import { getAllActions } from '../lib/actions/registry.js';
import { formatShortcut } from '../lib/actions/shortcuts.js';
import type { ActionContext, Action } from '../lib/actions/types.js';
import { isMobileDevice, isMac } from '../lib/utils.js';
import { scopedSessionKey } from '../lib/session-keys.js';
import './CommandPalette.css';

// ── Constants ─────────────────────────────────────────────────────────────────

const TABS = ['all', 'sessions', 'workspaces', 'prs', 'settings'] as const;
type Tab = (typeof TABS)[number];

const SEC_GENERAL = 'section-general';
const SEC_INTEGRATIONS = 'section-integrations';
const SEC_ADVANCED = 'section-advanced';
const SEC_ABOUT = 'section-about';

const SETTINGS_ENTRIES = [
  {
    id: 'setting-agent',
    label: 'Default Coding Agent',
    description: 'Which AI agent to use',
    section: SEC_GENERAL,
  },
  {
    id: 'setting-continue',
    label: 'Continue Session',
    description: 'Resume last session when opening a repo',
    section: SEC_GENERAL,
  },
  {
    id: 'setting-yolo',
    label: 'YOLO Mode',
    description: 'Skip permission checks',
    section: SEC_GENERAL,
  },
  {
    id: 'setting-notifications',
    label: 'Notifications',
    description: 'Push notifications for sessions',
    section: SEC_GENERAL,
  },
  {
    id: 'setting-github',
    label: 'GitHub Connection',
    description: 'Connect GitHub account for PRs and CI',
    section: SEC_INTEGRATIONS,
  },
  {
    id: 'setting-webhooks',
    label: 'Webhooks',
    description: 'Real-time CI and PR updates',
    section: SEC_INTEGRATIONS,
  },
  {
    id: 'setting-jira',
    label: 'Jira',
    description: 'See Jira tickets in the sidebar',
    section: SEC_INTEGRATIONS,
  },
  {
    id: 'setting-devtools',
    label: 'Developer Tools',
    description: 'Mobile debug panel',
    section: SEC_ADVANCED,
  },
  {
    id: 'setting-analytics',
    label: 'Analytics',
    description: 'Local usage data',
    section: SEC_ADVANCED,
  },
  {
    id: 'setting-version',
    label: 'Version',
    description: 'Check for updates',
    section: SEC_ABOUT,
  },
] as const;

// ── Types ─────────────────────────────────────────────────────────────────────

type SettingEntry = (typeof SETTINGS_ENTRIES)[number];

type PaletteResult =
  | {
      type: 'workspace';
      id: string;
      label: string;
      sublabel?: string;
      data: Repo;
    }
  | {
      type: 'session';
      id: string;
      label: string;
      sublabel?: string;
      data: SessionSummary;
    }
  | {
      type: 'pr' | 'attention';
      id: string;
      label: string;
      sublabel?: string;
      data: PullRequest;
    }
  | {
      type: 'ticket';
      id: string;
      label: string;
      sublabel?: string;
      data: GitHubIssue | JiraIssue;
    }
  | {
      type: 'command';
      id: string;
      label: string;
      sublabel?: string;
      data: Action;
    }
  | {
      type: 'setting';
      id: string;
      label: string;
      sublabel?: string;
      data: SettingEntry;
    };

interface ResultGroup {
  label: string;
  items: PaletteResult[];
}

export interface CommandPaletteProps {
  open: boolean;
  workspaces: Repo[];
  sessions: SessionSummary[];
  actionContext: ActionContext;
  onClose: () => void;
  onSelectWorkspace: (path: string) => void;
  onSelectSession: (id: string) => void;
  onSelectPr: (pr: PullRequest) => void;
  onOpenSettings?: (sectionId: string) => void;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function categoryIcon(type: PaletteResult['type']): string {
  switch (type) {
    case 'workspace':
      return '■';
    case 'session':
      return '▸';
    case 'pr':
    case 'attention':
      return '●';
    case 'ticket':
      return '#';
    case 'command':
      return '>';
    case 'setting':
      return '*';
    default:
      return '';
  }
}

function matchesTab(type: PaletteResult['type'], activeTab: Tab): boolean {
  if (activeTab === 'all') return true;
  if (activeTab === 'sessions') return type === 'session' || type === 'command';
  if (activeTab === 'workspaces') return type === 'workspace';
  if (activeTab === 'prs') return type === 'pr' || type === 'attention';
  if (activeTab === 'settings') return type === 'setting' || type === 'command';
  return true;
}

// ── Hooks ─────────────────────────────────────────────────────────────────────

function useCachedData(open: boolean) {
  const queryClient = useQueryClient();
  // Snapshot cache on each render (deps include `open` to re-read when palette opens)
  const cachedPrs = useMemo<PullRequest[]>(
    () => queryClient.getQueryData<OrgPrsResponse>(['org-prs'])?.prs ?? [],
    [queryClient, open]
  );
  const cachedGithubIssues = useMemo<GitHubIssue[]>(
    () =>
      queryClient.getQueryData<GitHubIssuesResponse>(['github-issues'])
        ?.issues ?? [],
    [queryClient, open]
  );
  const cachedJiraIssues = useMemo<JiraIssue[]>(
    () =>
      queryClient.getQueryData<JiraIssuesResponse>(['jira-issues'])?.issues ??
      [],
    [queryClient, open]
  );
  return { cachedPrs, cachedGithubIssues, cachedJiraIssues };
}

function buildResults(
  q: string,
  workspaces: Repo[],
  sessions: SessionSummary[],
  cachedPrs: PullRequest[],
  cachedGithubIssues: GitHubIssue[],
  cachedJiraIssues: JiraIssue[],
  registryCommands: Action[],
  needsAttention: PullRequest[],
  activeTab: Tab
): PaletteResult[] {
  const items: PaletteResult[] = [];
  if (!q) {
    for (const pr of needsAttention)
      items.push({
        type: 'attention',
        id: `attn-${pr.number}`,
        label: `#${pr.number} ${pr.title}`,
        sublabel: pr.repoName ?? '',
        data: pr,
      });
    for (const ws of workspaces.slice(0, 5))
      items.push({
        type: 'workspace',
        id: `ws-${ws.path}`,
        label: ws.name,
        sublabel: ws.path,
        data: ws,
      });
    for (const a of registryCommands)
      items.push({
        type: 'command',
        id: `cmd-${a.id}`,
        label: a.label,
        sublabel: a.description ?? '',
        data: a,
      });
    return items.filter((r) => matchesTab(r.type, activeTab));
  }
  for (const ws of workspaces
    .filter((w) => w.name.toLowerCase().includes(q))
    .slice(0, 5))
    items.push({
      type: 'workspace',
      id: `ws-${ws.path}`,
      label: ws.name,
      sublabel: ws.path,
      data: ws,
    });
  for (const s of sessions
    .filter(
      (s) =>
        s.displayName.toLowerCase().includes(q) ||
        s.branchName.toLowerCase().includes(q) ||
        s.repoName.toLowerCase().includes(q)
    )
    .slice(0, 5)) {
    items.push({
      type: 'session',
      id: `sess-${s.id}`,
      label: s.displayName || s.branchName || s.repoName,
      sublabel: s.repoName,
      data: s,
    });
  }
  for (const pr of cachedPrs
    .filter(
      (pr) =>
        pr.title.toLowerCase().includes(q) ||
        String(pr.number).includes(q) ||
        pr.headRefName.toLowerCase().includes(q)
    )
    .slice(0, 5)) {
    items.push({
      type: 'pr',
      id: `pr-${pr.number}`,
      label: `#${pr.number} ${pr.title}`,
      sublabel: pr.repoName ?? pr.headRefName,
      data: pr,
    });
  }
  for (const issue of cachedGithubIssues
    .filter(
      (i) => i.title.toLowerCase().includes(q) || String(i.number).includes(q)
    )
    .slice(0, 3)) {
    items.push({
      type: 'ticket',
      id: `gh-${issue.number}`,
      label: `#${issue.number} ${issue.title}`,
      sublabel: issue.repoName,
      data: issue,
    });
  }
  for (const issue of cachedJiraIssues
    .filter(
      (i) =>
        i.title.toLowerCase().includes(q) || i.key.toLowerCase().includes(q)
    )
    .slice(0, 3)) {
    items.push({
      type: 'ticket',
      id: `jira-${issue.key}`,
      label: `${issue.key} ${issue.title}`,
      sublabel: issue.status,
      data: issue,
    });
  }
  for (const a of registryCommands.filter(
    (a) =>
      a.label.toLowerCase().includes(q) ||
      a.description?.toLowerCase().includes(q) ||
      a.aliases?.some((alias) => alias.toLowerCase().includes(q))
  )) {
    items.push({
      type: 'command',
      id: `cmd-${a.id}`,
      label: a.label,
      sublabel: a.description ?? '',
      data: a,
    });
  }
  for (const s of SETTINGS_ENTRIES.filter(
    (s) =>
      s.label.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q)
  ))
    items.push({
      type: 'setting',
      id: s.id,
      label: s.label,
      sublabel: s.description,
      data: s,
    });
  return items.filter((r) => matchesTab(r.type, activeTab));
}

function useGroupedResults(
  results: PaletteResult[],
  query: string
): ResultGroup[] {
  return useMemo(() => {
    const q = query.toLowerCase().trim();
    const typeOrder: Array<{ type: PaletteResult['type']; label: string }> = q
      ? [
          { type: 'workspace', label: 'workspaces' },
          { type: 'session', label: 'sessions' },
          { type: 'pr', label: 'pull requests' },
          { type: 'ticket', label: 'tickets' },
          { type: 'command', label: 'commands' },
          { type: 'setting', label: 'settings' },
        ]
      : [
          { type: 'attention', label: 'needs attention' },
          { type: 'workspace', label: 'workspaces' },
          { type: 'command', label: 'commands' },
        ];
    return typeOrder.flatMap(({ type, label }) => {
      const items = results.filter((r) => r.type === type);
      return items.length > 0 ? [{ label, items }] : [];
    });
  }, [results, query]);
}

// ── usePaletteState hook ───────────────────────────────────────────────────────

function usePaletteState(
  open: boolean,
  inputRef: React.RefObject<HTMLInputElement | null>
) {
  const [query, setQuery] = useState('');
  const [debouncedQuery, setDebouncedQuery] = useState('');
  const [focusedIndex, setFocusedIndex] = useState(0);
  const [activeTab, setActiveTab] = useState<Tab>('all');
  const [dragOffset, setDragOffset] = useState(0);
  const [dragging, setDragging] = useState(false);
  const dragStartYRef = useRef(0);

  useEffect(() => {
    if (open) {
      setQuery('');
      setDebouncedQuery('');
      setFocusedIndex(0);
      setActiveTab('all');
      setDragOffset(0);
      setDragging(false);
      requestAnimationFrame(() => inputRef.current?.focus());
    }
  }, [open, inputRef]);

  useEffect(() => {
    const timer = setTimeout(() => setDebouncedQuery(query), 150);
    return () => clearTimeout(timer);
  }, [query]);

  return {
    query,
    setQuery,
    debouncedQuery,
    focusedIndex,
    setFocusedIndex,
    activeTab,
    setActiveTab,
    dragOffset,
    setDragOffset,
    dragging,
    setDragging,
    dragStartYRef,
  };
}

// ── usePaletteHandlers hook ────────────────────────────────────────────────────

function usePaletteHandlers(
  flatItems: PaletteResult[],
  focusedIndex: number,
  activeTab: Tab,
  setFocusedIndex: (v: number | ((p: number) => number)) => void,
  setActiveTab: (t: Tab) => void,
  dragging: boolean,
  dragOffset: number,
  setDragging: (v: boolean) => void,
  setDragOffset: (v: number) => void,
  dragStartYRef: React.RefObject<number>,
  resultsRef: React.RefObject<HTMLDivElement | null>,
  actionContext: ActionContext,
  onClose: () => void,
  onSelectWorkspace: (path: string) => void,
  onSelectSession: (id: string) => void,
  onSelectPr: (pr: PullRequest) => void,
  onOpenSettings?: (sectionId: string) => void
) {
  const scrollFocusedIntoView = useCallback(() => {
    requestAnimationFrame(() => {
      document
        .querySelector('.palette-item.focused')
        ?.scrollIntoView({ block: 'nearest' });
    });
  }, []);

  const selectItem = useCallback(
    async (item: PaletteResult) => {
      if (item.type === 'command') {
        try {
          await (item.data as Action).handler(actionContext);
        } finally {
          onClose();
        }
        return;
      }
      onClose();
      if (item.type === 'workspace')
        onSelectWorkspace((item.data as Repo).path);
      else if (item.type === 'session')
        onSelectSession(scopedSessionKey(item.data as SessionSummary));
      else if (item.type === 'attention' || item.type === 'pr')
        onSelectPr(item.data as PullRequest);
      else if (item.type === 'setting')
        onOpenSettings?.((item.data as SettingEntry).section);
    },
    [
      actionContext,
      onClose,
      onSelectWorkspace,
      onSelectSession,
      onSelectPr,
      onOpenSettings,
    ]
  );

  const handleKeydown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onClose();
        return;
      }
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        if (flatItems.length === 0) return;
        setFocusedIndex((p) => Math.min(p + 1, flatItems.length - 1));
        scrollFocusedIntoView();
        return;
      }
      if (e.key === 'ArrowUp') {
        e.preventDefault();
        if (flatItems.length === 0) return;
        setFocusedIndex((p) => Math.max(p - 1, 0));
        scrollFocusedIntoView();
        return;
      }
      if (e.key === 'Enter') {
        e.preventDefault();
        const item = flatItems[focusedIndex];
        if (item) void selectItem(item);
        return;
      }
      if (e.key === 'Tab') {
        e.preventDefault();
        const idx = TABS.indexOf(activeTab);
        setActiveTab(
          e.shiftKey
            ? TABS[(idx - 1 + TABS.length) % TABS.length]!
            : TABS[(idx + 1) % TABS.length]!
        );
        setFocusedIndex(0);
      }
    },
    [
      onClose,
      flatItems,
      focusedIndex,
      scrollFocusedIntoView,
      selectItem,
      activeTab,
      setActiveTab,
      setFocusedIndex,
    ]
  );

  const handleBackdropClick = useCallback(
    (e: React.MouseEvent) => {
      if ((e.target as HTMLElement).classList.contains('palette-overlay'))
        onClose();
    },
    [onClose]
  );

  const handleDragStart = useCallback(
    (e: React.TouchEvent) => {
      if (!isMobileDevice) return;
      const target = e.target as HTMLElement;
      const isHandle =
        target.classList.contains('drag-handle') ||
        target.classList.contains('drag-bar');
      if (!isHandle && resultsRef.current && resultsRef.current.scrollTop > 0)
        return;
      dragStartYRef.current = e.touches[0]!.clientY;
      setDragging(true);
    },
    [dragStartYRef, resultsRef, setDragging]
  );

  const handleDragMove = useCallback(
    (e: React.TouchEvent) => {
      if (!dragging) return;
      const delta = e.touches[0]!.clientY - dragStartYRef.current;
      if (delta > 0) setDragOffset(delta);
    },
    [dragging, dragStartYRef, setDragOffset]
  );

  const handleDragEnd = useCallback(() => {
    if (!dragging) return;
    setDragging(false);
    if (dragOffset > 100) onClose();
    setDragOffset(0);
  }, [dragging, dragOffset, onClose, setDragging, setDragOffset]);

  return {
    handleKeydown,
    handleBackdropClick,
    handleDragStart,
    handleDragMove,
    handleDragEnd,
    selectItem,
  };
}

// ── Main Component ────────────────────────────────────────────────────────────

export function CommandPalette({
  open,
  workspaces,
  sessions,
  actionContext,
  onClose,
  onSelectWorkspace,
  onSelectSession,
  onSelectPr,
  onOpenSettings,
}: CommandPaletteProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const resultsRef = useRef<HTMLDivElement>(null);

  const {
    query,
    setQuery,
    debouncedQuery,
    focusedIndex,
    setFocusedIndex,
    activeTab,
    setActiveTab,
    dragOffset,
    setDragOffset,
    dragging,
    setDragging,
    dragStartYRef,
  } = usePaletteState(open, inputRef);
  const { cachedPrs, cachedGithubIssues, cachedJiraIssues } =
    useCachedData(open);
  const registryCommands = useMemo(
    () => getAllActions().filter((a) => !a.when || a.when(actionContext)),
    [actionContext]
  );
  const needsAttention = useMemo(
    () =>
      cachedPrs
        .filter(
          (pr) =>
            pr.state === 'OPEN' &&
            (pr.reviewDecision === 'CHANGES_REQUESTED' ||
              pr.role === 'reviewer')
        )
        .slice(0, 5),
    [cachedPrs]
  );

  const results = useMemo(
    () =>
      buildResults(
        debouncedQuery.toLowerCase().trim(),
        workspaces,
        sessions,
        cachedPrs,
        cachedGithubIssues,
        cachedJiraIssues,
        registryCommands,
        needsAttention,
        activeTab
      ),
    [
      debouncedQuery,
      workspaces,
      sessions,
      cachedPrs,
      cachedGithubIssues,
      cachedJiraIssues,
      registryCommands,
      needsAttention,
      activeTab,
    ]
  );
  const groupedResults = useGroupedResults(results, debouncedQuery);
  const flatItems = useMemo(
    () => groupedResults.flatMap((g) => g.items),
    [groupedResults]
  );

  useEffect(() => {
    if (focusedIndex >= flatItems.length)
      setFocusedIndex(Math.max(0, flatItems.length - 1));
  }, [flatItems.length, focusedIndex, setFocusedIndex]);

  const {
    handleKeydown,
    handleBackdropClick,
    handleDragStart,
    handleDragMove,
    handleDragEnd,
    selectItem,
  } = usePaletteHandlers(
    flatItems,
    focusedIndex,
    activeTab,
    setFocusedIndex,
    setActiveTab,
    dragging,
    dragOffset,
    setDragging,
    setDragOffset,
    dragStartYRef,
    resultsRef,
    actionContext,
    onClose,
    onSelectWorkspace,
    onSelectSession,
    onSelectPr,
    onOpenSettings
  );

  if (!open) return null;
  const paletteStyle =
    isMobileDevice && dragOffset > 0
      ? { transform: `translateY(${dragOffset}px)` }
      : undefined;

  return (
    <div
      className={['palette-overlay', isMobileDevice ? 'mobile' : '']
        .filter(Boolean)
        .join(' ')}
      onClick={handleBackdropClick}
    >
      <div
        className={['palette', isMobileDevice ? 'mobile' : '']
          .filter(Boolean)
          .join(' ')}
        role="dialog"
        tabIndex={-1}
        aria-modal="true"
        aria-label="Command palette"
        style={paletteStyle}
        onTouchStart={isMobileDevice ? handleDragStart : undefined}
        onTouchMove={isMobileDevice ? handleDragMove : undefined}
        onTouchEnd={isMobileDevice ? handleDragEnd : undefined}
        onTouchCancel={isMobileDevice ? handleDragEnd : undefined}
      >
        {isMobileDevice && (
          <div className="drag-handle">
            <span className="drag-bar" />
          </div>
        )}
        <div className="palette-input-row">
          <span className="palette-prompt">&gt;</span>
          <input
            ref={inputRef}
            className="palette-search-input"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={handleKeydown}
            placeholder="search commands, workspaces, sessions..."
            autoComplete="off"
            spellCheck={false}
            role="combobox"
            aria-expanded={flatItems.length > 0}
            aria-controls="palette-results"
            aria-activedescendant={
              flatItems[focusedIndex]
                ? `palette-item-${flatItems[focusedIndex]!.id}`
                : undefined
            }
          />
        </div>
        <div className="palette-tabs" role="tablist">
          {TABS.map((tab) => (
            <button
              key={tab}
              className={['palette-tab', activeTab === tab ? 'active' : '']
                .filter(Boolean)
                .join(' ')}
              role="tab"
              aria-selected={activeTab === tab}
              onClick={() => {
                setActiveTab(tab);
                setFocusedIndex(0);
              }}
            >
              {tab}
            </button>
          ))}
        </div>
        {(() => {
          const flatIndexMap = new Map(
            flatItems.map((item, i) => [item.id, i])
          );
          if (flatItems.length === 0 && debouncedQuery.trim()) {
            return (
              <div className="palette-results" ref={resultsRef} role="listbox">
                <div className="palette-empty">
                  no results for &quot;{debouncedQuery}&quot;
                </div>
              </div>
            );
          }
          return (
            <div
              className="palette-results"
              id="palette-results"
              role="listbox"
              ref={resultsRef}
            >
              {groupedResults.map((group) => (
                <div key={group.label} role="presentation">
                  <div className="palette-category" role="presentation">
                    {group.label}
                    {group.label === 'needs attention' && (
                      <span className="category-count">
                        ({group.items.length})
                      </span>
                    )}
                  </div>
                  {group.items.map((item) => {
                    const globalIndex = flatIndexMap.get(item.id) ?? -1;
                    const isFocused = globalIndex === focusedIndex;
                    return (
                      <div
                        key={item.id}
                        id={`palette-item-${item.id}`}
                        className={['palette-item', isFocused ? 'focused' : '']
                          .filter(Boolean)
                          .join(' ')}
                        role="option"
                        tabIndex={-1}
                        aria-selected={isFocused}
                        onClick={() => void selectItem(item)}
                        onMouseEnter={() => setFocusedIndex(globalIndex)}
                      >
                        <span
                          className={['item-cursor', isFocused ? 'visible' : '']
                            .filter(Boolean)
                            .join(' ')}
                        >
                          &gt;
                        </span>
                        {item.type === 'attention' || item.type === 'pr' ? (
                          <StatusDot
                            status={derivePrDotStatus(item.data as PullRequest)}
                            size={7}
                          />
                        ) : item.type === 'command' &&
                          (item.data as Action).icon ? (
                          <span className="item-icon">
                            {(item.data as Action).icon}
                          </span>
                        ) : (
                          <span className="item-icon">
                            {categoryIcon(item.type)}
                          </span>
                        )}
                        <span className="item-label">{item.label}</span>
                        {item.sublabel && (
                          <span className="item-sublabel">{item.sublabel}</span>
                        )}
                        {!isMobileDevice &&
                          item.type === 'command' &&
                          (item.data as Action).shortcut && (
                            <kbd className="item-shortcut">
                              {formatShortcut(
                                (item.data as Action).shortcut!.key,
                                isMac
                              )}
                            </kbd>
                          )}
                      </div>
                    );
                  })}
                </div>
              ))}
            </div>
          );
        })()}
        {!isMobileDevice && (
          <div className="palette-footer">
            <span className="hint">↑↓ navigate</span>
            <span className="hint">tab category</span>
            <span className="hint">↵ select</span>
            <span className="hint">esc close</span>
          </div>
        )}
      </div>
    </div>
  );
}

export default CommandPalette;

// frontend/src/components/CommandPalette.svelte
<script lang="ts">
  import { useQueryClient } from '@tanstack/svelte-query';
  import type { Repo, SessionSummary, PullRequest, OrgPrsResponse, GitHubIssue, GitHubIssuesResponse, JiraIssue, JiraIssuesResponse } from '../lib/types.js';
  import { derivePrDotStatus } from '../lib/pr-status.js';
  import StatusDot from './StatusDot.svelte';
  import TuiInput from './TuiInput.svelte';
  import { getAllActions } from '../lib/actions/registry.svelte.js';
  import { formatShortcut } from '../lib/actions/shortcuts.js';
  import type { ActionContext, Action } from '../lib/actions/types.js';
  import { onDestroy } from 'svelte';
  import { isMobileDevice, isMac } from '../lib/utils.js';

  const TABS = ['all', 'sessions', 'workspaces', 'prs', 'settings'] as const;
  type Tab = typeof TABS[number];

  let {
    open = false,
    workspaces,
    sessions,
    actionContext,
    onClose,
    onSelectWorkspace,
    onSelectSession,
    onSelectPr,
    onOpenSettings,
  }: {
    open: boolean;
    workspaces: Repo[];
    sessions: SessionSummary[];
    actionContext: ActionContext;
    onClose: () => void;
    onSelectWorkspace: (path: string) => void;
    onSelectSession: (id: string) => void;
    onSelectPr: (pr: PullRequest) => void;
    onOpenSettings?: (sectionId: string) => void;
  } = $props();

  const queryClient = useQueryClient();

  let query = $state('');
  let focusedIndex = $state(0);
  let inputWrapperEl = $state<HTMLDivElement | undefined>(undefined);
  let resultsEl = $state<HTMLDivElement | undefined>(undefined);
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  let debouncedQuery = $state('');
  let activeTab = $state<Tab>('all');

  // Drag-dismiss state (mobile)
  let dragStartY = 0;
  let dragOffset = $state(0);
  let dragging = $state(false);

  // Read cached data from svelte-query
  let cachedPrs = $derived<PullRequest[]>(
    (queryClient.getQueryData<OrgPrsResponse>(['org-prs'])?.prs ?? [])
  );
  let cachedGithubIssues = $derived<GitHubIssue[]>(
    (queryClient.getQueryData<GitHubIssuesResponse>(['github-issues'])?.issues ?? [])
  );
  let cachedJiraIssues = $derived<JiraIssue[]>(
    (queryClient.getQueryData<JiraIssuesResponse>(['jira-issues'])?.issues ?? [])
  );

  // Settings entries (searchable)
  const SETTINGS_ENTRIES = [
    { id: 'setting-agent', label: 'Default Coding Agent', description: 'Which AI agent to use', section: 'section-general' },
    { id: 'setting-continue', label: 'Continue Session', description: 'Resume last session when opening a repo', section: 'section-general' },
    { id: 'setting-yolo', label: 'YOLO Mode', description: 'Skip permission checks', section: 'section-general' },
    { id: 'setting-tmux', label: 'Launch in tmux', description: 'Wrap sessions in tmux', section: 'section-general' },
    { id: 'setting-notifications', label: 'Notifications', description: 'Push notifications for sessions', section: 'section-general' },
    { id: 'setting-github', label: 'GitHub Connection', description: 'Connect GitHub account for PRs and CI', section: 'section-integrations' },
    { id: 'setting-webhooks', label: 'Webhooks', description: 'Real-time CI and PR updates', section: 'section-integrations' },
    { id: 'setting-jira', label: 'Jira', description: 'See Jira tickets in the sidebar', section: 'section-integrations' },
    { id: 'setting-devtools', label: 'Developer Tools', description: 'Mobile debug panel', section: 'section-advanced' },
    { id: 'setting-analytics', label: 'Analytics', description: 'Local usage data', section: 'section-advanced' },
    { id: 'setting-version', label: 'Version', description: 'Check for updates', section: 'section-about' },
  ];

  // Registry commands filtered by context
  let registryCommands = $derived.by(() => {
    return getAllActions().filter(a => !a.when || a.when(actionContext));
  });

  // "Needs Attention" — PRs with changes requested or awaiting review
  let needsAttention = $derived(
    cachedPrs.filter(pr =>
      pr.state === 'OPEN' && (
        pr.reviewDecision === 'CHANGES_REQUESTED' ||
        pr.role === 'reviewer'
      )
    ).slice(0, 5)
  );

  // Search results
  type PaletteResult =
    | { type: 'workspace'; id: string; label: string; sublabel?: string; data: Repo }
    | { type: 'session'; id: string; label: string; sublabel?: string; data: SessionSummary }
    | { type: 'pr' | 'attention'; id: string; label: string; sublabel?: string; data: PullRequest }
    | { type: 'ticket'; id: string; label: string; sublabel?: string; data: GitHubIssue | JiraIssue }
    | { type: 'command'; id: string; label: string; sublabel?: string; data: Action }
    | { type: 'setting'; id: string; label: string; sublabel?: string; data: { id: string; label: string; description: string; section: string } };

  // Tab filter mapping
  function matchesTab(type: PaletteResult['type']): boolean {
    if (activeTab === 'all') return true;
    switch (activeTab) {
      case 'sessions': return type === 'session' || type === 'command';
      case 'workspaces': return type === 'workspace';
      case 'prs': return type === 'pr' || type === 'attention';
      case 'settings': return type === 'setting' || type === 'command';
      default: return true;
    }
  }

  let results = $derived.by((): PaletteResult[] => {
    const q = debouncedQuery.toLowerCase().trim();
    const items: PaletteResult[] = [];

    if (!q) {
      for (const pr of needsAttention) {
        items.push({ type: 'attention', id: `attn-${pr.number}`, label: `#${pr.number} ${pr.title}`, sublabel: pr.repoName ?? '', data: pr });
      }
      for (const ws of workspaces.slice(0, 5)) {
        items.push({ type: 'workspace', id: `ws-${ws.path}`, label: ws.name, sublabel: ws.path, data: ws });
      }
      for (const action of registryCommands) {
        items.push({ type: 'command', id: `cmd-${action.id}`, label: action.label, sublabel: action.description ?? '', data: action });
      }
      return items.filter(r => matchesTab(r.type));
    }

    // Workspaces
    for (const ws of workspaces.filter(w => w.name.toLowerCase().includes(q)).slice(0, 5)) {
      items.push({ type: 'workspace', id: `ws-${ws.path}`, label: ws.name, sublabel: ws.path, data: ws });
    }
    // Sessions
    for (const s of sessions.filter(s => s.displayName.toLowerCase().includes(q) || s.branchName.toLowerCase().includes(q) || s.repoName.toLowerCase().includes(q)).slice(0, 5)) {
      items.push({ type: 'session', id: `sess-${s.id}`, label: s.displayName || s.branchName || s.repoName, sublabel: s.repoName, data: s });
    }
    // PRs
    for (const pr of cachedPrs.filter(pr => pr.title.toLowerCase().includes(q) || String(pr.number).includes(q) || pr.headRefName.toLowerCase().includes(q)).slice(0, 5)) {
      items.push({ type: 'pr', id: `pr-${pr.number}`, label: `#${pr.number} ${pr.title}`, sublabel: pr.repoName ?? pr.headRefName, data: pr });
    }
    // GitHub Issues
    for (const issue of cachedGithubIssues.filter(i => i.title.toLowerCase().includes(q) || String(i.number).includes(q)).slice(0, 3)) {
      items.push({ type: 'ticket', id: `gh-${issue.number}`, label: `#${issue.number} ${issue.title}`, sublabel: issue.repoName, data: issue });
    }
    // Jira Issues
    for (const issue of cachedJiraIssues.filter(i => i.title.toLowerCase().includes(q) || i.key.toLowerCase().includes(q)).slice(0, 3)) {
      items.push({ type: 'ticket', id: `jira-${issue.key}`, label: `${issue.key} ${issue.title}`, sublabel: issue.status, data: issue });
    }
    // Commands from registry
    for (const action of registryCommands.filter(a => a.label.toLowerCase().includes(q) || (a.description?.toLowerCase().includes(q)) || (a.aliases?.some(alias => alias.toLowerCase().includes(q))))) {
      items.push({ type: 'command', id: `cmd-${action.id}`, label: action.label, sublabel: action.description ?? '', data: action });
    }
    // Settings
    for (const s of SETTINGS_ENTRIES.filter(s => s.label.toLowerCase().includes(q) || s.description.toLowerCase().includes(q))) {
      items.push({ type: 'setting', id: s.id, label: s.label, sublabel: s.description, data: s });
    }
    return items.filter(r => matchesTab(r.type));
  });

  // Group results by type
  interface ResultGroup { label: string; items: PaletteResult[]; }

  let groupedResults = $derived.by((): ResultGroup[] => {
    const q = debouncedQuery.toLowerCase().trim();
    const groups: ResultGroup[] = [];
    const typeOrder: Array<{ type: PaletteResult['type']; label: string }> = q
      ? [
          { type: 'workspace', label: 'workspaces' },
          { type: 'session', label: 'sessions' },
          { type: 'pr', label: 'pull requests' },
          { type: 'ticket', label: 'tickets' },
          { type: 'command', label: 'commands' },
          { type: 'setting', label: 'settings' },
        ]
      : [
          { type: 'attention', label: 'needs attention' },
          { type: 'workspace', label: 'workspaces' },
          { type: 'command', label: 'commands' },
        ];
    for (const { type, label } of typeOrder) {
      const items = results.filter(r => r.type === type);
      if (items.length > 0) groups.push({ label, items });
    }
    return groups;
  });

  let flatItems = $derived(groupedResults.flatMap(g => g.items));
  let flatIndexMap = $derived(new Map(flatItems.map((item, i) => [item.id, i])));

  $effect(() => {
    if (focusedIndex >= flatItems.length) focusedIndex = Math.max(0, flatItems.length - 1);
  });

  $effect(() => {
    if (open) {
      query = '';
      debouncedQuery = '';
      focusedIndex = 0;
      activeTab = 'all';
      dragOffset = 0;
      dragging = false;
      requestAnimationFrame(() => inputWrapperEl?.querySelector('input')?.focus());
    }
  });

  onDestroy(() => { if (debounceTimer) clearTimeout(debounceTimer); });

  function handleInput() {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => { debouncedQuery = query; }, 150);
  }

  async function selectItem(item: PaletteResult) {
    if (item.type === 'command') {
      try {
        await item.data.handler(actionContext);
        onClose();
      } catch (err) {
        console.error(`Action "${item.data.id}" failed:`, err);
        onClose();
      }
      return;
    }
    onClose();
    switch (item.type) {
      case 'workspace': onSelectWorkspace(item.data.path); break;
      case 'session': onSelectSession(item.data.id); break;
      case 'attention': case 'pr': onSelectPr(item.data); break;
      case 'ticket': break;
      case 'setting': onOpenSettings?.(item.data.section); break;
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') { e.preventDefault(); onClose(); return; }
    if (e.key === 'ArrowDown') { e.preventDefault(); focusedIndex = Math.min(focusedIndex + 1, flatItems.length - 1); scrollFocusedIntoView(); return; }
    if (e.key === 'ArrowUp') { e.preventDefault(); focusedIndex = Math.max(focusedIndex - 1, 0); scrollFocusedIntoView(); return; }
    if (e.key === 'Enter') { e.preventDefault(); const item = flatItems[focusedIndex]; if (item) selectItem(item); return; }
    if (e.key === 'Tab') {
      e.preventDefault();
      const idx = TABS.indexOf(activeTab);
      activeTab = e.shiftKey ? TABS[(idx - 1 + TABS.length) % TABS.length]! : TABS[(idx + 1) % TABS.length]!;
      focusedIndex = 0;
      return;
    }
  }

  function scrollFocusedIntoView() {
    requestAnimationFrame(() => {
      const el = document.querySelector('.palette-item.focused');
      el?.scrollIntoView({ block: 'nearest' });
    });
  }

  function handleBackdropClick(e: MouseEvent) {
    if ((e.target as HTMLElement).classList.contains('palette-overlay')) onClose();
  }

  function categoryIcon(type: PaletteResult['type']): string {
    switch (type) {
      case 'workspace': return '■';
      case 'session': return '▸';
      case 'pr': case 'attention': return '●';
      case 'ticket': return '#';
      case 'command': return '>';
      case 'setting': return '*';
      default: return '';
    }
  }

  // Mobile swipe-down dismiss
  function handleDragStart(e: TouchEvent) {
    if (!isMobileDevice) return;
    const target = e.target as HTMLElement;
    const isHandle = target.classList.contains('drag-handle') || target.classList.contains('drag-bar');
    if (!isHandle && resultsEl && resultsEl.scrollTop > 0) return;
    dragStartY = e.touches[0]!.clientY;
    dragging = true;
  }

  function handleDragMove(e: TouchEvent) {
    if (!dragging) return;
    const delta = e.touches[0]!.clientY - dragStartY;
    if (delta > 0) dragOffset = delta;
  }

  function handleDragEnd() {
    if (!dragging) return;
    dragging = false;
    if (dragOffset > 100) onClose();
    dragOffset = 0;
  }
</script>

{#if open}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="palette-overlay" class:mobile={isMobileDevice} onclick={handleBackdropClick}>
    <div
      class="palette"
      class:mobile={isMobileDevice}
      role="dialog"
      tabindex="-1"
      aria-modal="true"
      aria-label="Command palette"
      style={isMobileDevice && dragOffset > 0 ? `transform: translateY(${dragOffset}px)` : ''}
      ontouchstart={handleDragStart}
      ontouchmove={handleDragMove}
      ontouchend={handleDragEnd}
      ontouchcancel={handleDragEnd}
    >
      {#if isMobileDevice}
        <div class="drag-handle"><span class="drag-bar"></span></div>
      {/if}

      <div class="palette-input-row" bind:this={inputWrapperEl}>
        <span class="palette-prompt">&gt;</span>
        <TuiInput
          bind:value={query}
          placeholder="search commands, workspaces, sessions..."
          oninput={handleInput}
          onkeydown={handleKeydown}
          autocomplete="off"
          spellcheck={false}
          role="combobox"
          aria-expanded={flatItems.length > 0}
          aria-controls="palette-results"
          aria-activedescendant={flatItems[focusedIndex] ? `palette-item-${flatItems[focusedIndex]!.id}` : undefined}
        />
      </div>

      <div class="palette-tabs" role="tablist">
        {#each TABS as tab (tab)}
          <button
            class="palette-tab"
            class:active={activeTab === tab}
            role="tab"
            aria-selected={activeTab === tab}
            onclick={() => { activeTab = tab as typeof activeTab; focusedIndex = 0; }}
          >{tab}</button>
        {/each}
      </div>

      <div class="palette-results" id="palette-results" role="listbox" bind:this={resultsEl}>
        {#if flatItems.length === 0 && debouncedQuery.trim()}
          <div class="palette-empty">no results for "{debouncedQuery}"</div>
        {:else}
          {#each groupedResults as group (group.label)}
            <div class="palette-category" role="presentation">
              {group.label}
              {#if group.label === 'needs attention'}
                <span class="category-count">({group.items.length})</span>
              {/if}
            </div>
            {#each group.items as item (item.id)}
              {@const globalIndex = flatIndexMap.get(item.id) ?? -1}
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <div
                id="palette-item-{item.id}"
                class="palette-item"
                class:focused={globalIndex === focusedIndex}
                role="option"
                tabindex="-1"
                aria-selected={globalIndex === focusedIndex}
                onclick={() => selectItem(item)}
                onmouseenter={() => { focusedIndex = globalIndex; }}
              >
                <span class="item-cursor" class:visible={globalIndex === focusedIndex}>&gt;</span>
                {#if item.type === 'attention' || item.type === 'pr'}
                  <StatusDot status={derivePrDotStatus(item.data)} size={7} />
                {:else if item.type === 'command' && item.data.icon}
                  <span class="item-icon">{item.data.icon}</span>
                {:else}
                  <span class="item-icon">{categoryIcon(item.type)}</span>
                {/if}
                <span class="item-label">{item.label}</span>
                {#if item.sublabel}
                  <span class="item-sublabel">{item.sublabel}</span>
                {/if}
                {#if !isMobileDevice && item.type === 'command' && item.data.shortcut}
                  <kbd class="item-shortcut">{formatShortcut(item.data.shortcut.key, isMac)}</kbd>
                {/if}
              </div>
            {/each}
          {/each}
        {/if}
      </div>

      {#if !isMobileDevice}
        <div class="palette-footer">
          <span class="hint">↑↓ navigate</span>
          <span class="hint">tab category</span>
          <span class="hint">↵ select</span>
          <span class="hint">esc close</span>
        </div>
      {/if}
    </div>
  </div>
{/if}

<style>
  .palette-overlay {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    z-index: 1000;
    display: flex;
    align-items: flex-start;
    justify-content: center;
    padding-top: 20vh;
  }

  .palette {
    width: 100%;
    max-width: 580px;
    background: var(--surface);
    border: 1px solid var(--border);
    display: flex;
    flex-direction: column;
    max-height: 480px;
  }

  .palette-input-row {
    display: flex;
    align-items: center;
    padding: 12px 16px;
    gap: 8px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
    height: 44px;
  }

  .palette-prompt {
    font-family: var(--font-mono);
    font-size: var(--font-size-base);
    color: var(--accent);
    font-weight: bold;
    flex-shrink: 0;
    line-height: 1;
    user-select: none;
  }

  .palette-input-row :global(.tui-input-wrapper) { flex: 1; }
  .palette-input-row :global(.tui-input) { background: transparent; border: none; padding: 0; }
  .palette-input-row :global(.tui-input:focus) { border: none; }
  .palette-input-row :global(.tui-input::placeholder) { color: var(--text-muted); opacity: 0.6; }

  .palette-tabs {
    display: flex;
    gap: 0;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
    height: 32px;
  }

  .palette-tab {
    background: none;
    border: none;
    border-bottom: 2px solid transparent;
    padding: 6px 12px;
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    cursor: pointer;
    text-transform: lowercase;
  }

  .palette-tab:hover { color: var(--text); }
  .palette-tab.active { color: var(--accent); border-bottom-color: var(--accent); }

  .palette-results { overflow-y: auto; flex: 1; min-height: 0; }

  .palette-category {
    padding: 8px 16px 4px;
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    font-weight: 600;
    color: var(--text-muted);
    letter-spacing: 0.08em;
    user-select: none;
    text-transform: lowercase;
  }

  .category-count { font-weight: 400; opacity: 0.7; }

  .palette-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 16px;
    cursor: pointer;
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    color: var(--text-muted);
    transition: background 0.08s;
    min-height: 36px;
  }

  .palette-item:hover, .palette-item.focused { background: var(--surface-hover); color: var(--text); }

  .item-cursor {
    flex-shrink: 0;
    width: 12px;
    font-size: var(--font-size-xs);
    color: var(--accent);
    opacity: 0;
    transition: opacity 0.12s ease-out;
  }

  .item-cursor.visible { opacity: 1; }

  .item-icon {
    flex-shrink: 0;
    width: 16px;
    text-align: center;
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    opacity: 0.6;
  }

  .item-label { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0; }

  .item-sublabel {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    flex-shrink: 1;
    min-width: 0;
    max-width: 180px;
  }

  .item-shortcut {
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    border: 1px solid var(--border);
    padding: 1px 6px;
    flex-shrink: 0;
    border-radius: 0;
  }

  .palette-empty {
    padding: 20px 16px;
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    color: var(--text-muted);
    opacity: 0.6;
    text-align: center;
  }

  .palette-footer {
    display: flex;
    gap: 16px;
    padding: 8px 16px;
    border-top: 1px solid var(--border);
    flex-shrink: 0;
  }

  .hint {
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    opacity: 0.5;
  }

  /* Mobile bottom sheet */
  .palette-overlay.mobile { padding-top: 0; align-items: flex-end; background: rgba(0, 0, 0, 0.6); }

  .palette.mobile {
    max-width: 100%;
    max-height: 70vh;
    border: none;
    border-top: 1px solid var(--border);
    padding-bottom: env(safe-area-inset-bottom);
    border-radius: 0;
  }

  .drag-handle {
    display: flex;
    justify-content: center;
    padding: 8px 0 4px;
    cursor: grab;
    touch-action: none;
  }

  .drag-bar { width: 24px; height: 3px; background: var(--text-muted); border-radius: 0; }

  .palette.mobile .palette-item {
    min-height: 48px;
    padding: 14px 16px;
    border-bottom: 1px solid var(--surface-hover);
  }

  .palette.mobile .item-cursor { display: none; }
  .palette.mobile .item-shortcut { display: none; }
  .palette.mobile .palette-tabs { overflow-x: auto; -webkit-overflow-scrolling: touch; }
</style>
