// frontend/src/components/FileViewerPane.svelte
<script lang="ts">
  import { getUi, closeFileTab, closeAllFileTabs, refreshHtmlTab, fileTabKey, type OpenFileTab } from '../lib/state/ui.svelte.js';
  import { getSessionState } from '../lib/state/sessions.svelte.js';
  import { fetchFileDiff } from '../lib/api.js';
  import { diffSourceToBase } from '../lib/diff-utils.js';
  import { parseLineReference } from '../lib/file-tree-utils.js';
  // DiffSource is now read from shared UI state, not props
  import DiffViewer from './DiffViewer.svelte';
  import CodeBlock from './CodeBlock.svelte';

  let {
    workspacePath,
    onInjectReference,
  }: {
    workspacePath: string;
    onInjectReference?: (reference: string) => void;
  } = $props();

  const ui = getUi();
  const sessionState = getSessionState();

  // Read diffSource and view mode from shared UI state
  let diffSource = $derived(ui.fileDiffSource);
  let defaultBranch = $derived(ui.fileDiffDefaultBranch);
  let diffViewMode = $derived(ui.fileDiffViewMode);
  let wordWrap = $derived(ui.fileWordWrap);

  function toggleDiffViewMode(): void {
    ui.fileDiffViewMode = diffViewMode === 'unified' ? 'side-by-side' : 'unified';
  }

  function toggleWordWrap(): void {
    ui.fileWordWrap = !wordWrap;
  }

  // ── Diff/content cache ──
  let diffCache = $state<Map<string, string>>(new Map());
  let loadingPaths = $state<Set<string>>(new Set());
  let errorPaths = $state<Map<string, string>>(new Map());

  let base = $derived(diffSourceToBase(diffSource, defaultBranch));
  let activeTab = $derived<OpenFileTab | undefined>(
    ui.openFileTabs.find(t => fileTabKey(t.filePath, t.tabType) === ui.activeFileTabKey)
  );
  let activeDiff = $derived(activeTab ? diffCache.get(cacheKey(activeTab.filePath)) ?? '' : '');
  let activeLoading = $derived(activeTab ? loadingPaths.has(cacheKey(activeTab.filePath)) : false);
  let activeError = $derived(activeTab ? errorPaths.get(cacheKey(activeTab.filePath)) ?? null : null);

  // Active session info for send-to pill
  let activeSessionName = $derived.by(() => {
    const targetId = ui.sendToTargetSessionId ?? sessionState.activeSessionId;
    if (!targetId) return 'no sessions';
    const session = sessionState.sessions.find(s => s.id === targetId);
    return session?.displayName ?? session?.branchName ?? 'session';
  });

  let hasActiveSession = $derived(
    (ui.sendToTargetSessionId ?? sessionState.activeSessionId) !== null
  );

  // Cache key includes base to avoid stale diffs across diff source changes
  function cacheKey(filePath: string): string {
    return `${filePath}::${base ?? 'working'}`;
  }

  // Fetch diff when active tab or base changes
  $effect(() => {
    const tab = activeTab;
    if (!tab || !workspacePath) return;
    if (tab.tabType === 'html') return;
    const key = cacheKey(tab.filePath);
    if (diffCache.has(key)) return;
    if (loadingPaths.has(key)) return;

    const capturedBase = base;
    loadingPaths.add(key);
    loadingPaths = new Set(loadingPaths);

    fetchFileDiff(workspacePath, tab.filePath, capturedBase).then(
      (result) => {
        // Discard if base changed during fetch
        if (base !== capturedBase) return;
        if (result.error) {
          errorPaths.set(key, result.error);
          errorPaths = new Map(errorPaths);
        } else {
          diffCache.set(key, result.diff);
          diffCache = new Map(diffCache);
        }
      },
      (err) => {
        if (base !== capturedBase) return;
        errorPaths.set(key, err instanceof Error ? err.message : 'failed to load diff');
        errorPaths = new Map(errorPaths);
      },
    ).finally(() => {
      loadingPaths.delete(key);
      loadingPaths = new Set(loadingPaths);
    });
  });

  function handleCloseTab(tab: OpenFileTab, e: MouseEvent): void {
    e.stopPropagation();
    closeFileTab(tab.filePath, tab.tabType);
    const key = cacheKey(tab.filePath);
    diffCache.delete(key);
    errorPaths.delete(key);
    diffCache = new Map(diffCache);
    errorPaths = new Map(errorPaths);
  }

  function handleTabClick(tab: OpenFileTab): void {
    ui.activeFileTabKey = fileTabKey(tab.filePath, tab.tabType);
  }

  function handleDiffLineClick(filePath: string, lineNumber: number): void {
    if (!hasActiveSession) return;
    const reference = parseLineReference(filePath, lineNumber);
    onInjectReference?.(reference);
  }

  function handleRetry(): void {
    if (!activeTab) return;
    const key = cacheKey(activeTab.filePath);
    errorPaths.delete(key);
    diffCache.delete(key);
    errorPaths = new Map(errorPaths);
    diffCache = new Map(diffCache);
  }

  function languageFromPath(filePath: string): string {
    const ext = filePath.split('.').pop()?.toLowerCase() ?? '';
    const map: Record<string, string> = {
      ts: 'typescript', tsx: 'tsx', js: 'javascript', jsx: 'jsx',
      py: 'python', rs: 'rust', go: 'go', rb: 'ruby',
      java: 'java', c: 'c', cpp: 'cpp', h: 'c', hpp: 'cpp',
      css: 'css', scss: 'scss', html: 'html', svelte: 'svelte',
      json: 'json', yaml: 'yaml', yml: 'yaml', toml: 'toml',
      md: 'markdown', sh: 'bash', bash: 'bash', zsh: 'bash',
      sql: 'sql', graphql: 'graphql',
    };
    return map[ext] ?? 'text';
  }

  // ── HTML tab support ──
  const globeIcon = `<svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square"><circle cx="7" cy="7" r="5.5"/><path d="M1.5 7h11M7 1.5c-1.5 2-2 3.5-2 5.5s.5 3.5 2 5.5M7 1.5c1.5 2 2 3.5 2 5.5s-.5 3.5-2 5.5"/></svg>`;

  let sandboxDismissed = $state(false);
  let lastHtmlTabPath = $state('');

  // Auto-dismiss sandbox notice after 4 seconds
  $effect(() => {
    if (activeTab?.tabType === 'html' && !sandboxDismissed) {
      const timer = setTimeout(() => { sandboxDismissed = true; }, 4000);
      return () => clearTimeout(timer);
    }
  });

  // Reset dismissal when switching to a different HTML tab
  $effect(() => {
    if (activeTab?.tabType === 'html' && activeTab.filePath !== lastHtmlTabPath) {
      lastHtmlTabPath = activeTab.filePath;
      sandboxDismissed = false;
    }
  });

  function handleRefresh(): void {
    if (activeTab?.tabType === 'html' && activeTab.filePath) {
      refreshHtmlTab(activeTab.filePath);
    }
  }
</script>

<div class="file-viewer">
  <!-- File tab bar -->
  <div class="file-tab-bar">
    <div class="tabs-scroll">
      {#each ui.openFileTabs as tab (fileTabKey(tab.filePath, tab.tabType))}
        <div
          class="file-tab"
          class:active={ui.activeFileTabKey === fileTabKey(tab.filePath, tab.tabType)}
          role="tab"
          tabindex="0"
          aria-selected={ui.activeFileTabKey === fileTabKey(tab.filePath, tab.tabType)}
          onclick={() => handleTabClick(tab)}
          onkeydown={(e) => { if (e.key === 'Enter') handleTabClick(tab); }}
          title={tab.filePath}
        >
          {#if tab.tabType === 'html'}
            <span class="tab-icon">{@html globeIcon}</span>
          {/if}
          <span class="tab-name">{tab.fileName}</span>
          {#if tab.isChanged}
            <span class="tab-badge">M</span>
          {/if}
          <button
            class="tab-close"
            onclick={(e) => handleCloseTab(tab, e)}
            aria-label="close {tab.fileName}"
          >×</button>
        </div>
      {/each}
    </div>
    <div class="tab-bar-actions">
      <button class="diff-mode-btn" onclick={toggleWordWrap} title="Toggle word wrap">
        {wordWrap ? '[nowrap]' : '[wrap]'}
      </button>
      {#if activeTab?.isChanged}
        <button class="diff-mode-btn" onclick={toggleDiffViewMode} title="Toggle split/unified diff">
          {diffViewMode === 'unified' ? '[split]' : '[unified]'}
        </button>
      {/if}
      {#if activeTab?.tabType === 'html'}
        <button class="refresh-btn" onclick={handleRefresh} title="Reload HTML content">
          [refresh]
        </button>
      {/if}
      {#if ui.openFileTabs.length > 1}
        <button class="close-all-btn" onclick={closeAllFileTabs}>close all</button>
      {/if}
      <!-- Send-to pill -->
      <div class="send-to-pill" class:disabled={!hasActiveSession}>
        <span class="send-to-label">send to:</span>
        <span class="send-to-target">{activeSessionName}</span>
      </div>
    </div>
  </div>

  <!-- Content area -->
  <div class="file-content" role="tabpanel">
    {#if !activeTab}
      <div class="empty-viewer">select a file from the sidebar</div>
    {:else if activeLoading}
      <div class="loading-viewer">
        <span class="spinner">&#x280B;</span> loading {activeTab.fileName}...
      </div>
    {:else if activeError}
      <div class="error-viewer">
        <div class="error-text">failed to load diff: {activeError}</div>
        <div class="error-actions">
          <button class="retry-btn" onclick={handleRetry}>retry</button>
          <button class="close-btn" onclick={() => closeFileTab(activeTab!.filePath, activeTab!.tabType)}>close tab</button>
        </div>
      </div>
    {:else if activeTab.tabType === 'html' && activeTab.token}
      <div class="html-viewer">
        {#if !sandboxDismissed}
          <div class="sandbox-notice">
            <span class="notice-text">rendered in sandbox · some web features may not work</span>
            <button class="notice-dismiss" onclick={() => { sandboxDismissed = true; }} aria-label="dismiss notice">×</button>
          </div>
        {/if}
        <iframe
          src="/browser-content/{activeTab.token}/{activeTab.fileName}{activeTab.refreshVersion ? `?v=${activeTab.refreshVersion}` : ''}"
          sandbox="allow-scripts"
          title="HTML preview: {activeTab.fileName}"
          class="html-iframe"
        ></iframe>
      </div>
    {:else if activeTab.isChanged && activeDiff}
      <!-- Diff view with line-click handler -->
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div class="diff-wrapper" onclick={(e) => {
        // Diff-to-agent bridge: detect clicks on line numbers in the gutter
        const target = e.target as HTMLElement;
        const lineEl = target.closest('.line-number, .d2h-code-linenumber');
        if (!lineEl || !activeTab) return;
        const lineText = lineEl.textContent?.trim();
        const lineNum = lineText ? parseInt(lineText, 10) : NaN;
        if (!Number.isNaN(lineNum) && lineNum > 0) {
          handleDiffLineClick(activeTab.filePath, lineNum);
        }
      }}>
        <DiffViewer
          diff={activeDiff}
          filePath={activeTab.filePath}
          mode={diffViewMode}
          {wordWrap}
        />
      </div>
    {:else if !activeTab.isChanged}
      <!-- Raw file view -->
      <div class="raw-file" class:word-wrap={wordWrap}>
        <CodeBlock code={activeDiff || '(empty file)'} language={languageFromPath(activeTab.filePath)} />
      </div>
    {:else}
      <div class="empty-viewer">no diff available</div>
    {/if}
  </div>
</div>

<style>
  .file-viewer {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--bg, #000);
    overflow: hidden;
  }

  /* File tab bar */
  .file-tab-bar {
    display: flex;
    align-items: center;
    border-bottom: 1px solid var(--border, #333);
    min-height: 32px;
    flex-shrink: 0;
  }

  .tabs-scroll {
    display: flex;
    overflow-x: auto;
    flex: 1;
    min-width: 0;
  }

  .tabs-scroll::-webkit-scrollbar {
    height: 2px;
  }

  .tabs-scroll::-webkit-scrollbar-thumb {
    background: var(--border, #333);
  }

  .file-tab {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 6px 8px;
    background: none;
    border: none;
    border-bottom: 1px solid transparent;
    border-right: 1px solid var(--border, #333);
    margin-bottom: -1px;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
    cursor: pointer;
    white-space: nowrap;
    flex-shrink: 0;
  }

  .file-tab:hover {
    color: var(--text, #e0e0e0);
    background: var(--surface-hover, #141414);
  }

  .file-tab.active {
    color: var(--text, #e0e0e0);
    border-bottom-color: var(--accent, #d97757);
  }

  .tab-name {
    max-width: 120px;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .tab-badge {
    font-size: 0.625rem;
    color: var(--status-warning, #fbbf24);
  }

  .tab-close {
    background: none;
    border: none;
    color: var(--text-muted, #888);
    font-size: var(--font-size-sm, 0.8125rem);
    cursor: pointer;
    padding: 0 2px;
    line-height: 1;
  }

  .tab-close:hover {
    color: var(--text, #e0e0e0);
  }

  .tab-bar-actions {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 0 8px;
    flex-shrink: 0;
  }

  .diff-mode-btn {
    background: none;
    border: 1px solid var(--border, #333);
    color: var(--text-muted, #888);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    cursor: pointer;
    white-space: nowrap;
    padding: 1px 6px;
  }

  .diff-mode-btn:hover {
    color: var(--text, #e0e0e0);
    border-color: var(--text-muted, #888);
  }

  .close-all-btn {
    background: none;
    border: none;
    color: var(--text-muted, #888);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    cursor: pointer;
    white-space: nowrap;
  }

  .close-all-btn:hover {
    color: var(--text, #e0e0e0);
  }

  /* Send-to pill */
  .send-to-pill {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 2px 8px;
    border: 1px solid var(--border, #333);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    white-space: nowrap;
  }

  .send-to-pill.disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .send-to-label {
    color: var(--text-muted, #888);
  }

  .send-to-target {
    color: var(--text, #e0e0e0);
  }

  /* Content */
  .file-content {
    flex: 1;
    overflow: auto;
    min-height: 0;
  }

  .diff-wrapper {
    position: relative;
    height: 100%;
    overflow: auto;
  }

  /* Override DiffViewer standalone styles when embedded in file viewer */
  .diff-wrapper :global(.diff-viewer) {
    max-height: none;
    border: none;
  }

  /* Diff-to-agent bridge: make line numbers clickable with + indicator */
  .diff-wrapper :global(.line-number),
  .diff-wrapper :global(.d2h-code-linenumber) {
    position: relative;
    cursor: pointer;
  }

  .diff-wrapper :global(.line-number)::before,
  .diff-wrapper :global(.d2h-code-linenumber)::before {
    content: '+';
    position: absolute;
    left: 0;
    top: 50%;
    transform: translateY(-50%);
    color: var(--text-muted, #888);
    font-size: 10px;
    opacity: 0;
    transition: opacity 100ms;
    pointer-events: none;
  }

  .diff-wrapper :global(.line-number):hover::before,
  .diff-wrapper :global(.d2h-code-linenumber):hover::before {
    opacity: 1;
    color: var(--accent, #d97757);
  }

  .diff-wrapper :global(.line-number):hover,
  .diff-wrapper :global(.d2h-code-linenumber):hover {
    background: color-mix(in srgb, var(--accent) 8%, transparent);
  }

  .raw-file {
    padding: 8px;
  }

  .raw-file.word-wrap :global(pre) {
    white-space: pre-wrap;
    word-break: break-all;
  }

  .empty-viewer, .loading-viewer, .error-viewer {
    padding: 24px 16px;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-sm, 0.8125rem);
    color: var(--text-muted, #888);
  }

  .error-viewer {
    color: var(--status-error, #f87171);
  }

  .error-text {
    font-size: var(--font-size-xs, 0.75rem);
    margin-bottom: 8px;
  }

  .error-actions {
    display: flex;
    gap: 8px;
  }

  .retry-btn, .close-btn {
    padding: 2px 8px;
    background: none;
    border: 1px solid var(--border, #333);
    color: var(--text-muted, #888);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    cursor: pointer;
  }

  .retry-btn:hover, .close-btn:hover {
    color: var(--text, #e0e0e0);
    border-color: var(--text-muted, #888);
  }

  .spinner {
    display: inline-block;
    animation: braille-spin 0.8s steps(8) infinite;
  }

  @keyframes braille-spin {
    to { content: '⠏'; }
  }

  /* HTML tab support */
  .tab-icon {
    display: inline-flex;
    align-items: center;
    color: var(--text-muted, #888);
    margin-right: 4px;
  }

  .file-tab.active .tab-icon {
    color: var(--text, #e0e0e0);
  }

  .refresh-btn {
    background: none;
    border: 1px solid var(--border, #333);
    color: var(--text-muted, #888);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    cursor: pointer;
    white-space: nowrap;
    padding: 1px 6px;
  }

  .refresh-btn:hover {
    color: var(--text, #e0e0e0);
    border-color: var(--text-muted, #888);
  }

  .html-viewer {
    display: flex;
    flex-direction: column;
    flex: 1;
    overflow: hidden;
  }

  .sandbox-notice {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 4px 12px;
    border-bottom: 1px solid var(--border, #333);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
    transition: opacity 0.3s ease-out;
  }

  .notice-text {
    font-family: inherit;
  }

  .notice-dismiss {
    background: none;
    border: none;
    color: var(--text-muted, #888);
    cursor: pointer;
    font-family: inherit;
    font-size: var(--font-size-sm, 0.8125rem);
    padding: 0 4px;
    min-width: 44px;
    min-height: 44px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .notice-dismiss:hover {
    color: var(--text, #e0e0e0);
  }

  .html-iframe {
    flex: 1;
    width: 100%;
    border: none;
    background: white;
  }
</style>

// frontend/src/components/FileViewerPane.tsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useUiStore, fileTabKey } from '../lib/stores/ui.js';
import type { OpenFileTab } from '../lib/stores/ui.js';
import { useSessionsStore } from '../lib/stores/sessions.js';
import { fetchFileDiff } from '../lib/api.js';
import { diffSourceToBase } from '../lib/diff-utils.js';
import { parseLineReference } from '../lib/file-tree-utils.js';
import DiffViewer from './DiffViewer.js';
import CodeBlock from './CodeBlock.js';
import './FileViewerPane.css';

// ── Types ────────────────────────────────────────────────────────────────────

export interface FileViewerPaneProps {
  workspacePath: string;
  onInjectReference?: (reference: string) => void;
  renderDiff?: (props: {
    diff: string;
    filePath: string;
    mode: 'unified' | 'side-by-side';
    wordWrap: boolean;
  }) => React.ReactNode;
  renderCode?: (props: { code: string; language: string }) => React.ReactNode;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const GLOBE_SVG = (
  <svg width="14" height="14" viewBox="0 0 14 14" fill="none"
    stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" aria-hidden="true">
    <circle cx="7" cy="7" r="5.5" />
    <path d="M1.5 7h11M7 1.5c-1.5 2-2 3.5-2 5.5s.5 3.5 2 5.5M7 1.5c1.5 2 2 3.5 2 5.5s-.5 3.5-2 5.5" />
  </svg>
);

function languageFromPath(filePath: string): string {
  const ext = filePath.split('.').pop()?.toLowerCase() ?? '';
  const map: Record<string, string> = {
    ts: 'typescript', tsx: 'tsx', js: 'javascript', jsx: 'jsx',
    py: 'python', rs: 'rust', go: 'go', rb: 'ruby',
    css: 'css', scss: 'scss', html: 'html', svelte: 'svelte',
    json: 'json', yaml: 'yaml', yml: 'yaml', md: 'markdown',
    sh: 'bash', bash: 'bash', sql: 'sql', graphql: 'graphql',
  };
  return map[ext] ?? 'text';
}

function buildCacheKey(filePath: string, base: string | null): string {
  return `${filePath}::${base ?? 'working'}`;
}

// ── useDiffCache hook ─────────────────────────────────────────────────────────

function useDiffCache(workspacePath: string) {
  const [diffCache, setDiffCache] = useState<Map<string, string>>(new Map());
  const [loadingPaths, setLoadingPaths] = useState<Set<string>>(new Set());
  const [errorPaths, setErrorPaths] = useState<Map<string, string>>(new Map());

  const fetchDiff = useCallback((filePath: string, base: string | null) => {
    const key = buildCacheKey(filePath, base);
    if (diffCache.has(key) || loadingPaths.has(key)) return;
    setLoadingPaths((prev) => new Set([...prev, key]));
    fetchFileDiff(workspacePath, filePath, base ?? undefined).then(
      (result) => {
        if (result.error) {
          setErrorPaths((prev) => new Map([...prev, [key, result.error as string]]));
        } else {
          setDiffCache((prev) => new Map([...prev, [key, result.diff]]));
        }
      },
      (err: unknown) => {
        const msg = err instanceof Error ? err.message : 'failed to load diff';
        setErrorPaths((prev) => new Map([...prev, [key, msg]]));
      }
    ).finally(() => {
      setLoadingPaths((prev) => { const next = new Set(prev); next.delete(key); return next; });
    });
  }, [workspacePath, diffCache, loadingPaths]);

  const clearEntry = useCallback((key: string) => {
    setDiffCache((prev) => { const m = new Map(prev); m.delete(key); return m; });
    setErrorPaths((prev) => { const m = new Map(prev); m.delete(key); return m; });
  }, []);

  return { diffCache, loadingPaths, errorPaths, fetchDiff, clearEntry };
}

// ── useActiveSession hook ─────────────────────────────────────────────────────

function useActiveSession() {
  const sessions = useSessionsStore((s) => s.sessions);
  const activeSessionId = useSessionsStore((s) => s.activeSessionId);
  const sendToTargetSessionId = useUiStore((s) => s.sendToTargetSessionId);
  const targetId = sendToTargetSessionId ?? activeSessionId;
  const activeSessionName = useMemo(() => {
    if (!targetId) return 'no sessions';
    const session = sessions.find((s) => s.id === targetId);
    return session?.displayName ?? session?.branchName ?? 'session';
  }, [targetId, sessions]);
  return { hasActiveSession: targetId !== null, activeSessionName };
}

// ── Sub-components ────────────────────────────────────────────────────────────

interface TabItemProps {
  tab: OpenFileTab;
  isActive: boolean;
  onTabClick: (tab: OpenFileTab) => void;
  onCloseTab: (tab: OpenFileTab, e: React.MouseEvent) => void;
}

function TabItem({ tab, isActive, onTabClick, onCloseTab }: TabItemProps) {
  return (
    <div
      className={['file-tab', isActive ? 'active' : ''].filter(Boolean).join(' ')}
      role="tab" tabIndex={0} aria-selected={isActive}
      onClick={() => onTabClick(tab)}
      onKeyDown={(e) => { if (e.key === 'Enter') onTabClick(tab); }}
      title={tab.filePath}
    >
      {tab.tabType === 'html' && <span className="tab-icon">{GLOBE_SVG}</span>}
      <span className="tab-name">{tab.fileName}</span>
      {tab.isChanged && <span className="tab-badge">M</span>}
      <button className="tab-close" onClick={(e) => onCloseTab(tab, e)} aria-label={`close ${tab.fileName}`}>×</button>
    </div>
  );
}

interface HtmlTabViewProps { tab: OpenFileTab; }

function HtmlTabView({ tab }: HtmlTabViewProps) {
  const [sandboxDismissed, setSandboxDismissed] = useState(false);
  const [lastPath, setLastPath] = useState('');
  useEffect(() => {
    if (tab.filePath !== lastPath) { setLastPath(tab.filePath); setSandboxDismissed(false); }
  }, [tab.filePath, lastPath]);
  useEffect(() => {
    if (!sandboxDismissed) {
      const timer = setTimeout(() => setSandboxDismissed(true), 4000);
      return () => clearTimeout(timer);
    }
    return undefined;
  }, [sandboxDismissed]);
  const src = `/browser-content/${tab.token}/${tab.fileName}${tab.refreshVersion ? `?v=${tab.refreshVersion}` : ''}`;
  return (
    <div className="html-viewer">
      {!sandboxDismissed && (
        <div className="sandbox-notice">
          <span className="notice-text">rendered in sandbox · some web features may not work</span>
          <button className="notice-dismiss" onClick={() => setSandboxDismissed(true)} aria-label="dismiss notice">×</button>
        </div>
      )}
      <iframe src={src} sandbox="allow-scripts" title={`HTML preview: ${tab.fileName}`} className="html-iframe" />
    </div>
  );
}

interface ContentAreaProps {
  activeTab: OpenFileTab | undefined;
  activeLoading: boolean;
  activeError: string | null;
  activeDiff: string;
  diffViewMode: 'unified' | 'side-by-side';
  wordWrap: boolean;
  onRetry: () => void;
  onCloseActiveTab: () => void;
  onDiffClick: (e: React.MouseEvent) => void;
  renderDiff?: FileViewerPaneProps['renderDiff'];
  renderCode?: FileViewerPaneProps['renderCode'];
}

function ContentArea({
  activeTab, activeLoading, activeError, activeDiff, diffViewMode, wordWrap,
  onRetry, onCloseActiveTab, onDiffClick, renderDiff, renderCode,
}: ContentAreaProps) {
  if (!activeTab) return <div className="empty-viewer">select a file from the sidebar</div>;
  if (activeLoading) return <div className="loading-viewer"><span className="spinner">&#x280B;</span> loading {activeTab.fileName}...</div>;
  if (activeError) {
    return (
      <div className="error-viewer">
        <div className="error-text">failed to load diff: {activeError}</div>
        <div className="error-actions">
          <button className="retry-btn" onClick={onRetry}>retry</button>
          <button className="close-btn" onClick={onCloseActiveTab}>close tab</button>
        </div>
      </div>
    );
  }
  if (activeTab.tabType === 'html' && activeTab.token) return <HtmlTabView tab={activeTab} />;
  if (activeTab.isChanged && activeDiff) {
    return (
      <div className="diff-wrapper" onClick={onDiffClick}>
        {renderDiff ? renderDiff({ diff: activeDiff, filePath: activeTab.filePath, mode: diffViewMode, wordWrap })
          : <DiffViewer diff={activeDiff} filePath={activeTab.filePath} mode={diffViewMode} wordWrap={wordWrap} />}
      </div>
    );
  }
  if (!activeTab.isChanged) {
    return (
      <div className={['raw-file', wordWrap ? 'word-wrap' : ''].filter(Boolean).join(' ')}>
        {renderCode ? renderCode({ code: activeDiff || '(empty file)', language: languageFromPath(activeTab.filePath) })
          : <CodeBlock code={activeDiff || '(empty file)'} language={languageFromPath(activeTab.filePath)} />}
      </div>
    );
  }
  return <div className="empty-viewer">no diff available</div>;
}

// ── useFileViewerHandlers hook ────────────────────────────────────────────────

function useFileViewerHandlers(
  activeTab: OpenFileTab | undefined,
  base: string | null,
  hasActiveSession: boolean,
  onInjectReference: ((r: string) => void) | undefined,
  clearEntry: (key: string) => void,
) {
  const closeFileTab = useUiStore((s) => s.closeFileTab);
  const closeAllFileTabs = useUiStore((s) => s.closeAllFileTabs);
  const refreshHtmlTab = useUiStore((s) => s.refreshHtmlTab);
  const setFileDiffViewMode = useUiStore((s) => s.setFileDiffViewMode);
  const setFileWordWrap = useUiStore((s) => s.setFileWordWrap);
  const fileDiffViewMode = useUiStore((s) => s.fileDiffViewMode);
  const fileWordWrap = useUiStore((s) => s.fileWordWrap);

  const handleCloseTab = useCallback((tab: OpenFileTab, e: React.MouseEvent) => {
    e.stopPropagation();
    closeFileTab(tab.filePath, tab.tabType);
    clearEntry(buildCacheKey(tab.filePath, base));
  }, [closeFileTab, clearEntry, base]);

  const handleTabClick = useCallback((tab: OpenFileTab) => {
    useUiStore.setState({ activeFileTabKey: fileTabKey(tab.filePath, tab.tabType) });
  }, []);

  const handleDiffClick = useCallback((e: React.MouseEvent) => {
    const target = e.target as HTMLElement;
    const lineEl = target.closest('.line-number, .d2h-code-linenumber');
    if (!lineEl || !activeTab || !hasActiveSession) return;
    const lineNum = parseInt(lineEl.textContent?.trim() ?? '', 10);
    if (!Number.isNaN(lineNum) && lineNum > 0) {
      onInjectReference?.(parseLineReference(activeTab.filePath, lineNum));
    }
  }, [activeTab, hasActiveSession, onInjectReference]);

  const handleRetry = useCallback(() => {
    if (activeTab) clearEntry(buildCacheKey(activeTab.filePath, base));
  }, [activeTab, base, clearEntry]);

  const handleRefresh = useCallback(() => {
    if (activeTab?.tabType === 'html' && activeTab.filePath) refreshHtmlTab(activeTab.filePath);
  }, [activeTab, refreshHtmlTab]);

  const handleCloseActiveTab = useCallback(() => {
    if (activeTab) closeFileTab(activeTab.filePath, activeTab.tabType);
  }, [activeTab, closeFileTab]);

  const handleToggleDiffViewMode = useCallback(() => {
    setFileDiffViewMode(fileDiffViewMode === 'unified' ? 'side-by-side' : 'unified');
  }, [fileDiffViewMode, setFileDiffViewMode]);

  const handleToggleWordWrap = useCallback(() => {
    setFileWordWrap(!fileWordWrap);
  }, [fileWordWrap, setFileWordWrap]);

  return {
    handleCloseTab, handleTabClick, handleDiffClick, handleRetry, handleRefresh,
    handleCloseActiveTab, handleToggleDiffViewMode, handleToggleWordWrap, closeAllFileTabs,
    fileDiffViewMode, fileWordWrap,
  };
}

// ── Main Component ────────────────────────────────────────────────────────────

export function FileViewerPane({ workspacePath, onInjectReference, renderDiff, renderCode }: FileViewerPaneProps) {
  const openFileTabs = useUiStore((s) => s.openFileTabs);
  const activeFileTabKey = useUiStore((s) => s.activeFileTabKey);
  const fileDiffSource = useUiStore((s) => s.fileDiffSource);
  const fileDiffDefaultBranch = useUiStore((s) => s.fileDiffDefaultBranch);
  const base = useMemo(() => diffSourceToBase(fileDiffSource, fileDiffDefaultBranch) ?? null, [fileDiffSource, fileDiffDefaultBranch]);
  const activeTab = useMemo(
    () => openFileTabs.find((t) => fileTabKey(t.filePath, t.tabType) === activeFileTabKey),
    [openFileTabs, activeFileTabKey]
  );
  const { diffCache, loadingPaths, errorPaths, fetchDiff, clearEntry } = useDiffCache(workspacePath);
  const { hasActiveSession, activeSessionName } = useActiveSession();
  const handlers = useFileViewerHandlers(activeTab, base, hasActiveSession, onInjectReference, clearEntry);
  const { handleCloseTab, handleTabClick, handleDiffClick, handleRetry, handleRefresh,
    handleCloseActiveTab, handleToggleDiffViewMode, handleToggleWordWrap, closeAllFileTabs,
    fileDiffViewMode, fileWordWrap } = handlers;

  const activeCacheKey = activeTab ? buildCacheKey(activeTab.filePath, base) : null;
  const activeDiff = activeCacheKey ? diffCache.get(activeCacheKey) ?? '' : '';
  const activeLoading = activeCacheKey ? loadingPaths.has(activeCacheKey) : false;
  const activeError = activeCacheKey ? errorPaths.get(activeCacheKey) ?? null : null;

  useEffect(() => {
    if (!activeTab || activeTab.tabType === 'html') return;
    fetchDiff(activeTab.filePath, base);
  }, [activeTab?.filePath, activeTab?.tabType, base, fetchDiff]);

  return (
    <div className="file-viewer">
      <div className="file-tab-bar">
        <div className="tabs-scroll">
          {openFileTabs.map((tab) => (
            <TabItem
              key={fileTabKey(tab.filePath, tab.tabType)}
              tab={tab} isActive={activeFileTabKey === fileTabKey(tab.filePath, tab.tabType)}
              onTabClick={handleTabClick} onCloseTab={handleCloseTab}
            />
          ))}
        </div>
        <div className="tab-bar-actions">
          <button className="diff-mode-btn" onClick={handleToggleWordWrap}>{fileWordWrap ? '[nowrap]' : '[wrap]'}</button>
          {activeTab?.isChanged && (
            <button className="diff-mode-btn" onClick={handleToggleDiffViewMode}>
              {fileDiffViewMode === 'unified' ? '[split]' : '[unified]'}
            </button>
          )}
          {activeTab?.tabType === 'html' && (
            <button className="refresh-btn" onClick={handleRefresh}>[refresh]</button>
          )}
          {openFileTabs.length > 1 && <button className="close-all-btn" onClick={closeAllFileTabs}>close all</button>}
          <div className={['send-to-pill', !hasActiveSession ? 'disabled' : ''].filter(Boolean).join(' ')}>
            <span className="send-to-label">send to:</span>
            <span className="send-to-target">{activeSessionName}</span>
          </div>
        </div>
      </div>
      <div className="file-content" role="tabpanel">
        <ContentArea
          activeTab={activeTab} activeLoading={activeLoading} activeError={activeError}
          activeDiff={activeDiff} diffViewMode={fileDiffViewMode} wordWrap={fileWordWrap}
          onRetry={handleRetry} onCloseActiveTab={handleCloseActiveTab} onDiffClick={handleDiffClick}
          renderDiff={renderDiff} renderCode={renderCode}
        />
      </div>
    </div>
  );
}

export default FileViewerPane;
