// frontend/src/components/FileTreeSidebar.tsx
import React, { useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState, forwardRef } from 'react';
import type { FileTreeNode } from '../lib/file-tree-utils.js';
import { buildChangedFilesTree, flattenVisibleNodes, statusToBadge, statusToBadgeColor } from '../lib/file-tree-utils.js';
import { diffSourceToBase } from '../lib/diff-utils.js';
import { fetchChangedFiles, fetchDefaultBranch, browseFsDirectory, type BrowseEntry } from '../lib/api.js';
import { useUiStore, type RightSidebarTab } from '../lib/stores/ui.js';
import type { ChangedFile } from '../lib/types.js';
import DiffSourceToggle from './DiffSourceToggle.js';
import './FileTreeSidebar.css';

export type { ChangedFile } from '../lib/types.js';

export interface FileTreeSidebarHandle {
  refresh: () => Promise<void>;
}

export interface FileTreeSidebarProps {
  workspacePath: string;
  changedFilesData?: string[];
  onFileSelect?: (filePath: string, isChanged: boolean) => void;
}

export const FileTreeSidebar = forwardRef<FileTreeSidebarHandle, FileTreeSidebarProps>(
  function FileTreeSidebar({ workspacePath, changedFilesData = [], onFileSelect }, ref) {
    const rightSidebarTab = useUiStore((s) => s.rightSidebarTab);
    const setRightSidebarTab = useUiStore((s) => s.setRightSidebarTab);
    const fileDiffSource = useUiStore((s) => s.fileDiffSource);
    const fileDiffDefaultBranch = useUiStore((s) => s.fileDiffDefaultBranch);
    const openFileTab = useUiStore((s) => s.openFileTab);
    // ── Changes tab state ──
    const [changedFiles, setChangedFiles] = useState<ChangedFile[]>([]);
    const [aggregate, setAggregate] = useState({ additions: 0, deletions: 0, fileCount: 0 });
    const [changesLoading, setChangesLoading] = useState(false);
    const [changesError, setChangesError] = useState<string | null>(null);
    const [treeNodes, setTreeNodes] = useState<FileTreeNode[]>([]);

    // ── All files tab state ──
    const [allFilesTree, setAllFilesTree] = useState<BrowseEntry[]>([]);
    const [allFilesExpanded, setAllFilesExpanded] = useState<Set<string>>(new Set());
    const [allFilesChildren, setAllFilesChildren] = useState<Map<string, BrowseEntry[]>>(new Map());
    const [allFilesLoading, setAllFilesLoading] = useState(false);
    const [allFilesError, setAllFilesError] = useState<string | null>(null);

    // ── Cipher-decode animation state ──
    const [animatingPaths, setAnimatingPaths] = useState<Set<string>>(new Set());

    // ── Keyboard nav ──
    const [focusedIndex, setFocusedIndex] = useState(-1);

    const base = useMemo(() => diffSourceToBase(fileDiffSource, fileDiffDefaultBranch), [fileDiffSource, fileDiffDefaultBranch]);
    const visibleNodes = useMemo(() => flattenVisibleNodes(treeNodes), [treeNodes]);

    const changedFilesRef = useRef(changedFiles);
    changedFilesRef.current = changedFiles;

    // ── Fetch changed files ──
    const refresh = useCallback(async () => {
      if (!workspacePath) return;
      setChangesLoading(true);
      setChangesError(null);
      try {
        const data = await fetchChangedFiles(workspacePath, base);
        if (data.error) {
          setChangesError(data.error);
        } else {
          setChangedFiles(data.files);
          setAggregate(data.aggregate);
          setTreeNodes(buildChangedFilesTree(data.files));
        }
      } catch (err) {
        setChangesError(err instanceof Error ? err.message : 'failed to load');
      } finally {
        setChangesLoading(false);
      }
    }, [workspacePath, base]);

    useImperativeHandle(ref, () => ({ refresh }), [refresh]);

    // Fetch default branch then refresh
    const lastWorkspacePathRef = useRef('');
    useEffect(() => {
      if (!workspacePath) return;
      const needsBranchFetch = workspacePath !== lastWorkspacePathRef.current;
      lastWorkspacePathRef.current = workspacePath;

      if (needsBranchFetch) {
        fetchDefaultBranch(workspacePath).then((b) => {
          useUiStore.getState().setFileDiffDefaultBranch(b);
          refresh();
        });
      } else {
        refresh();
      }
    }, [workspacePath, base, refresh]);

    // Handle real-time file change events — mark new files for animation
    useEffect(() => {
      if (changedFilesData.length > 0) {
        const prevSet = new Set(useUiStore.getState().lastChangedFiles);
        const justChanged = changedFilesData.filter((f) => !prevSet.has(f));
        if (justChanged.length > 0) {
          setAnimatingPaths((prev) => new Set([...prev, ...justChanged]));
          setTimeout(() => {
            setAnimatingPaths((prev) => new Set([...prev].filter((p) => !justChanged.includes(p))));
          }, 500);
        }
        useUiStore.getState().setLastChangedFiles([...changedFilesData]);
      }
    }, [changedFilesData]);

    // ── All files tab ──
    const loadAllFiles = useCallback(async () => {
      if (!workspacePath) return;
      setAllFilesLoading(true);
      setAllFilesError(null);
      try {
        const data = await browseFsDirectory(workspacePath, { includeFiles: true, showHidden: false });
        setAllFilesTree(data.entries);
      } catch (err) {
        setAllFilesError(err instanceof Error ? err.message : 'failed to load');
      } finally {
        setAllFilesLoading(false);
      }
    }, [workspacePath]);

    const toggleAllFilesDir = useCallback(async (entryPath: string) => {
      if (allFilesExpanded.has(entryPath)) {
        setAllFilesExpanded((prev) => {
          const next = new Set(prev);
          next.delete(entryPath);
          return next;
        });
      } else {
        setAllFilesExpanded((prev) => new Set([...prev, entryPath]));
        if (!allFilesChildren.has(entryPath)) {
          try {
            const data = await browseFsDirectory(entryPath, { includeFiles: true, showHidden: false });
            setAllFilesChildren((prev) => new Map([...prev, [entryPath, data.entries]]));
          } catch {
            // best effort
          }
        }
      }
    }, [allFilesExpanded, allFilesChildren]);

    // Load all files on tab switch
    useEffect(() => {
      if (rightSidebarTab === 'all-files' && allFilesTree.length === 0 && !allFilesLoading) {
        loadAllFiles();
      }
    }, [rightSidebarTab, allFilesTree.length, allFilesLoading, loadAllFiles]);

    // ── Tree interactions ──
    const handleFileClick = useCallback((node: FileTreeNode) => {
      if (node.isDirectory) {
        setTreeNodes((prev) => {
          function toggleExpanded(nodes: FileTreeNode[]): FileTreeNode[] {
            return nodes.map((n) => {
              if (n.path === node.path) return { ...n, expanded: !n.expanded, children: toggleExpanded(n.children) };
              return { ...n, children: toggleExpanded(n.children) };
            });
          }
          return toggleExpanded(prev);
        });
      } else {
        const isChanged = changedFilesRef.current.some((f) => f.path === node.path);
        openFileTab(node.path, isChanged);
        onFileSelect?.(node.path, isChanged);
      }
    }, [openFileTab, onFileSelect]);

    const handleAllFilesClick = useCallback((entry: BrowseEntry) => {
      if (entry.isDirectory !== false) {
        toggleAllFilesDir(entry.path);
      } else {
        const prefix = workspacePath + '/';
        const relativePath = entry.path.startsWith(prefix) ? entry.path.slice(prefix.length) : entry.path;
        const isChanged = changedFilesRef.current.some((f) => f.path === relativePath);
        openFileTab(relativePath, isChanged);
        onFileSelect?.(relativePath, isChanged);
      }
    }, [workspacePath, toggleAllFilesDir, openFileTab, onFileSelect]);

    const handleKeydown = useCallback((e: React.KeyboardEvent) => {
      const nodes = visibleNodes;
      if (nodes.length === 0) return;

      if (e.key === 'ArrowDown') {
        e.preventDefault();
        setFocusedIndex((prev) => Math.min(prev + 1, nodes.length - 1));
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        setFocusedIndex((prev) => Math.max(prev - 1, 0));
      } else if (e.key === 'Enter' && focusedIndex >= 0 && focusedIndex < nodes.length) {
        e.preventDefault();
        handleFileClick(nodes[focusedIndex]!.node);
      }
    }, [visibleNodes, focusedIndex, handleFileClick]);

    function isRecentlyChanged(filePath: string): boolean {
      return changedFilesData.length > 0 && changedFilesData.includes(filePath);
    }

    // ── All files recursive renderer ──
    function renderAllFilesNode(entries: BrowseEntry[], depth: number): React.ReactNode {
      return entries.map((entry) => (
        <React.Fragment key={entry.path}>
          <button
            className={`tree-item ${entry.isDirectory !== false ? 'directory' : 'file'}`}
            role="treeitem"
            aria-expanded={entry.isDirectory !== false ? allFilesExpanded.has(entry.path) : undefined}
            aria-selected={false}
            style={{ paddingLeft: `${8 + depth * 16}px` }}
            onClick={() => handleAllFilesClick(entry)}
          >
            <span className="icon-slot">
              {entry.isDirectory !== false ? (
                <span className="expand-arrow">{allFilesExpanded.has(entry.path) ? 'v' : '>'}</span>
              ) : (
                <span className="file-icon">-</span>
              )}
            </span>
            <span className="node-name">{entry.name}</span>
            {entry.isDirectory !== false && entry.hasChildren && (
              <span className="action-slot">
                <span className="has-children-dot" />
              </span>
            )}
          </button>
          {allFilesExpanded.has(entry.path) && allFilesChildren.has(entry.path) && (
            renderAllFilesNode(allFilesChildren.get(entry.path) ?? [], depth + 1)
          )}
        </React.Fragment>
      ));
    }

    return (
      <div className="fts-sidebar" role="complementary" aria-label="file tree">
        {/* Tab bar */}
        <div className="fts-tab-bar" role="tablist">
          {([
            { id: 'changes' as RightSidebarTab, label: 'changes' },
            { id: 'all-files' as RightSidebarTab, label: 'all files' },
            { id: 'checks' as RightSidebarTab, label: 'checks' },
          ]).map((tab) => (
            <button
              key={tab.id}
              className={`fts-tab${rightSidebarTab === tab.id ? ' active' : ''}`}
              role="tab"
              aria-selected={rightSidebarTab === tab.id}
              onClick={() => setRightSidebarTab(tab.id)}
            >
              {tab.label}
              {tab.id === 'changes' && aggregate.fileCount > 0 && (
                <span className="fts-tab-count">{aggregate.fileCount}</span>
              )}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="fts-tab-content">
          {rightSidebarTab === 'changes' && (
            <>
              <div className="fts-controls-row">
                <DiffSourceToggle
                  value={fileDiffSource}
                  onchange={(s) => useUiStore.getState().setFileDiffSource(s)}
                  defaultBranch={fileDiffDefaultBranch}
                />
              </div>

              {changesLoading && changedFiles.length === 0 ? (
                <div className="fts-loading-state">
                  <span className="fts-spinner">&#x280B;</span> loading changes...
                </div>
              ) : changesError ? (
                <div className="fts-error-state">
                  <span className="fts-error-text">{changesError}</span>
                  <button className="fts-retry-btn" onClick={() => refresh()}>retry</button>
                </div>
              ) : visibleNodes.length === 0 ? (
                <div className="fts-empty-state">
                  no changes yet — when an agent writes code, changed files appear here. click any line to send it as context.
                </div>
              ) : (
                <div className="fts-tree" role="tree" tabIndex={0} onKeyDown={handleKeydown}>
                  {visibleNodes.map(({ node, depth }, i) => (
                    <button
                      key={node.path}
                      className={[
                        'tree-item',
                        focusedIndex === i && 'focused',
                        animatingPaths.has(node.path) && 'animating',
                        node.isDirectory ? 'directory' : 'file',
                      ].filter(Boolean).join(' ')}
                      role="treeitem"
                      aria-selected={focusedIndex === i}
                      aria-expanded={node.isDirectory ? node.expanded : undefined}
                      aria-label={`${node.name}${node.status ? `, ${node.status}` : ''}${node.additions ? `, ${node.additions} additions` : ''}${node.deletions ? `, ${node.deletions} deletions` : ''}${isRecentlyChanged(node.path) ? ', recently changed' : ''}`}
                      style={{ paddingLeft: `${8 + depth * 16}px` }}
                      onClick={() => handleFileClick(node)}
                    >
                      <span className="icon-slot">
                        {isRecentlyChanged(node.path) && !node.isDirectory ? (
                          <span className="blue-dot" aria-label="recently changed" />
                        ) : node.isDirectory ? (
                          <span className="expand-arrow">{node.expanded ? 'v' : '>'}</span>
                        ) : (
                          <span className="file-icon">-</span>
                        )}
                      </span>
                      <span className="node-name">{node.name}</span>
                      <span className="action-slot">
                        {node.isDirectory ? (
                          <span className="file-count">{node.fileCount}</span>
                        ) : node.status ? (
                          <span className="badge" style={{ color: statusToBadgeColor(node.status) }}>{statusToBadge(node.status)}</span>
                        ) : null}
                      </span>
                    </button>
                  ))}
                </div>
              )}

              {aggregate.fileCount > 0 && (
                <div className="fts-stats-bar">
                  {aggregate.fileCount} changed{' '}
                  <span className="fts-stat-add">+{aggregate.additions}</span>{' '}
                  <span className="fts-stat-del">-{aggregate.deletions}</span>
                </div>
              )}
            </>
          )}

          {rightSidebarTab === 'all-files' && (
            <>
              {allFilesLoading && allFilesTree.length === 0 ? (
                <div className="fts-loading-state">
                  <span className="fts-spinner">&#x280B;</span> loading files...
                </div>
              ) : allFilesError ? (
                <div className="fts-error-state">
                  <span className="fts-error-text">{allFilesError}</span>
                  <button className="fts-retry-btn" onClick={() => loadAllFiles()}>retry</button>
                </div>
              ) : allFilesTree.length === 0 ? (
                <div className="fts-empty-state">empty repository</div>
              ) : (
                <div className="fts-tree" role="tree">
                  {renderAllFilesNode(allFilesTree, 0)}
                </div>
              )}
            </>
          )}

          {rightSidebarTab === 'checks' && (
            <div className="fts-empty-state">checks — coming soon</div>
          )}
        </div>
      </div>
    );
  }
);

export default FileTreeSidebar;

// frontend/src/components/FileTreeSidebar.svelte
<script lang="ts">
  import { getUi, openFileTab, type RightSidebarTab } from '../lib/state/ui.svelte.js';
  import { fetchChangedFiles, fetchDefaultBranch, browseFsDirectory, type BrowseEntry } from '../lib/api.js';
  import type { ChangedFile, DiffSource } from '../lib/types.js';
  import { buildChangedFilesTree, flattenVisibleNodes, statusToBadge, statusToBadgeColor, type FileTreeNode, type FlatNode } from '../lib/file-tree-utils.js';
  import { diffSourceToBase } from '../lib/diff-utils.js';
  import DiffSourceToggle from './DiffSourceToggle.svelte';

  let {
    workspacePath,
    changedFilesData = [],
    onFileSelect,
  }: {
    workspacePath: string;
    changedFilesData?: string[];
    onFileSelect?: (filePath: string, isChanged: boolean) => void;
  } = $props();

  const ui = getUi();

  // ── Changes tab state ──
  let changedFiles = $state<ChangedFile[]>([]);
  let aggregate = $state({ additions: 0, deletions: 0, fileCount: 0 });
  let changesLoading = $state(false);
  let changesError = $state<string | null>(null);
  let treeNodes = $state<FileTreeNode[]>([]);

  // diffSource and defaultBranch are shared via ui state so FileViewerPane stays in sync
  let diffSource = $derived(ui.fileDiffSource);
  let defaultBranch = $derived(ui.fileDiffDefaultBranch);

  // ── All files tab state ──
  let allFilesTree = $state<BrowseEntry[]>([]);
  let allFilesExpanded = $state<Set<string>>(new Set());
  let allFilesChildren = $state<Map<string, BrowseEntry[]>>(new Map());
  let allFilesLoading = $state(false);
  let allFilesError = $state<string | null>(null);

  // ── Cipher-decode animation state ──
  let animatingPaths = $state<Set<string>>(new Set());

  // ── Keyboard nav ──
  let focusedIndex = $state(-1);

  let base = $derived(diffSourceToBase(diffSource, defaultBranch));
  let visibleNodes = $derived(flattenVisibleNodes(treeNodes));

  // ── Fetch changed files ──
  export async function refresh(): Promise<void> {
    if (!workspacePath) return;
    changesLoading = true;
    changesError = null;
    try {
      const data = await fetchChangedFiles(workspacePath, base);
      if (data.error) {
        changesError = data.error;
      } else {
        changedFiles = data.files;
        aggregate = data.aggregate;
        treeNodes = buildChangedFilesTree(data.files);
      }
    } catch (err) {
      changesError = err instanceof Error ? err.message : 'failed to load';
    } finally {
      changesLoading = false;
    }
  }

  // Fetch default branch then refresh — single effect avoids double-fetch on mount
  let lastWorkspacePath = '';
  $effect(() => {
    if (!workspacePath) return;
    // Track base to re-fetch when diff source changes
    void base;
    const wp = workspacePath;
    const needsBranchFetch = wp !== lastWorkspacePath;
    lastWorkspacePath = wp;

    if (needsBranchFetch) {
      fetchDefaultBranch(wp).then(b => {
        ui.fileDiffDefaultBranch = b;
        refresh();
      });
    } else {
      refresh();
    }
  });

  // Handle real-time file change events — mark new files for animation
  $effect(() => {
    const newFiles = changedFilesData;
    if (newFiles.length > 0) {
      const prevSet = new Set(ui.lastChangedFiles);
      const justChanged = newFiles.filter(f => !prevSet.has(f));
      if (justChanged.length > 0) {
        animatingPaths = new Set([...animatingPaths, ...justChanged]);
        setTimeout(() => {
          animatingPaths = new Set([...animatingPaths].filter(p => !justChanged.includes(p)));
        }, 500);
      }
      ui.lastChangedFiles = [...newFiles];
    }
  });

  // ── All files tab ──
  async function loadAllFiles(): Promise<void> {
    if (!workspacePath) return;
    allFilesLoading = true;
    allFilesError = null;
    try {
      const data = await browseFsDirectory(workspacePath, { includeFiles: true, showHidden: false });
      allFilesTree = data.entries;
    } catch (err) {
      allFilesError = err instanceof Error ? err.message : 'failed to load';
    } finally {
      allFilesLoading = false;
    }
  }

  async function toggleAllFilesDir(entryPath: string): Promise<void> {
    if (allFilesExpanded.has(entryPath)) {
      allFilesExpanded.delete(entryPath);
      allFilesExpanded = new Set(allFilesExpanded);
    } else {
      allFilesExpanded.add(entryPath);
      allFilesExpanded = new Set(allFilesExpanded);
      if (!allFilesChildren.has(entryPath)) {
        try {
          const data = await browseFsDirectory(entryPath, { includeFiles: true, showHidden: false });
          allFilesChildren.set(entryPath, data.entries);
          allFilesChildren = new Map(allFilesChildren);
        } catch {
          // best effort
        }
      }
    }
  }

  $effect(() => {
    if (ui.rightSidebarTab === 'all-files' && allFilesTree.length === 0 && !allFilesLoading) {
      loadAllFiles();
    }
  });

  // ── Tree interactions ──
  function handleFileClick(node: FileTreeNode): void {
    if (node.isDirectory) {
      node.expanded = !node.expanded;
      treeNodes = [...treeNodes]; // trigger reactivity
    } else {
      const isChanged = changedFiles.some(f => f.path === node.path);
      openFileTab(node.path, isChanged);
      onFileSelect?.(node.path, isChanged);
    }
  }

  function handleAllFilesClick(entry: BrowseEntry): void {
    if (entry.isDirectory !== false) {
      toggleAllFilesDir(entry.path);
    } else {
      // Derive relative path safely via prefix check + slice
      const prefix = workspacePath + '/';
      const relativePath = entry.path.startsWith(prefix)
        ? entry.path.slice(prefix.length)
        : entry.path;
      const isChanged = changedFiles.some(f => f.path === relativePath);
      openFileTab(relativePath, isChanged);
      onFileSelect?.(relativePath, isChanged);
    }
  }

  function handleKeydown(e: KeyboardEvent): void {
    const nodes = visibleNodes;
    if (nodes.length === 0) return;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      focusedIndex = Math.min(focusedIndex + 1, nodes.length - 1);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      focusedIndex = Math.max(focusedIndex - 1, 0);
    } else if (e.key === 'Enter' && focusedIndex >= 0 && focusedIndex < nodes.length) {
      e.preventDefault();
      handleFileClick(nodes[focusedIndex]!.node);
    }
  }

  function setTab(tab: RightSidebarTab): void {
    ui.rightSidebarTab = tab;
  }

  // Check if a file path has the "recently changed" blue dot
  function isRecentlyChanged(filePath: string): boolean {
    return changedFilesData.length > 0 && changedFilesData.includes(filePath);
  }
</script>

{#if !ui.rightSidebarCollapsed}
  <div
    class="sidebar"
    role="complementary"
    aria-label="file tree"
    style="width: {ui.rightSidebarWidth}px"
  >
    <!-- Tab bar -->
    <div class="tab-bar" role="tablist">
      {#each [
        { id: 'changes' as RightSidebarTab, label: 'changes' },
        { id: 'all-files' as RightSidebarTab, label: 'all files' },
        { id: 'checks' as RightSidebarTab, label: 'checks' },
      ] as tab (tab.id)}
        <button
          class="tab"
          class:active={ui.rightSidebarTab === tab.id}
          role="tab"
          aria-selected={ui.rightSidebarTab === tab.id}
          onclick={() => setTab(tab.id)}
        >
          {tab.label}
          {#if tab.id === 'changes' && aggregate.fileCount > 0}
            <span class="tab-count">{aggregate.fileCount}</span>
          {/if}
        </button>
      {/each}
    </div>

    <!-- Tab content -->
    <div class="tab-content">
      {#if ui.rightSidebarTab === 'changes'}
        <!-- Diff source toggle -->
        <div class="controls-row">
          <DiffSourceToggle value={diffSource} onchange={(s) => { ui.fileDiffSource = s; }} {defaultBranch} />
        </div>

        {#if changesLoading && changedFiles.length === 0}
          <div class="loading-state">
            <span class="spinner">&#x280B;</span> loading changes...
          </div>
        {:else if changesError}
          <div class="error-state">
            <span class="error-text">{changesError}</span>
            <button class="retry-btn" onclick={() => refresh()}>retry</button>
          </div>
        {:else if visibleNodes.length === 0}
          <div class="empty-state">
            no changes yet — when an agent writes code, changed files appear here. click any line to send it as context.
          </div>
        {:else}
          <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
          <div class="tree" role="tree" tabindex="0" onkeydown={handleKeydown}>
            {#each visibleNodes as { node, depth }, i (node.path)}
              {@const isFocused = focusedIndex === i}
              {@const isAnimating = animatingPaths.has(node.path)}
              <button
                class="tree-item"
                class:focused={isFocused}
                class:animating={isAnimating}
                class:directory={node.isDirectory}
                class:file={!node.isDirectory}
                role="treeitem"
                aria-selected={isFocused}
                aria-expanded={node.isDirectory ? node.expanded : undefined}
                aria-label="{node.name}{node.status ? `, ${node.status}` : ''}{node.additions ? `, ${node.additions} additions` : ''}{node.deletions ? `, ${node.deletions} deletions` : ''}{isRecentlyChanged(node.path) ? ', recently changed' : ''}"
                style="padding-left: {8 + depth * 16}px"
                onclick={() => handleFileClick(node)}
              >
                <span class="icon-slot">
                  {#if isRecentlyChanged(node.path) && !node.isDirectory}
                    <span class="blue-dot" aria-label="recently changed"></span>
                  {:else if node.isDirectory}
                    <span class="expand-arrow">{node.expanded ? 'v' : '>'}</span>
                  {:else}
                    <span class="file-icon">-</span>
                  {/if}
                </span>
                <span class="node-name">{node.name}</span>
                <span class="action-slot">
                  {#if node.isDirectory}
                    <span class="file-count">{node.fileCount}</span>
                  {:else if node.status}
                    <span class="badge" style="color: {statusToBadgeColor(node.status)}">{statusToBadge(node.status)}</span>
                  {/if}
                </span>
              </button>
            {/each}
          </div>
        {/if}

        <!-- Aggregate stats -->
        {#if aggregate.fileCount > 0}
          <div class="stats-bar">
            {aggregate.fileCount} changed
            <span class="stat-add">+{aggregate.additions}</span>
            <span class="stat-del">-{aggregate.deletions}</span>
          </div>
        {/if}

      {:else if ui.rightSidebarTab === 'all-files'}
        {#if allFilesLoading && allFilesTree.length === 0}
          <div class="loading-state">
            <span class="spinner">&#x280B;</span> loading files...
          </div>
        {:else if allFilesError}
          <div class="error-state">
            <span class="error-text">{allFilesError}</span>
            <button class="retry-btn" onclick={() => loadAllFiles()}>retry</button>
          </div>
        {:else if allFilesTree.length === 0}
          <div class="empty-state">empty repository</div>
        {:else}
          {#snippet allFilesNode(entries: BrowseEntry[], depth: number)}
            {#each entries as entry (entry.path)}
              <button
                class="tree-item"
                class:directory={entry.isDirectory !== false}
                class:file={entry.isDirectory === false}
                role="treeitem"
                aria-expanded={entry.isDirectory !== false ? allFilesExpanded.has(entry.path) : undefined}
                aria-selected={false}
                style="padding-left: {8 + depth * 16}px"
                onclick={() => handleAllFilesClick(entry)}
              >
                <span class="icon-slot">
                  {#if entry.isDirectory !== false}
                    <span class="expand-arrow">{allFilesExpanded.has(entry.path) ? 'v' : '>'}</span>
                  {:else}
                    <span class="file-icon">-</span>
                  {/if}
                </span>
                <span class="node-name">{entry.name}</span>
                {#if entry.isDirectory !== false && entry.hasChildren}
                  <span class="action-slot">
                    <span class="has-children-dot"></span>
                  </span>
                {/if}
              </button>
              {#if allFilesExpanded.has(entry.path) && allFilesChildren.has(entry.path)}
                {@render allFilesNode(allFilesChildren.get(entry.path) ?? [], depth + 1)}
              {/if}
            {/each}
          {/snippet}

          <div class="tree" role="tree">
            {@render allFilesNode(allFilesTree, 0)}
          </div>
        {/if}

      {:else if ui.rightSidebarTab === 'checks'}
        <div class="empty-state">checks — coming soon</div>
      {/if}
    </div>
  </div>
{/if}

<style>
  .sidebar {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--bg, #000);
    border-left: 1px solid var(--border, #333);
    overflow: hidden;
    min-width: 160px;
  }

  /* Tab bar */
  .tab-bar {
    display: flex;
    border-bottom: 1px solid var(--border, #333);
    padding: 0;
    flex-shrink: 0;
  }

  .tab {
    flex: 1;
    padding: 6px 8px;
    background: none;
    border: none;
    border-bottom: 1px solid transparent;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
    cursor: pointer;
    white-space: nowrap;
  }

  .tab:hover {
    color: var(--text, #e0e0e0);
  }

  .tab.active {
    color: var(--text, #e0e0e0);
    border-bottom-color: var(--accent, #d97757);
  }

  .tab-count {
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
    margin-left: 4px;
  }

  /* Tab content */
  .tab-content {
    flex: 1;
    overflow-y: auto;
    overflow-x: hidden;
  }

  .controls-row {
    padding: 4px 8px;
    border-bottom: 1px solid var(--border, #333);
  }

  /* Tree */
  .tree {
    outline: none;
  }

  .tree-item {
    display: flex;
    align-items: center;
    width: 100%;
    min-height: 26px;
    padding: 2px 8px;
    background: none;
    border: none;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text, #e0e0e0);
    cursor: pointer;
    text-align: left;
    gap: 4px;
  }

  .tree-item.file {
    color: var(--text-muted, #888);
  }

  .tree-item:hover {
    background: var(--surface-hover, #141414);
  }

  .tree-item.file:hover {
    color: var(--text, #e0e0e0);
  }

  .tree-item.focused {
    background: var(--surface-hover, #141414);
    outline: 1px solid var(--accent, #d97757);
    outline-offset: -1px;
  }

  .tree-item.animating {
    animation: flash-accent 300ms ease-out;
  }

  @keyframes flash-accent {
    0% { background: color-mix(in srgb, var(--accent) 10%, transparent); }
    100% { background: transparent; }
  }

  .icon-slot {
    width: 16px;
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .expand-arrow {
    color: var(--text, #e0e0e0);
    font-size: var(--font-size-xs, 0.75rem);
  }

  .file-icon {
    color: var(--border, #333);
    font-size: var(--font-size-xs, 0.75rem);
  }

  .blue-dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: var(--status-info, #60a5fa);
  }

  .node-name {
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .action-slot {
    flex-shrink: 0;
    min-width: 24px;
    text-align: right;
  }

  .badge {
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    font-weight: 600;
  }

  .file-count {
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
  }

  .has-children-dot {
    display: inline-block;
    width: 4px;
    height: 4px;
    border-radius: 50%;
    background: var(--text-muted, #888);
  }

  /* States */
  .loading-state, .error-state, .empty-state {
    padding: 12px 8px;
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
  }

  .error-state {
    color: var(--status-error, #f87171);
  }

  .error-text {
    font-size: var(--font-size-xs, 0.75rem);
  }

  .retry-btn {
    display: inline-block;
    margin-top: 8px;
    padding: 2px 8px;
    background: none;
    border: 1px solid var(--border, #333);
    color: var(--text-muted, #888);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    cursor: pointer;
  }

  .retry-btn:hover {
    color: var(--text, #e0e0e0);
    border-color: var(--text-muted, #888);
  }

  .spinner {
    display: inline-block;
    animation: spin 0.8s steps(8) infinite;
  }

  @keyframes spin {
    to { content: '⠏'; }
  }

  /* Stats bar */
  .stats-bar {
    padding: 4px 8px;
    border-top: 1px solid var(--border, #333);
    font-family: var(--font-mono, monospace);
    font-size: var(--font-size-xs, 0.75rem);
    color: var(--text-muted, #888);
    flex-shrink: 0;
  }

  .stat-add {
    color: var(--status-success, #4ade80);
  }

  .stat-del {
    color: var(--status-error, #f87171);
  }
</style>
