// frontend/src/components/MobileHeader.tsx
import './MobileHeader.css';

export interface MobileHeaderProps {
  title: string;
  onMenuClick: () => void;
  onCommandClick: () => void;
  hidden?: boolean;
}

export function MobileHeader({
  title,
  onMenuClick,
  onCommandClick,
  hidden = false,
}: MobileHeaderProps) {
  return (
    <div className={`mobile-header${hidden ? ' hidden' : ''}`}>
      <button className="icon-btn" aria-label="Open sessions menu" onClick={onMenuClick}>
        ☰
      </button>
      <span className="mobile-title">{title}</span>
      <button className="command-trigger" aria-label="Open command palette" onClick={onCommandClick}>
        {'> command'}
      </button>
    </div>
  );
}

export default MobileHeader;

// frontend/src/components/MobileHeader.svelte
<script lang="ts">
  let {
    title,
    onMenuClick,
    onCommandClick,
    hidden = false,
  }: {
    title: string;
    onMenuClick: () => void;
    onCommandClick: () => void;
    hidden?: boolean;
  } = $props();
</script>

<div class="mobile-header" class:hidden>
  <button
    class="icon-btn"
    aria-label="Open sessions menu"
    onclick={onMenuClick}
  >&#9776;</button>
  <span class="mobile-title">{title}</span>
  <button
    class="command-trigger"
    aria-label="Open command palette"
    onclick={onCommandClick}
  >&gt; command</button>
</div>

<style>
  .mobile-header {
    display: none;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
    min-height: 44px;
    flex-shrink: 0;
  }

  @media (max-width: 600px) {
    .mobile-header {
      display: flex;
    }
    .mobile-header.hidden {
      display: none;
    }
  }

  .mobile-title {
    font-size: var(--font-size-base);
    color: var(--text);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    flex: 1;
  }

  .icon-btn {
    background: none;
    border: none;
    color: var(--text);
    font-size: var(--font-size-lg);
    cursor: pointer;
    padding: 8px;
    min-width: 36px;
    min-height: 36px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 0;
    touch-action: manipulation;
  }

  .icon-btn:hover {
    background: var(--border);
  }

  .command-trigger {
    background: none;
    border: 1px solid var(--accent);
    color: var(--accent);
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    padding: 4px 10px;
    cursor: pointer;
    min-height: 44px;
    display: flex;
    align-items: center;
    border-radius: 0;
    touch-action: manipulation;
    white-space: nowrap;
    flex-shrink: 0;
  }

  .command-trigger:active {
    background: var(--accent);
    color: var(--surface);
  }
</style>
