// frontend/src/components/PickerResultRow.svelte
<script lang="ts">
  import type { SessionIntent } from '../lib/session-intent.js';
  import type { StatusColor } from '../lib/pr-state.js';
  import StatusDot from './StatusDot.svelte';
  import TuiButton from './TuiButton.svelte';
  import type { PrDotStatus } from '../lib/pr-status.js';

  let {
    label,
    sublabel = '',
    dotStatus,
    intents,
    focused = false,
    onSelectIntent,
    onRowClick,
  }: {
    label: string;
    sublabel?: string;
    dotStatus?: PrDotStatus;
    intents: SessionIntent[];
    focused?: boolean;
    onSelectIntent: (intent: SessionIntent) => void;
    onRowClick?: () => void;
  } = $props();

  function colorToVariant(color: StatusColor): 'primary' | 'ghost' | 'danger' | 'success' | 'info' {
    if (color === 'success') return 'success';
    if (color === 'error') return 'danger';
    if (color === 'info') return 'info';
    if (color === 'accent') return 'primary';
    return 'ghost';
  }

  let primary = $derived(intents[0]);
  let secondary = $derived(intents.slice(1));
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<div
  class="picker-row"
  class:focused
  role="option"
  aria-selected={focused}
  onclick={() => {
    if (primary) onSelectIntent(primary);
    else onRowClick?.();
  }}
>
  <div class="row-left">
    {#if dotStatus}
      <StatusDot status={dotStatus} size={7} />
    {:else}
      <span class="row-icon">▸</span>
    {/if}
    <div class="row-text">
      <span class="row-label">{label}</span>
      {#if sublabel}
        <span class="row-sublabel">{sublabel}</span>
      {/if}
    </div>
  </div>
  <div class="row-actions">
    {#each secondary as intent}
      <TuiButton
        variant={colorToVariant(intent.color)}
        size="sm"
        onclick={(e) => { e.stopPropagation(); onSelectIntent(intent); }}
      >
        {intent.label}
      </TuiButton>
    {/each}
    {#if primary}
      <TuiButton
        variant={colorToVariant(primary.color)}
        size="sm"
        onclick={(e) => { e.stopPropagation(); onSelectIntent(primary); }}
      >
        {primary.label}
      </TuiButton>
    {/if}
  </div>
</div>

<style>
  .picker-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 16px;
    min-height: 44px;
    cursor: pointer;
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    color: var(--text-muted);
    transition: background 0.08s;
    gap: 8px;
  }

  .picker-row:hover,
  .picker-row.focused {
    background: var(--surface-hover);
    color: var(--text);
  }

  .row-left {
    display: flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
    flex: 1;
  }

  .row-icon {
    flex-shrink: 0;
    width: 16px;
    text-align: center;
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    opacity: 0.6;
  }

  .row-text {
    display: flex;
    flex-direction: column;
    gap: 2px;
    min-width: 0;
  }

  .row-label {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .row-sublabel {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    opacity: 0.5;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .row-actions {
    display: flex;
    align-items: center;
    gap: 6px;
    flex-shrink: 0;
  }

  @media (max-width: 600px) {
    .picker-row {
      flex-direction: column;
      align-items: flex-start;
      gap: 8px;
    }

    .row-actions {
      align-self: flex-end;
    }
  }
</style>

// frontend/src/components/PickerResultRow.tsx
import React from 'react';
import type { SessionIntent } from '../lib/session-intent.js';
import type { StatusColor } from '../lib/pr-state.js';
import type { PrDotStatus } from '../lib/pr-status.js';
import { StatusDot } from './StatusDot.js';
import { TuiButton } from './TuiButton.js';
import './PickerResultRow.css';

interface PickerResultRowProps {
  label: string;
  sublabel?: string;
  dotStatus?: PrDotStatus;
  intents: SessionIntent[];
  focused?: boolean;
  onSelectIntent: (intent: SessionIntent) => void;
  onRowClick?: () => void;
}

function colorToVariant(color: StatusColor): 'primary' | 'ghost' | 'danger' | 'success' | 'info' {
  if (color === 'success') return 'success';
  if (color === 'error') return 'danger';
  if (color === 'info') return 'info';
  if (color === 'accent') return 'primary';
  return 'ghost';
}

export function PickerResultRow({
  label,
  sublabel = '',
  dotStatus,
  intents,
  focused = false,
  onSelectIntent,
  onRowClick,
}: PickerResultRowProps) {
  const primary = intents[0];
  const secondary = intents.slice(1);

  const handleRowClick = () => {
    if (primary) {
      onSelectIntent(primary);
    } else {
      onRowClick?.();
    }
  };

  const rowClass = ['picker-row', focused && 'focused'].filter(Boolean).join(' ');

  return (
    <div
      className={rowClass}
      role="option"
      aria-selected={focused}
      onClick={handleRowClick}
    >
      <div className="row-left">
        {dotStatus ? (
          <StatusDot status={dotStatus} size={7} />
        ) : (
          <span className="row-icon">&#9656;</span>
        )}
        <div className="row-text">
          <span className="row-label">{label}</span>
          {sublabel && <span className="row-sublabel">{sublabel}</span>}
        </div>
      </div>
      <div className="row-actions">
        {secondary.map((intent, i) => (
          <TuiButton
            key={i}
            variant={colorToVariant(intent.color)}
            size="sm"
            onClick={(e) => { e.stopPropagation(); onSelectIntent(intent); }}
          >
            {intent.label}
          </TuiButton>
        ))}
        {primary && primary.label && (
          <TuiButton
            variant={colorToVariant(primary.color)}
            size="sm"
            onClick={(e) => { e.stopPropagation(); onSelectIntent(primary); }}
          >
            {primary.label}
          </TuiButton>
        )}
      </div>
    </div>
  );
}

export default PickerResultRow;
