// frontend/src/components/PinInput.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import './PinInput.css';

export interface PinInputProps {
  id?: string;
  value?: string;
  placeholder?: string;
  onKeyDown?: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  maxLength?: number;
  autoFocus?: boolean;
  onChange?: (value: string) => void;
  onComplete?: (value: string) => void;
  error?: boolean;
  disabled?: boolean;
  length?: number;
}

export function PinInput({
  id,
  value = '',
  placeholder = 'PIN',
  onKeyDown,
  maxLength = 20,
  autoFocus = false,
  onChange,
  onComplete,
  error = false,
  disabled = false,
  length,
}: PinInputProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [isFocused, setIsFocused] = useState(false);
  const [isIdle, setIsIdle] = useState(true);
  const idleTimeoutRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const [prefersReducedMotion, setPrefersReducedMotion] = useState(false);

  useEffect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    setPrefersReducedMotion(mq.matches);

    const handler = (e: MediaQueryListEvent) => {
      setPrefersReducedMotion(e.matches);
    };

    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, []);

  useEffect(() => {
    return () => {
      if (idleTimeoutRef.current !== undefined) {
        clearTimeout(idleTimeoutRef.current);
      }
    };
  }, []);

  const resetIdle = useCallback(() => {
    setIsIdle(false);
    if (idleTimeoutRef.current !== undefined) {
      clearTimeout(idleTimeoutRef.current);
    }
    idleTimeoutRef.current = setTimeout(() => {
      setIsIdle(true);
    }, 530);
  }, []);

  const handleInput = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const newValue = e.target.value;
      onChange?.(newValue);
      resetIdle();

      if (length !== undefined && newValue.length === length) {
        onComplete?.(newValue);
      }
    },
    [onChange, onComplete, length, resetIdle]
  );

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      resetIdle();
      onKeyDown?.(e);
    },
    [onKeyDown, resetIdle]
  );

  const handleFocus = useCallback(() => {
    setIsFocused(true);
  }, []);

  const handleBlur = useCallback(() => {
    setIsFocused(false);
    if (idleTimeoutRef.current !== undefined) {
      clearTimeout(idleTimeoutRef.current);
      idleTimeoutRef.current = undefined;
    }
    setIsIdle(true);
  }, []);

  const focusInput = useCallback(() => {
    inputRef.current?.focus();
  }, []);

  const dots = value.length;
  const showPlaceholder = !value && !isFocused;

  return (
    <div
      className={`pin-input ${isFocused ? 'focused' : ''} ${error ? 'error' : ''} ${disabled ? 'disabled' : ''}`}
      onClick={focusInput}
    >
      <input
        ref={inputRef}
        id={id}
        type="password"
        inputMode="numeric"
        maxLength={maxLength}
        className="pin-hidden-input"
        value={value}
        onChange={handleInput}
        onKeyDown={handleKeyDown}
        onFocus={handleFocus}
        onBlur={handleBlur}
        autoFocus={autoFocus}
        disabled={disabled}
      />
      <div className="pin-display">
        {showPlaceholder ? (
          <span className="pin-placeholder">{placeholder}</span>
        ) : (
          <>
            {Array.from({ length: dots }).map((_, i) => (
              <span key={i} className="pin-dot">
                {'\u2022'}
              </span>
            ))}
            {isFocused && (
              <span className={`pin-cursor ${isIdle && !prefersReducedMotion ? 'blinking' : ''}`}>
                {'\u2588'}
              </span>
            )}
          </>
        )}
      </div>
    </div>
  );
}

// frontend/src/components/PinInput.svelte
<script lang="ts">
  let {
    value = $bindable(''),
    placeholder = 'PIN',
    onkeydown,
    maxlength = 20,
    autofocus = false,
  }: {
    value?: string;
    placeholder?: string;
    onkeydown?: (e: KeyboardEvent) => void;
    maxlength?: number;
    autofocus?: boolean;
  } = $props();

  let inputEl = $state<HTMLInputElement | undefined>(undefined);
  let isFocused = $state(false);
  let isIdle = $state(true);
  let idleTimeout: ReturnType<typeof setTimeout> | undefined;
  let prefersReducedMotion = $state(false);

  let dots = $derived(value.length);
  let showPlaceholder = $derived(!value && !isFocused);

  $effect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    prefersReducedMotion = mq.matches;
    const handler = (e: MediaQueryListEvent) => { prefersReducedMotion = e.matches; };
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  });

  function resetIdle() {
    isIdle = false;
    if (idleTimeout !== undefined) clearTimeout(idleTimeout);
    idleTimeout = setTimeout(() => { isIdle = true; }, 530);
  }

  function handleInput(e: Event) {
    value = (e.target as HTMLInputElement).value;
    resetIdle();
  }

  function handleKeydown(e: KeyboardEvent) {
    resetIdle();
    onkeydown?.(e);
  }

  function handleFocus() {
    isFocused = true;
  }

  function handleBlur() {
    isFocused = false;
    if (idleTimeout !== undefined) {
      clearTimeout(idleTimeout);
      idleTimeout = undefined;
    }
    isIdle = true;
  }

  function focusInput() {
    inputEl?.focus();
  }

  $effect(() => {
    return () => {
      if (idleTimeout !== undefined) clearTimeout(idleTimeout);
    };
  });
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="pin-input"
  class:focused={isFocused}
  onclick={focusInput}
>
  <input
    bind:this={inputEl}
    bind:value
    type="password"
    inputmode="numeric"
    {maxlength}
    class="pin-hidden-input"
    oninput={handleInput}
    onkeydown={handleKeydown}
    onfocus={handleFocus}
    onblur={handleBlur}
    autofocus={autofocus ? true : undefined}
  />
  <div class="pin-display">
    {#if showPlaceholder}
      <span class="pin-placeholder">{placeholder}</span>
    {:else}
      {#each { length: dots } as _, i}
        <span class="pin-dot">{'\u2022'}</span>
      {/each}
      {#if isFocused}
        <span
          class="pin-cursor"
          class:blinking={isIdle && !prefersReducedMotion}
        >&#x2588;</span>
      {/if}
    {/if}
  </div>
</div>

<style>
  .pin-input {
    position: relative;
    width: 100%;
    border: 1px solid var(--border);
    background: var(--surface);
    padding: 16px;
    cursor: text;
    box-sizing: border-box;
  }

  .pin-input.focused {
    border-color: var(--accent);
  }

  .pin-hidden-input {
    position: absolute;
    opacity: 0;
    width: 0;
    height: 0;
    pointer-events: none;
  }

  .pin-display {
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: var(--font-mono);
    font-size: var(--font-size-lg);
    color: var(--text);
    min-height: 1.2em;
    gap: 0.15em;
  }

  .pin-placeholder {
    color: var(--text-muted);
  }

  .pin-dot {
    line-height: 1;
  }

  .pin-cursor {
    opacity: 0.7;
    line-height: 1;
  }

  .pin-cursor.blinking {
    animation: cursor-blink 1s step-end infinite;
  }

  @keyframes cursor-blink {
    0%, 100% { opacity: 0.7; }
    50% { opacity: 0; }
  }
</style>
