// frontend/src/components/PrGlyph.svelte
<script lang="ts">
  import type { PrDotStatus } from '../lib/pr-status.js';
  import { prGlyph } from '../lib/pr-status.js';

  let { status }: { status: PrDotStatus } = $props();
  let glyph = $derived(prGlyph(status));
</script>

<span class="pr-glyph {glyph.colorClass}" role="img" aria-label={glyph.label} title={glyph.label}>{glyph.char}</span>

<style>
  .pr-glyph {
    font-family: var(--font-mono);
    font-size: 10px;
    line-height: 1;
    flex-shrink: 0;
  }

  .pr-gray   { color: #555; }
  .pr-blue   { color: #4a9eff; }
  .pr-yellow { color: #f0c674; }
  .pr-red    { color: #e05252; }
  .pr-green  { color: #5cb85c; }
  .pr-purple { color: #b294bb; }
</style>

// frontend/src/components/PrGlyph.tsx
import type { PrDotStatus } from '../lib/pr-status';
import { prGlyph } from '../lib/pr-status';
import './PrGlyph.css';

interface PrGlyphProps {
  status: PrDotStatus;
}

export function PrGlyph({ status }: PrGlyphProps) {
  const glyph = prGlyph(status);
  
  return (
    <span
      className={`pr-glyph ${glyph.colorClass}`}
      role="img"
      aria-label={glyph.label}
      title={glyph.label}
    >
      {glyph.char}
    </span>
  );
}
