// frontend/src/components/PrTopBar.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import {
  fetchPrForBranchOrNull,
  fetchCiStatusOrNull,
  fetchCurrentBranch,
} from '../lib/api.js';
import { sendPtyData } from '../lib/ws.js';
import {
  derivePrAction,
  deriveSecondaryAction,
  getActionPrompt,
} from '../lib/pr-state.js';
import type { PrAction, StatusColor } from '../lib/pr-state.js';
import type { PrInfo, CiStatus } from '../lib/types.js';
import CipherText from './CipherText.js';
import TuiButton from './TuiButton.js';
import BranchSwitcher from './BranchSwitcher.js';
import TargetBranchSwitcher from './TargetBranchSwitcher.js';
import { useUiStore } from '../lib/stores/ui.js';
import './PrTopBar.css';

export interface PrTopBarProps {
  workspacePath: string;
  branchName: string;
  sessionId: string | null;
  agentRunning?: boolean;
  onArchive?: () => void;
}

function colorToVariant(color: StatusColor): 'primary' | 'ghost' | 'danger' | 'success' | 'info' {
  if (color === 'success') return 'success';
  if (color === 'error') return 'danger';
  if (color === 'accent') return 'primary';
  return 'ghost';
}

// ── Hooks ────────────────────────────────────────────────────────────────────

interface PrDataState {
  pr: PrInfo | null;
  ci: CiStatus | null;
  isRefreshing: boolean;
  prLoading: boolean;
  refresh: () => void;
}

function usePrData(workspacePath: string, currentBranch: string, sessionId: string | null): PrDataState {
  const [pr, setPr] = useState<PrInfo | null>(null);
  const [ci, setCi] = useState<CiStatus | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [prLoading, setPrLoading] = useState(false);

  const fetchPrAndCi = useCallback(async () => {
    if (!currentBranch) return;
    setIsRefreshing(true);
    setPrLoading(true);
    try {
      const prData = await fetchPrForBranchOrNull(workspacePath, currentBranch);
      setPr(prData);
      if (prData?.state === 'OPEN') {
        const ciData = await fetchCiStatusOrNull(workspacePath, currentBranch);
        setCi(ciData);
      } else {
        setCi(null);
      }
    } finally {
      setIsRefreshing(false);
      setPrLoading(false);
    }
  }, [workspacePath, currentBranch]);

  useEffect(() => { void fetchPrAndCi(); }, [fetchPrAndCi, sessionId]);
  return { pr, ci, isRefreshing, prLoading, refresh: () => { void fetchPrAndCi(); } };
}

interface RenameState {
  renaming: boolean;
  renameValue: string;
  renameSubmitting: boolean;
  renameWarning: { oldName: string; newName: string } | null;
  renameInputRef: React.RefObject<HTMLInputElement | null>;
  startRename: () => void;
  cancelRename: () => void;
  confirmRename: () => Promise<void>;
  handleRenameKeydown: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  setRenameValue: (v: string) => void;
  clearWarning: () => void;
}

function useRename(workspacePath: string, currentBranch: string, agentRunning: boolean,
  hasPr: boolean, onBranchRenamed: (name: string) => void): RenameState {
  const [renaming, setRenaming] = useState(false);
  const [renameValue, setRenameValue] = useState('');
  const [renameSubmitting, setRenameSubmitting] = useState(false);
  const [renameWarning, setRenameWarning] = useState<{ oldName: string; newName: string } | null>(null);
  const renameInputRef = useRef<HTMLInputElement>(null);

  function startRename() {
    if (agentRunning) return;
    setRenaming(true);
    setRenameValue(currentBranch);
    requestAnimationFrame(() => renameInputRef.current?.focus());
  }

  function cancelRename() {
    if (renameSubmitting) return;
    setRenaming(false);
    setRenameValue('');
  }

  async function confirmRename() {
    const trimmed = renameValue.trim();
    if (!trimmed || trimmed === currentBranch) { cancelRename(); return; }
    setRenameSubmitting(true);
    try {
      const res = await fetch('/workspaces/rename-branch?path=' + encodeURIComponent(workspacePath), {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ newName: trimmed }),
      });
      const data = (await res.json()) as { success?: boolean; oldName?: string; newName?: string; error?: string };
      setRenaming(false);
      setRenameValue('');
      if (data.success && data.oldName && data.newName) {
        onBranchRenamed(data.newName);
        if (hasPr) setRenameWarning({ oldName: data.oldName, newName: data.newName });
      }
    } catch {
      setRenaming(false);
      setRenameValue('');
    } finally {
      setRenameSubmitting(false);
    }
  }

  function handleRenameKeydown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter') { e.preventDefault(); void confirmRename(); }
    else if (e.key === 'Escape') cancelRename();
  }

  return { renaming, renameValue, renameSubmitting, renameWarning, renameInputRef,
    startRename, cancelRename, confirmRename, handleRenameKeydown, setRenameValue,
    clearWarning: () => setRenameWarning(null) };
}

// ── Sub-components ───────────────────────────────────────────────────────────

const COPY_SVG_CHECK = (
  <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
    <path d="M3 8l3 3 7-7" stroke="currentColor" fill="none" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);
const COPY_SVG_DEFAULT = (
  <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
    <rect x="5" y="5" width="9" height="9" rx="1.5" stroke="currentColor" fill="none" strokeWidth="1.5" />
    <path d="M3 11V3a1.5 1.5 0 011.5-1.5H11" stroke="currentColor" fill="none" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);
const RENAME_SVG = (
  <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
    <path d="M11.5 1.5l3 3L5 14H2v-3L11.5 1.5z" stroke="currentColor" fill="none" strokeWidth="1.5" strokeLinejoin="round" />
  </svg>
);

interface BranchSectionProps {
  workspacePath: string;
  currentBranch: string;
  agentRunning: boolean;
  pr: PrInfo | null;
  rename: RenameState;
  copyFeedback: boolean;
  onBranchSwitch: (branch: string) => void;
  onCopy: () => void;
  onBaseChanged: () => void;
}

function BranchSection({ workspacePath, currentBranch, agentRunning, pr, rename,
  copyFeedback, onBranchSwitch, onCopy, onBaseChanged }: BranchSectionProps) {
  return (
    <div className="bar-left">
      {rename.renaming ? (
        <div className="rename-input-wrap">
          <span className="branch-icon">⑂</span>
          <input ref={rename.renameInputRef} type="text" className="rename-input" value={rename.renameValue}
            onChange={(e) => rename.setRenameValue(e.currentTarget.value)} onKeyDown={rename.handleRenameKeydown} onBlur={rename.cancelRename} />
        </div>
      ) : (
        <div className="branch-with-actions">
          <BranchSwitcher repoPath={workspacePath} currentWorktreePath={workspacePath}
            currentBranch={currentBranch} disabled={agentRunning} onSwitch={onBranchSwitch} />
          <div className="hover-icons">
            <button className="hover-icon" onClick={onCopy}
              title={copyFeedback ? 'Copied!' : 'Copy branch name'} aria-label="Copy branch name" type="button">
              {copyFeedback ? COPY_SVG_CHECK : COPY_SVG_DEFAULT}
            </button>
            <button className="hover-icon" onClick={rename.startRename} disabled={agentRunning}
              title={agentRunning ? 'Unavailable while agent is running' : 'Rename branch'}
              aria-label="Rename branch" type="button">{RENAME_SVG}
            </button>
          </div>
        </div>
      )}
      {pr?.baseRefName ? (
        <span className="target-section">
          <span className="target-arrow" aria-hidden="true">
            <svg width="14" height="10" viewBox="0 0 14 10" aria-hidden="true">
              <path d="M1 5h10M8 2l3 3-3 3" stroke="currentColor" fill="none" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </span>
          <TargetBranchSwitcher workspacePath={workspacePath} currentBase={pr.baseRefName}
            prNumber={pr.number} disabled={agentRunning} onBaseChanged={onBaseChanged} />
        </span>
      ) : null}
    </div>
  );
}

interface PrActionsProps {
  isRefreshing: boolean;
  prLoading: boolean;
  prAction: PrAction;
  secondaryAction: PrAction | null;
  onRefresh: () => void;
  onAction: (action?: PrAction) => void;
}

function PrActions({ isRefreshing, prLoading, prAction, secondaryAction, onRefresh, onAction }: PrActionsProps) {
  const rightSidebarCollapsed = useUiStore((s) => s.rightSidebarCollapsed);
  const toggleRightSidebarCollapsed = useUiStore((s) => s.toggleRightSidebarCollapsed);

  return (
    <div className="bar-right">
      <button className={['refresh-btn', isRefreshing && 'refreshing'].filter(Boolean).join(' ')}
        onClick={onRefresh} disabled={isRefreshing} aria-label="Refresh PR data" title="Refresh PR data" type="button">
        <svg width="12" height="12" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <path d="M14 8A6 6 0 1 1 8 2" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
          <path d="M8 0L14 2L12 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" fill="none" />
        </svg>
      </button>
      {prLoading ? <CipherText text="loading" loading={true} /> : (
        <>
          {secondaryAction ? (
            <TuiButton variant="ghost" size="sm" data-track="pr-top-bar.secondary-action"
              onClick={() => onAction(secondaryAction)} aria-label={secondaryAction.label}>
              {secondaryAction.label}
            </TuiButton>
          ) : null}
          {prAction.type !== 'none' ? (
            <TuiButton variant={colorToVariant(prAction.color)} size="sm" data-track="pr-top-bar.primary-action"
              onClick={() => onAction()} disabled={prAction.type === 'checks-running'} aria-label={prAction.label}>
              {prAction.label}
            </TuiButton>
          ) : null}
        </>
      )}
      <button className="sidebar-toggle-btn" onClick={toggleRightSidebarCollapsed}
        aria-label={rightSidebarCollapsed ? 'Show file sidebar' : 'Hide file sidebar'}
        title={rightSidebarCollapsed ? 'Show file sidebar' : 'Hide file sidebar'} type="button">
        <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <rect x="1" y="2" width="14" height="12" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="square" />
          <line x1="10" y1="2" x2="10" y2="14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
        </svg>
      </button>
    </div>
  );
}

// ── Helpers ──────────────────────────────────────────────────────────────────

type PrStateType = 'OPEN' | 'CLOSED' | 'MERGED' | 'DRAFT' | null;

function buildPrStateInput(pr: PrInfo | null, ci: CiStatus | null) {
  const prState: PrStateType = pr ? (pr.isDraft ? 'DRAFT' : pr.state) : null;
  return {
    commitsAhead: pr ? 1 : 0,
    prState,
    ciPassing: ci?.passing ?? 0,
    ciFailing: ci?.failing ?? 0,
    ciPending: ci?.pending ?? 0,
    ciTotal: ci?.total ?? 0,
    mergeable: pr?.mergeable ?? null,
    unresolvedCommentCount: pr?.unresolvedCommentCount ?? 0,
  };
}

function deriveBarClass(pr: PrInfo | null): string {
  return ['pr-top-bar', pr?.state === 'MERGED' && 'bar-merged',
    pr?.mergeable === 'CONFLICTING' && 'bar-conflicts'].filter(Boolean).join(' ');
}

// ── Main component ───────────────────────────────────────────────────────────

export function PrTopBar({ workspacePath, branchName, sessionId, agentRunning = false, onArchive }: PrTopBarProps) {
  const [currentBranch, setCurrentBranch] = useState(branchName);
  const [copyFeedback, setCopyFeedback] = useState(false);
  useEffect(() => { setCurrentBranch(branchName); }, [branchName]);
  useEffect(() => {
    if (!branchName && workspacePath) {
      void fetchCurrentBranch(workspacePath).then((b) => { if (b) setCurrentBranch(b); });
    }
  }, [branchName, workspacePath]);

  const { pr, ci, isRefreshing, prLoading, refresh } = usePrData(workspacePath, currentBranch, sessionId);
  const rename = useRename(workspacePath, currentBranch, agentRunning, pr !== null, setCurrentBranch);

  const prStateInput = buildPrStateInput(pr, ci);
  const prAction = derivePrAction(prStateInput);
  const secondaryAction = deriveSecondaryAction(prAction, prStateInput);

  function handleActionClick(action: PrAction = prAction) {
    const ctx = { branchName: currentBranch, baseBranch: pr?.baseRefName ?? '',
      prNumber: pr?.number ?? 0, unresolvedCommentCount: pr?.unresolvedCommentCount ?? 0 };
    const prompt = getActionPrompt(action, ctx);
    if (prompt === null) { onArchive?.(); return; }
    if (sessionId) sendPtyData(prompt + '\r');
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(currentBranch);
      setCopyFeedback(true);
      setTimeout(() => setCopyFeedback(false), 1500);
    } catch { /* clipboard may not be available */ }
  }

  const barClass = deriveBarClass(pr);

  return (
    <div className={barClass}>
      <BranchSection workspacePath={workspacePath} currentBranch={currentBranch}
        agentRunning={agentRunning} pr={pr} rename={rename} copyFeedback={copyFeedback}
        onBranchSwitch={setCurrentBranch} onCopy={() => void handleCopy()} onBaseChanged={refresh} />
      {pr ? (
        <>
          <div className="bar-middle" aria-label="pull request">
            <a className="pr-link" href={pr.url} target="_blank" rel="noopener noreferrer"
              data-track="pr-top-bar.open-pr" aria-label={`PR #${pr.number}: ${pr.title}`}>
              PR #{pr.number}
              <svg className="pr-ext-icon" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                <path d="M1 9L9 1M9 1H4M9 1V6" stroke="currentColor" fill="none" strokeWidth="1.5" strokeLinecap="round" />
              </svg>
            </a>
          </div>
          <span className="diff-stats">
            <span className="diff-add">+{pr.additions}</span>
            <span className="diff-del">-{pr.deletions}</span>
          </span>
        </>
      ) : null}
      <PrActions isRefreshing={isRefreshing} prLoading={prLoading}
        prAction={prAction} secondaryAction={secondaryAction}
        onRefresh={refresh} onAction={handleActionClick} />
      {rename.renameWarning ? (
        <RenameWarningModal oldName={rename.renameWarning.oldName} newName={rename.renameWarning.newName}
          workspacePath={workspacePath} onClose={() => { rename.clearWarning(); refresh(); }} />
      ) : null}
    </div>
  );
}

// ── RenameWarningModal ────────────────────────────────────────────────────────

interface RenameWarningModalProps { oldName: string; newName: string; workspacePath: string; onClose: () => void; }

function RenameWarningModal({ oldName, newName, workspacePath, onClose }: RenameWarningModalProps) {
  const [loading, setLoading] = useState<'push' | 'cancel' | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const encodedPath = encodeURIComponent(workspacePath);
  const codeStyle = { background: 'var(--surface-hover)', padding: '2px 4px',
    fontFamily: 'var(--font-mono)', fontSize: 'var(--font-size-xs)' };

  async function handlePush() {
    setLoading('push'); setErrorMsg(null);
    try {
      const res = await fetch('/workspaces/push-branch?path=' + encodedPath, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ branch: newName, deleteOldBranch: oldName }),
      });
      const data = (await res.json()) as { success?: boolean; error?: string };
      if (data.success) onClose(); else setErrorMsg(data.error ?? 'Push failed');
    } catch { setErrorMsg('Push failed'); }
    finally { setLoading(null); }
  }

  async function handleCancel() {
    setLoading('cancel'); setErrorMsg(null);
    try {
      const res = await fetch('/workspaces/rename-branch?path=' + encodedPath, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ newName: oldName }),
      });
      const data = (await res.json()) as { success?: boolean; error?: string };
      if (data.success) onClose(); else setErrorMsg(data.error ?? 'Failed to undo rename');
    } catch { setErrorMsg('Failed to undo rename'); }
    finally { setLoading(null); }
  }

  return (
    <div className="rename-modal-overlay"
      style={{ position: 'fixed', inset: 0, display: 'flex', alignItems: 'center',
        justifyContent: 'center', background: 'rgba(0,0,0,0.6)', zIndex: 1000 }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)',
        padding: '24px', maxWidth: '420px', width: '100%', fontFamily: 'var(--font-mono)' }}>
        <h2 style={{ margin: '0 0 16px', fontSize: 'var(--font-size-sm)', color: 'var(--text)' }}>Branch Renamed</h2>
        <p style={{ margin: '0 0 8px', fontSize: 'var(--font-size-sm)', color: 'var(--text)', lineHeight: 1.5 }}>
          Branch renamed: <code style={codeStyle}>{oldName}</code>{' → '}<code style={codeStyle}>{newName}</code>
        </p>
        <p style={{ margin: '0 0 16px', fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', lineHeight: 1.5 }}>
          This PR&apos;s head branch no longer matches. Push the renamed branch to update GitHub?
        </p>
        {errorMsg ? <p style={{ margin: '0 0 12px', fontSize: 'var(--font-size-xs)', color: 'var(--status-error)' }}>{errorMsg}</p> : null}
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <TuiButton variant="primary" onClick={() => void handlePush()} disabled={loading !== null}>
            {loading === 'push' ? 'Pushing...' : 'Push'}
          </TuiButton>
          <TuiButton variant="ghost" onClick={onClose} disabled={loading !== null}>Ignore</TuiButton>
          <TuiButton variant="ghost" onClick={() => void handleCancel()} disabled={loading !== null}>
            {loading === 'cancel' ? 'Undoing...' : 'Cancel (undo rename)'}
          </TuiButton>
        </div>
      </div>
    </div>
  );
}

export default PrTopBar;

// frontend/src/components/PrTopBar.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { createQuery } from '@tanstack/svelte-query';
  import { fetchPrForBranchOrNull, fetchCiStatusOrNull, fetchCurrentBranch } from '../lib/api.js';
  import { sendPtyData } from '../lib/ws.js';
  import {
    derivePrAction,
    deriveSecondaryAction,
    getActionPrompt,
  } from '../lib/pr-state.js';
  import type { PrAction, StatusColor } from '../lib/pr-state.js';
  import type { PrInfo, CiStatus } from '../lib/types.js';
  import { getUi, toggleRightSidebarCollapsed } from '../lib/state/ui.svelte.js';
  import CipherText from './CipherText.svelte';
  import TuiButton from './TuiButton.svelte';
  import BranchSwitcher from './BranchSwitcher.svelte';
  import TargetBranchSwitcher from './TargetBranchSwitcher.svelte';
  import RenameWarningModal from './dialogs/RenameWarningModal.svelte';

  const ui = getUi();

  let {
    repoPath,
    branchName,
    sessionId,
    agentRunning = false,
    onArchive,
  }: {
    repoPath: string;
    branchName: string;
    sessionId: string | null;
    agentRunning?: boolean;
    onArchive?: () => void;
  } = $props();

  // currentBranch starts from the prop but can diverge when user switches locally.
  // Re-sync when the parent prop changes (e.g. workspace navigation).
  // svelte-ignore state_referenced_locally
  let currentBranch = $state(branchName);
  $effect(() => { currentBranch = branchName; });

  // If branchName is empty (repo sessions), detect the current branch from git
  $effect(() => {
    if (!branchName && repoPath) {
      fetchCurrentBranch(repoPath).then(branch => {
        if (branch) currentBranch = branch;
      });
    }
  });

  const prQuery = createQuery<PrInfo | null>(() => ({
    queryKey: ['pr', repoPath, currentBranch],
    queryFn: () => fetchPrForBranchOrNull(repoPath, currentBranch),
    staleTime: 60_000,
    refetchOnWindowFocus: true,
  }));

  const ciQuery = createQuery<CiStatus | null>(() => ({
    queryKey: ['ci-status', repoPath, currentBranch],
    queryFn: () => fetchCiStatusOrNull(repoPath, currentBranch),
    staleTime: 30_000,
    refetchOnWindowFocus: true,
    enabled: prQuery.data?.state === 'OPEN',
  }));

  // Refetch PR and CI data when session changes (e.g. workspace navigation).
  // untrack() prevents tracking prQuery/ciQuery stores — without it, the effect
  // re-triggers on every query state change (isFetching, data), creating an infinite loop.
  $effect(() => {
    if (sessionId) {
      untrack(() => {
        prQuery.refetch();
        ciQuery.refetch();
      });
    }
  });

  let pr = $derived(prQuery.data ?? null);
  let ci = $derived(ciQuery.data ?? null);

  let prStateInput = $derived({
    commitsAhead: pr ? 1 : 0,
    prState: pr ? (pr.isDraft ? 'DRAFT' : pr.state) : null as 'OPEN' | 'CLOSED' | 'MERGED' | 'DRAFT' | null,
    ciPassing: ci?.passing ?? 0,
    ciFailing: ci?.failing ?? 0,
    ciPending: ci?.pending ?? 0,
    ciTotal: ci?.total ?? 0,
    mergeable: pr?.mergeable ?? null,
    unresolvedCommentCount: pr?.unresolvedCommentCount ?? 0,
  });

  let prAction = $derived(derivePrAction(prStateInput));
  let secondaryAction = $derived(deriveSecondaryAction(prAction, prStateInput));

  let showAction = $derived(prAction.type !== 'none');

  function colorToVariant(color: StatusColor): 'primary' | 'ghost' | 'danger' | 'success' | 'info' {
    if (color === 'success') return 'success';
    if (color === 'error') return 'danger';
    if (color === 'accent') return 'primary';
    return 'ghost';
  }
  let isRefreshing = $derived(prQuery.isFetching || ciQuery.isFetching);

  function handleRefresh() {
    prQuery.refetch();
    ciQuery.refetch();
  }

  function handleActionClick(action: PrAction = prAction) {
    const ctx = {
      branchName: currentBranch,
      baseBranch: pr?.baseRefName ?? '',
      prNumber: pr?.number ?? 0,
      unresolvedCommentCount: pr?.unresolvedCommentCount ?? 0,
    };
    const prompt = getActionPrompt(action, ctx);
    if (prompt === null) {
      onArchive?.();
      return;
    }
    if (sessionId) {
      sendPtyData(prompt + '\r');
    }
  }

  function handleBranchSwitch(branch: string) {
    currentBranch = branch;
  }

  let copyFeedback = $state(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(currentBranch);
      copyFeedback = true;
      setTimeout(() => copyFeedback = false, 1500);
    } catch { /* clipboard may not be available */ }
  }

  // ── Inline rename ──────────────────────────────────
  let renaming = $state(false);
  let renameValue = $state('');
  let renameSubmitting = $state(false);
  let renameInputEl = $state<HTMLInputElement | null>(null);
  let renameWarning = $state<{ oldName: string; newName: string } | null>(null);

  function startRename() {
    if (agentRunning) return;
    renaming = true;
    renameValue = currentBranch;
    requestAnimationFrame(() => renameInputEl?.focus());
  }

  function cancelRename() {
    if (renameSubmitting) return;
    renaming = false;
    renameValue = '';
  }

  async function confirmRename() {
    const trimmed = renameValue.trim();
    if (!trimmed || trimmed === currentBranch) {
      cancelRename();
      return;
    }

    renameSubmitting = true;
    try {
      const res = await fetch('/workspaces/rename-branch?path=' + encodeURIComponent(repoPath), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ newName: trimmed }),
      });
      const data = await res.json() as { success?: boolean; oldName?: string; newName?: string; error?: string };
      if (data.success && data.oldName && data.newName) {
        const oldName = data.oldName;
        currentBranch = data.newName;
        renaming = false;
        renameValue = '';

        // If PR exists, show warning modal
        if (pr) {
          renameWarning = { oldName, newName: data.newName };
        }
      } else {
        // Show error and exit rename mode
        renaming = false;
        renameValue = '';
      }
    } catch {
      // Exit rename mode on error
      renaming = false;
      renameValue = '';
    } finally {
      renameSubmitting = false;
    }
  }

  function handleRenameKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      e.preventDefault();
      confirmRename();
    } else if (e.key === 'Escape') {
      cancelRename();
    }
  }
</script>

<div class="pr-top-bar" class:bar-merged={pr?.state === 'MERGED'} class:bar-conflicts={pr?.mergeable === 'CONFLICTING'}>
  <!-- Left section: branch switcher + target branch -->
  <div class="bar-left">
    {#if renaming}
      <div class="rename-input-wrap">
        <span class="branch-icon">⑂</span>
        <input
          bind:this={renameInputEl}
          type="text"
          class="rename-input"
          bind:value={renameValue}
          onkeydown={handleRenameKeydown}
          onblur={cancelRename}
        />
      </div>
    {:else}
      <div class="branch-with-actions">
        <BranchSwitcher
          {repoPath}
          currentWorktreePath={repoPath}
          currentBranch={currentBranch}
          disabled={agentRunning}
          onSwitch={handleBranchSwitch}
        />

        <!-- Hover-reveal icons — overlaid to the right of branch name, left of chevron -->
        <div class="hover-icons">
        <button
          class="hover-icon"
          onclick={handleCopy}
          title={copyFeedback ? 'Copied!' : 'Copy branch name'}
          aria-label="Copy branch name"
        >
          {#if copyFeedback}
            <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
              <path d="M3 8l3 3 7-7" stroke="currentColor" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          {:else}
            <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
              <rect x="5" y="5" width="9" height="9" rx="1.5" stroke="currentColor" fill="none" stroke-width="1.5"/>
              <path d="M3 11V3a1.5 1.5 0 011.5-1.5H11" stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round"/>
            </svg>
          {/if}
        </button>
        <button
          class="hover-icon"
          onclick={startRename}
          disabled={agentRunning}
          title={agentRunning ? 'Unavailable while agent is running' : 'Rename branch'}
          aria-label="Rename branch"
        >
          <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
            <path d="M11.5 1.5l3 3L5 14H2v-3L11.5 1.5z" stroke="currentColor" fill="none" stroke-width="1.5" stroke-linejoin="round"/>
          </svg>
        </button>
      </div>
      </div>
    {/if}

    {#if pr?.baseRefName}
      <span class="target-section">
        <span class="target-arrow" aria-hidden="true">
          <svg width="14" height="10" viewBox="0 0 14 10" aria-hidden="true">
            <path d="M1 5h10M8 2l3 3-3 3" stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </span>
        <TargetBranchSwitcher
          {repoPath}
          currentBase={pr.baseRefName}
          prNumber={pr.number}
          disabled={agentRunning}
          onBaseChanged={() => {
            prQuery.refetch();
          }}
        />
      </span>
    {/if}
  </div>

  <!-- Middle: PR link + diff stats -->
  {#if pr}
    <div class="bar-middle" aria-label="pull request">
      <a
        class="pr-link"
        href={pr.url}
        target="_blank"
        rel="noopener noreferrer"
        data-track="pr-top-bar.open-pr"
        aria-label="PR #{pr.number}: {pr.title}"
      >
        PR #{pr.number}
        <svg class="pr-ext-icon" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
          <path d="M1 9L9 1M9 1H4M9 1V6" stroke="currentColor" fill="none" stroke-width="1.5" stroke-linecap="round"/>
        </svg>
      </a>
    </div>
    <span class="diff-stats">
      <span class="diff-add">+{pr.additions}</span>
      <span class="diff-del">-{pr.deletions}</span>
    </span>
  {/if}

  <!-- Right: action buttons -->
  <div class="bar-right">
    <button
      class="refresh-btn"
      class:refreshing={isRefreshing}
      onclick={handleRefresh}
      disabled={isRefreshing}
      aria-label="Refresh PR data"
      title="Refresh PR data"
    >
      <svg width="12" height="12" viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <path d="M14 8A6 6 0 1 1 8 2" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>
        <path d="M8 0L14 2L12 4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
      </svg>
    </button>
    {#if prQuery.isLoading}
      <CipherText text="loading" loading={true} />
    {:else}
      {#if secondaryAction}
        <TuiButton
          variant="ghost"
          size="sm"
          data-track="pr-top-bar.secondary-action"
          onclick={() => handleActionClick(secondaryAction!)}
          aria-label={secondaryAction.label}
        >
          {secondaryAction.label}
        </TuiButton>
      {/if}
      {#if showAction}
        <TuiButton
          variant={colorToVariant(prAction.color)}
          size="sm"
          data-track="pr-top-bar.primary-action"
          onclick={() => handleActionClick()}
          disabled={prAction.type === 'checks-running'}
          aria-label={prAction.label}
        >
          {prAction.label}
        </TuiButton>
      {/if}
    {/if}
    <button
      class="sidebar-toggle-btn"
      onclick={toggleRightSidebarCollapsed}
      aria-label={ui.rightSidebarCollapsed ? 'Show file sidebar' : 'Hide file sidebar'}
      title={ui.rightSidebarCollapsed ? 'Show file sidebar' : 'Hide file sidebar'}
    >
      <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <rect x="1" y="2" width="14" height="12" stroke="currentColor" stroke-width="1.5" fill="none" stroke-linecap="square"/>
        <line x1="10" y1="2" x2="10" y2="14" stroke="currentColor" stroke-width="1.5" stroke-linecap="square"/>
      </svg>
    </button>
  </div>

  {#if renameWarning}
    <RenameWarningModal
      oldName={renameWarning.oldName}
      newName={renameWarning.newName}
      {repoPath}
      onClose={() => {
        renameWarning = null;
        prQuery.refetch();
      }}
    />
  {/if}
</div>

<style>
  .pr-top-bar {
    display: flex;
    align-items: center;
    height: 36px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
    padding: 0 8px;
    gap: 0;
    flex-shrink: 0;
    overflow: visible;
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
  }

  /* ── Left ─────────────────────────── */
  .bar-left {
    display: flex;
    align-items: center;
    gap: 4px;
    flex: 1;
    min-width: 0;
    overflow: hidden;
    padding-right: 8px;
    border-right: 1px solid var(--border);
    align-self: stretch;
  }

  .target-section {
    display: flex;
    align-items: center;
    flex-shrink: 0;
  }

  .target-arrow {
    display: flex;
    align-items: center;
    color: var(--text-muted);
    flex-shrink: 0;
    padding: 0 2px;
  }

  /* ── Middle ────────────────────────── */
  .bar-middle {
    display: flex;
    align-items: center;
    padding: 0 12px;
    flex-shrink: 0;
    white-space: nowrap;
  }

  .pr-link {
    display: flex;
    align-items: center;
    gap: 4px;
    color: var(--text-muted);
    text-decoration: none;
    font-size: var(--font-size-xs);
    transition: color 0.12s;
  }

  .pr-link:hover {
    color: var(--accent);
  }

  .pr-ext-icon {
    flex-shrink: 0;
    opacity: 0.6;
  }

  /* ── Right ─────────────────────────── */
  .bar-right {
    display: flex;
    align-items: center;
    padding-left: 8px;
    gap: 8px;
    flex-shrink: 0;
  }

  .sidebar-toggle-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 22px;
    height: 22px;
    border-radius: 0;
    border: none;
    background: transparent;
    color: var(--text-muted);
    cursor: pointer;
    padding: 0;
    transition: color 0.12s, background 0.12s;
  }

  .sidebar-toggle-btn:hover {
    color: var(--text);
    background: var(--border);
  }

  .refresh-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 22px;
    height: 22px;
    border-radius: 0;
    border: none;
    background: transparent;
    color: var(--text-muted);
    cursor: pointer;
    padding: 0;
    transition: color 0.12s, background 0.12s;
  }

  .refresh-btn:hover:not(:disabled) {
    color: var(--text);
    background: var(--border);
  }

  .refresh-btn:disabled {
    cursor: default;
  }

  .refresh-btn.refreshing svg {
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }

  .bar-merged {
    background: color-mix(in srgb, var(--status-merged) 8%, var(--surface));
  }

  .bar-conflicts {
    background: color-mix(in srgb, var(--status-error) 8%, var(--surface));
  }

  .diff-stats {
    display: flex;
    align-items: center;
    gap: 8px;
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    padding: 0 8px;
    flex-shrink: 0;
  }

  .diff-add { color: var(--status-success); }
  .diff-del { color: var(--status-error); }

  /* ── Rename ──────────────────────────── */
  .rename-input-wrap {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 2px 4px;
  }

  .rename-input {
    background: var(--bg);
    border: 1px solid var(--accent);
    border-radius: 0;
    color: var(--text);
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    padding: 2px 8px;
    outline: none;
    min-width: 120px;
    max-width: 250px;
  }

  /* Hover-reveal icons */
  .branch-with-actions {
    position: relative;
    display: flex;
    align-items: center;
  }

  .hover-icons {
    position: absolute;
    right: 24px; /* left of the chevron */
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    align-items: center;
    gap: 2px;
    opacity: 0;
    transition: opacity 0.15s;
    pointer-events: none;
    z-index: 1;
    background: var(--bg);
    padding-left: 4px;
  }

  .branch-with-actions:hover .hover-icons {
    opacity: 1;
    pointer-events: auto;
  }

  .hover-icon {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 22px;
    height: 22px;
    border-radius: 0;
    border: none;
    background: transparent;
    color: var(--text-muted);
    cursor: pointer;
    padding: 0;
    transition: color 0.12s, background 0.12s;
  }

  .hover-icon:hover:not(:disabled) {
    color: var(--text);
    background: var(--surface-hover);
  }

  .hover-icon:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .branch-icon {
    color: var(--text-muted);
    font-size: var(--font-size-base);
    flex-shrink: 0;
  }

  /* ── Mobile ─────────────────────────── */
  @media (max-width: 600px) {
    .hover-icons {
      opacity: 1;
    }

    .target-section,
    .bar-middle,
    .diff-stats {
      display: none;
    }

    .bar-left {
      border-right: none;
      padding-right: 4px;
    }
  }
</style>
