// frontend/src/components/RepoDashboard.tsx
import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { fetchDashboard } from '../lib/api.js';
import { derivePrAction, buildPrStateInput } from '../lib/pr-state.js';
import { formatRelativeTime } from '../lib/utils.js';
import type { PullRequest, ActivityEntry, DashboardData } from '../lib/types.js';
import { useSessionsStore } from '../lib/stores/sessions.js';
import { useTelemetryStore } from '../lib/stores/telemetry.js';
import { derivePrDotStatus } from '../lib/pr-status.js';
import StatusDot from './StatusDot.js';
import { TuiButton } from './TuiButton.js';
import { TuiProgress } from './TuiProgress.js';
import './RepoDashboard.css';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface RepoDashboardProps {
  repoPath: string;
  workspaceName: string;
  creatingWorktree?: boolean;
  onNewSession: () => void;
  onNewWorktree: () => void;
  onFixConflicts: (pr: PullRequest) => void;
  onPrAction: (pr: PullRequest) => void;
  onOpenPrSession: (pr: PullRequest) => void;
  /** Injected renderer for DataTable (Svelte compat) */
  renderDataTable?: (props: DataTableRenderProps) => React.ReactNode;
  /** Injected renderer for TuiButton */
  renderButton?: (props: TuiButtonRenderProps) => React.ReactNode;
  /** Injected renderer for TuiProgress */
  renderProgress?: (props: { variant: string; value: number; width: number }) => React.ReactNode;
}

export interface DataTableRenderProps {
  rows: PullRequest[];
  sortBy: string;
  sortDir: 'asc' | 'desc';
  loading: boolean;
  error?: string;
  emptyMessage: string;
  filteredEmptyMessage: string;
  hasActiveFilters: boolean;
  onClearFilters: () => void;
  onSort: (col: string) => void;
  onRowAction: (pr: PullRequest) => void;
  renderRow: (pr: PullRequest) => React.ReactNode;
  renderMobileCard: (pr: PullRequest) => React.ReactNode;
}

export interface TuiButtonRenderProps {
  variant: string;
  size?: string;
  disabled?: boolean;
  onClick?: () => void;
  href?: string;
  target?: string;
  rel?: string;
  title?: string;
  children: React.ReactNode;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function compactCount(value: number): string {
  if (value < 1000) return String(Math.round(value));
  if (value < 1_000_000) return `${(value / 1000).toFixed(value >= 10_000 ? 0 : 1)}k`;
  return `${(value / 1_000_000).toFixed(value >= 10_000_000 ? 0 : 1)}M`;
}

function formatResetAt(value: string | null | undefined): string {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  const now = new Date();
  const sameDay =
    date.getFullYear() === now.getFullYear() &&
    date.getMonth() === now.getMonth() &&
    date.getDate() === now.getDate();
  if (sameDay) return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false });
  return date.toLocaleDateString([], { month: 'short', day: 'numeric' });
}

function prRoleLabel(pr: PullRequest): string {
  return pr.role === 'author' ? 'by you' : 'review requested';
}

function activityBranches(entry: ActivityEntry): string {
  if (!entry.branches || entry.branches.length === 0) return '';
  return '(' + entry.branches.join(', ') + ')';
}

function sortPrs(prs: PullRequest[], sortBy: string, sortDir: 'asc' | 'desc'): PullRequest[] {
  return [...prs].sort((a, b) => {
    if (sortBy === 'title') return sortDir === 'asc' ? a.title.localeCompare(b.title) : b.title.localeCompare(a.title);
    if (sortBy === 'role') {
      const roleOrder: Record<string, number> = { reviewer: 0, author: 1 };
      return sortDir === 'asc' ? (roleOrder[a.role] ?? 1) - (roleOrder[b.role] ?? 1) : (roleOrder[b.role] ?? 1) - (roleOrder[a.role] ?? 1);
    }
    return sortDir === 'asc' ? a.updatedAt.localeCompare(b.updatedAt) : b.updatedAt.localeCompare(a.updatedAt);
  });
}

// ── Sub-components ─────────────────────────────────────────────────────────────

interface UsageSectionProps {
  repoSessions: import('../lib/types.js').SessionSummary[];
  repoPath: string;
}

function UsageSection({ repoSessions }: UsageSectionProps) {
  const summarize = useTelemetryStore((s) => s.summarizeSessionSetTelemetry);
  const accountTelemetry = useTelemetryStore((s) => s.accountTelemetry);
  const repoTelemetry = useMemo(() => summarize(repoSessions), [summarize, repoSessions]);

  const sessionCoveragePercent = repoTelemetry.totalSessions > 0
    ? Math.round((repoTelemetry.trackedSessions / repoTelemetry.totalSessions) * 100)
    : 0;

  const contextPercent = repoTelemetry.averageContextPercent !== null
    ? Math.max(0, Math.min(100, Math.round(repoTelemetry.averageContextPercent)))
    : -1;

  return (
    <section className="dashboard-section">
      <div className="section-heading">usage this window</div>
      <div className="usage-panel">
        <div className="usage-row">
          <span className="usage-label">sessions tracked</span>
          <span className="usage-bar">
            <TuiProgress variant="bar" value={sessionCoveragePercent} width={10} />
          </span>
          <span className="usage-value">
            {repoTelemetry.trackedSessions} of {repoTelemetry.totalSessions}
            {repoTelemetry.totalSessions > repoTelemetry.trackedSessions && (
              <> ({repoTelemetry.totalSessions - repoTelemetry.trackedSessions} outside relay)</>
            )}
          </span>
        </div>
        <div className="usage-row">
          <span className="usage-label">relay tokens</span>
          <span className="usage-value">
            ↓{compactCount(repoTelemetry.totalInputTokens)} ↑{compactCount(repoTelemetry.totalOutputTokens)}
          </span>
          <span className="usage-meta">cache: {compactCount(repoTelemetry.totalCacheRead)} read</span>
        </div>
        <div className="usage-row">
          <span className="usage-label">context pressure</span>
          <span className="usage-bar">
            <TuiProgress variant="bar" value={contextPercent >= 0 ? contextPercent : 0} width={10} />
          </span>
          <span className="usage-value">
            {repoTelemetry.averageContextPercent !== null ? `${Math.round(repoTelemetry.averageContextPercent)}% avg` : '—'}
            {repoTelemetry.maxContextPercent !== null && (
              <span className="usage-meta"> peak {Math.round(repoTelemetry.maxContextPercent)}%</span>
            )}
          </span>
        </div>
        {accountTelemetry && (
          <>
            <div className="usage-divider" />
            <div className="usage-row">
              <span className="usage-label">5h limit</span>
              <span className="usage-bar">
                <TuiProgress variant="bar" value={Math.max(0, Math.min(100, accountTelemetry.fiveHourUsedPercent >= 0 ? accountTelemetry.fiveHourUsedPercent : 0))} width={10} />
              </span>
              <span className="usage-value">
                {accountTelemetry.fiveHourUsedPercent >= 0 ? `${Math.round(accountTelemetry.fiveHourUsedPercent)}% used` : '—'}
              </span>
              <span className="usage-meta">resets {formatResetAt(accountTelemetry.fiveHourResetsAt)}</span>
            </div>
            <div className="usage-row">
              <span className="usage-label">7d limit</span>
              <span className="usage-bar">
                <TuiProgress variant="bar" value={Math.max(0, Math.min(100, accountTelemetry.sevenDayUsedPercent >= 0 ? accountTelemetry.sevenDayUsedPercent : 0))} width={10} />
              </span>
              <span className="usage-value">
                {accountTelemetry.sevenDayUsedPercent >= 0 ? `${Math.round(accountTelemetry.sevenDayUsedPercent)}% used` : '—'}
              </span>
              <span className="usage-meta">resets {formatResetAt(accountTelemetry.sevenDayResetsAt)}</span>
            </div>
          </>
        )}
      </div>
    </section>
  );
}

interface ActivitySectionProps {
  data: DashboardData | undefined;
  isLoading: boolean;
}

function ActivitySection({ data, isLoading }: ActivitySectionProps) {
  return (
    <section className="dashboard-section dashboard-section--scroll">
      <div className="section-heading">recent activity</div>
      {isLoading ? (
        <div className="scroll-container">
          <div className="activity-list">
            {[1, 2, 3].map((i) => (
              <div key={i} className="activity-row skeleton">
                <div className="skeleton-line skeleton-activity" />
              </div>
            ))}
          </div>
        </div>
      ) : data && data.activity.length === 0 ? (
        <div className="section-message">No recent commits (24h)</div>
      ) : data ? (
        <div className="scroll-container">
          <div className="activity-list">
            {data.activity.map((entry: ActivityEntry) => (
              <div key={entry.hash} className="activity-row">
                <span className="commit-hash">{entry.shortHash}</span>
                <span className="commit-msg">{entry.message}</span>
                {entry.branches.length > 0 && (
                  <span className="commit-branch">{activityBranches(entry)}</span>
                )}
                <span className="commit-time">{entry.timeAgo}</span>
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </section>
  );
}

interface PrRowProps {
  pr: PullRequest;
  onOpenPrSession: (pr: PullRequest) => void;
  onPrAction: (pr: PullRequest) => void;
}

function PrRow({ pr, onOpenPrSession, onPrAction }: PrRowProps) {
  const action = derivePrAction(buildPrStateInput(pr));
  return (
    <>
      <div className="pr-cell pr-cell--status" style={{ width: 36, flex: 'none' }}>
        <StatusDot status={derivePrDotStatus(pr)} />
      </div>
      <div className="pr-cell pr-cell--title" style={{ flex: 1 }}>
        <a className="pr-title-link" href={pr.url} target="_blank" rel="noopener noreferrer">{pr.title}</a>
        <div className="pr-row-meta">
          <span className="pr-num">#{pr.number}</span>
          <span className="pr-sep">&middot;</span>
          <span className="pr-role">{prRoleLabel(pr)}</span>
          <span className="pr-sep">&middot;</span>
          <span className="pr-time">{formatRelativeTime(pr.updatedAt)}</span>
        </div>
      </div>
      <div className="pr-cell pr-cell--role" style={{ width: 60, flex: 'none' }}>
        <span className="pr-role-text">{pr.role === 'author' ? 'Author' : 'Review'}</span>
      </div>
      <div className="pr-cell pr-cell--age" style={{ width: 50, flex: 'none' }}>
        <span className="pr-age-text">{formatRelativeTime(pr.updatedAt)}</span>
      </div>
      <div className="pr-cell pr-cell--action" style={{ width: 160, flex: 'none' }}>
        <div className="pr-row-actions">
          <TuiButton variant="ghost" size="icon" onClick={() => onOpenPrSession(pr)} title="Open session on this branch">+</TuiButton>
          {action.type !== 'none' && action.label && (
            <TuiButton variant="ghost" size="sm" onClick={() => onPrAction(pr)} title={action.label} disabled={action.type === 'checks-running'}>
              {action.label}
            </TuiButton>
          )}
        </div>
      </div>
    </>
  );
}

// ── Helpers ─────────────────────────────────────────────────────────────────────

interface PrListBodyProps {
  data: DashboardData | undefined;
  isLoading: boolean;
  isError: boolean;
  workspaceName: string;
  searchQuery: string;
  processedPrs: PullRequest[];
  onSearchChange: (q: string) => void;
  onOpenPrSession: (pr: PullRequest) => void;
  onPrAction: (pr: PullRequest) => void;
}

function PrListBody({ data, isLoading, isError, workspaceName, searchQuery, processedPrs, onSearchChange, onOpenPrSession, onPrAction }: PrListBodyProps) {
  if (data && !data.hasGhCli) {
    return (
      <div className="section-message info">
        Install GitHub CLI for PR tracking —{' '}
        <a href="https://cli.github.com" target="_blank" rel="noopener noreferrer">cli.github.com</a>
      </div>
    );
  }
  if (isLoading) return <div className="section-message">Loading...</div>;
  if (isError) return <div className="section-message">Could not load pull requests.</div>;
  if (processedPrs.length === 0 && !searchQuery) return <div className="section-message">No open PRs for {workspaceName}.</div>;
  return (
    <>
      <input
        type="search"
        placeholder="filter PRs..."
        value={searchQuery}
        onChange={(e) => onSearchChange(e.target.value)}
        style={{ marginBottom: 8, fontFamily: 'var(--font-mono)', fontSize: 'var(--font-size-xs)', background: 'transparent', border: '1px solid var(--border)', color: 'var(--text)', padding: '2px 8px' }}
      />
      {processedPrs.length === 0 ? (
        <div className="section-message">No results for &apos;{searchQuery}&apos;.</div>
      ) : (
        <div>
          {processedPrs.map((pr) => (
            <div key={pr.number} style={{ display: 'flex', alignItems: 'center', borderBottom: '1px solid var(--border)' }}>
              <PrRow pr={pr} onOpenPrSession={onOpenPrSession} onPrAction={onPrAction} />
            </div>
          ))}
        </div>
      )}
    </>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────

export function RepoDashboard({
  repoPath, workspaceName, creatingWorktree = false,
  onNewSession, onNewWorktree, onFixConflicts: _onFixConflicts, onPrAction, onOpenPrSession,
}: RepoDashboardProps) {
  const sessions = useSessionsStore((s) => s.sessions);
  const repoSessions = useMemo(() => sessions.filter((s) => s.repoPath === repoPath), [sessions, repoPath]);

  const [searchQuery, setSearchQuery] = useState('');
  const sortBy = 'age';
  const sortDir: 'asc' | 'desc' = 'desc';

  const { data, isLoading, isError } = useQuery<DashboardData>({
    queryKey: ['dashboard', repoPath],
    queryFn: () => fetchDashboard(repoPath),
    staleTime: 60_000,
    refetchOnWindowFocus: true,
  });

  const processedPrs = useMemo((): PullRequest[] => {
    if (!data) return [];
    let prs = data.prs;
    const q = searchQuery.toLowerCase().trim();
    if (q) {
      prs = prs.filter((pr) =>
        pr.title.toLowerCase().includes(q) ||
        String(pr.number).includes(q) ||
        pr.headRefName.toLowerCase().includes(q)
      );
    }
    return sortPrs(prs, sortBy, sortDir);
  }, [data, searchQuery, sortBy, sortDir]);

  return (
    <div className="repo-dashboard">
      {data && !data.isGitRepo ? (
        <div className="non-git-notice">
          <span className="non-git-msg">Not a git repository</span>
        </div>
      ) : (
        <>
          <UsageSection repoSessions={repoSessions} repoPath={repoPath} />
          <section className="dashboard-section dashboard-section--scroll">
            <div className="section-heading">open pull requests</div>
            <PrListBody
              data={data} isLoading={isLoading} isError={isError}
              workspaceName={workspaceName} searchQuery={searchQuery} processedPrs={processedPrs}
              onSearchChange={setSearchQuery} onOpenPrSession={onOpenPrSession} onPrAction={onPrAction}
            />
          </section>
          <ActivitySection data={data} isLoading={isLoading} />
        </>
      )}
      <div className="cta-row">
        <TuiButton variant="primary" onClick={onNewSession}>+ start session</TuiButton>
        {(!data || data.isGitRepo) && (
          <TuiButton variant="ghost" onClick={onNewWorktree} disabled={creatingWorktree}>
            {creatingWorktree ? 'creating...' : '+ new worktree'}
          </TuiButton>
        )}
      </div>
    </div>
  );
}

export default RepoDashboard;

// frontend/src/components/RepoDashboard.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query';
  import { fetchDashboard } from '../lib/api.js';
  import { derivePrAction, buildPrStateInput } from '../lib/pr-state.js';
  import { formatRelativeTime } from '../lib/utils.js';
  import type { PullRequest, ActivityEntry, DashboardData } from '../lib/types.js';
  import { getSessionState } from '../lib/state/sessions.svelte.js';
  import { getTelemetryState, summarizeSessionSetTelemetry } from '../lib/state/telemetry.svelte.js';
  import DataTable from './DataTable.svelte';
  import type { Column } from './DataTable.svelte';
  import StatusDot from './StatusDot.svelte';
  import TuiButton from './TuiButton.svelte';
  import TuiProgress from './TuiProgress.svelte';
  import { derivePrDotStatus } from '../lib/pr-status.js';

  let {
    repoPath,
    workspaceName,
    creatingWorktree = false,
    onNewSession,
    onNewWorktree,
    onFixConflicts,
    onPrAction,
    onOpenPrSession,
  }: {
    repoPath: string;
    workspaceName: string;
    creatingWorktree?: boolean;
    onNewSession: () => void;
    onNewWorktree: () => void;
    onFixConflicts: (pr: PullRequest) => void;
    onPrAction: (pr: PullRequest) => void;
    onOpenPrSession: (pr: PullRequest) => void;
  } = $props();

  const sessionState = getSessionState();
  const telemetryState = getTelemetryState();

  const dashQuery = createQuery<DashboardData>(() => ({
    queryKey: ['dashboard', repoPath],
    queryFn: () => fetchDashboard(repoPath),
    staleTime: 60_000,
    refetchOnWindowFocus: true,
  }));

  let data = $derived(dashQuery.data);
  let isLoading = $derived(dashQuery.isLoading);
  let isError = $derived(dashQuery.isError);
  let repoSessions = $derived(sessionState.sessions.filter((session) => session.repoPath === repoPath));
  let repoTelemetry = $derived(summarizeSessionSetTelemetry(repoSessions));
  let accountTelemetry = $derived(telemetryState.accountTelemetry);

  const prColumns: Column[] = [
    { key: 'status', label: 'St', sortable: false, width: '36px' },
    { key: 'title', label: 'Title', sortable: true },
    { key: 'role', label: 'Role', sortable: true, width: '60px' },
    { key: 'age', label: 'Age', sortable: true, width: '50px' },
    { key: 'action', label: '', sortable: false, width: '160px' },
  ];

  function prActionForRow(pr: PullRequest) {
    return derivePrAction(buildPrStateInput(pr));
  }

  function prRoleLabel(pr: PullRequest): string {
    return pr.role === 'author' ? 'by you' : 'review requested';
  }

  function activityBranches(entry: ActivityEntry): string {
    if (!entry.branches || entry.branches.length === 0) return '';
    return '(' + entry.branches.join(', ') + ')';
  }

  function compactCount(value: number): string {
    if (value < 1000) return String(Math.round(value));
    if (value < 1_000_000) return `${(value / 1000).toFixed(value >= 10_000 ? 0 : 1)}k`;
    return `${(value / 1_000_000).toFixed(value >= 10_000_000 ? 0 : 1)}M`;
  }

  function formatResetAt(value: string | null | undefined): string {
    if (!value) return '—';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return '—';
    const now = new Date();
    const sameDay =
      date.getFullYear() === now.getFullYear() &&
      date.getMonth() === now.getMonth() &&
      date.getDate() === now.getDate();
    if (sameDay) {
      return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false });
    }
    return date.toLocaleDateString([], { month: 'short', day: 'numeric' });
  }

  let sessionCoveragePercent = $derived(
    repoTelemetry.totalSessions > 0
      ? Math.round((repoTelemetry.trackedSessions / repoTelemetry.totalSessions) * 100)
      : 0
  );

  let contextPercent = $derived(
    repoTelemetry.averageContextPercent !== null
      ? Math.max(0, Math.min(100, Math.round(repoTelemetry.averageContextPercent)))
      : -1
  );

  let searchQuery = $state('');
  let sortBy = $state('age');
  let sortDir = $state<'asc' | 'desc'>('desc');

  let processedPrs = $derived.by((): PullRequest[] => {
    if (!data) return [];
    let prs = data.prs;
    const q = searchQuery.toLowerCase().trim();
    if (q) {
      prs = prs.filter(pr =>
        pr.title.toLowerCase().includes(q) ||
        String(pr.number).includes(q) ||
        pr.headRefName.toLowerCase().includes(q)
      );
    }
    prs = [...prs].sort((a, b) => {
      if (sortBy === 'title') return sortDir === 'asc' ? a.title.localeCompare(b.title) : b.title.localeCompare(a.title);
      if (sortBy === 'role') {
        const roleOrder: Record<string, number> = { reviewer: 0, author: 1 };
        return sortDir === 'asc' ? (roleOrder[a.role] ?? 1) - (roleOrder[b.role] ?? 1) : (roleOrder[b.role] ?? 1) - (roleOrder[a.role] ?? 1);
      }
      // age = updatedAt
      return sortDir === 'asc' ? a.updatedAt.localeCompare(b.updatedAt) : b.updatedAt.localeCompare(a.updatedAt);
    });
    return prs;
  });
</script>

<div class="repo-dashboard">
  {#if data && !data.isGitRepo}
    <!-- Non-git repo: simplified view, just CTA buttons -->
    <div class="non-git-notice">
      <span class="non-git-msg">Not a git repository</span>
    </div>
  {:else}
    <section class="dashboard-section">
      <div class="section-heading">usage this window</div>
      <div class="usage-panel">
        <div class="usage-row">
          <span class="usage-label">sessions tracked</span>
          <span class="usage-bar">
            <TuiProgress variant="bar" value={sessionCoveragePercent} width={14} />
          </span>
          <span class="usage-value">
            {repoTelemetry.trackedSessions} of {repoTelemetry.totalSessions}
            {#if repoTelemetry.totalSessions > repoTelemetry.trackedSessions}
              ({repoTelemetry.totalSessions - repoTelemetry.trackedSessions} outside relay)
            {/if}
          </span>
        </div>

        <div class="usage-row">
          <span class="usage-label">relay tokens</span>
          <span class="usage-value">
            ↓{compactCount(repoTelemetry.totalInputTokens)} ↑{compactCount(repoTelemetry.totalOutputTokens)}
          </span>
          <span class="usage-meta">
            cache: {compactCount(repoTelemetry.totalCacheRead)} read
          </span>
        </div>

        <div class="usage-row">
          <span class="usage-label">context pressure</span>
          <span class="usage-bar">
            <TuiProgress variant="bar" value={contextPercent >= 0 ? contextPercent : 0} width={14} />
          </span>
          <span class="usage-value">
            {repoTelemetry.averageContextPercent !== null ? `${Math.round(repoTelemetry.averageContextPercent)}% avg` : '—'}
            {#if repoTelemetry.maxContextPercent !== null}
              <span class="usage-meta">peak {Math.round(repoTelemetry.maxContextPercent)}%</span>
            {/if}
          </span>
        </div>

        {#if accountTelemetry}
          <div class="usage-divider"></div>
          <div class="usage-row">
            <span class="usage-label">5h limit</span>
            <span class="usage-bar">
              <TuiProgress variant="bar" value={Math.max(0, Math.min(100, accountTelemetry.fiveHourUsedPercent >= 0 ? accountTelemetry.fiveHourUsedPercent : 0))} width={14} />
            </span>
            <span class="usage-value">
              {accountTelemetry.fiveHourUsedPercent >= 0 ? `${Math.round(accountTelemetry.fiveHourUsedPercent)}% used` : '—'}
            </span>
            <span class="usage-meta">resets {formatResetAt(accountTelemetry.fiveHourResetsAt)}</span>
          </div>

          <div class="usage-row">
            <span class="usage-label">7d limit</span>
            <span class="usage-bar">
              <TuiProgress variant="bar" value={Math.max(0, Math.min(100, accountTelemetry.sevenDayUsedPercent >= 0 ? accountTelemetry.sevenDayUsedPercent : 0))} width={14} />
            </span>
            <span class="usage-value">
              {accountTelemetry.sevenDayUsedPercent >= 0 ? `${Math.round(accountTelemetry.sevenDayUsedPercent)}% used` : '—'}
            </span>
            <span class="usage-meta">resets {formatResetAt(accountTelemetry.sevenDayResetsAt)}</span>
          </div>
        {/if}
      </div>
    </section>

    <!-- OPEN PULL REQUESTS section -->
    <section class="dashboard-section dashboard-section--scroll">
      <div class="section-heading">open pull requests</div>

      {#if data && !data.hasGhCli}
        <div class="section-message info">
          Install GitHub CLI for PR tracking —
          <a href="https://cli.github.com" target="_blank" rel="noopener noreferrer">cli.github.com</a>
        </div>
      {:else}
        {#snippet prActionPills(pr: PullRequest, action: ReturnType<typeof prActionForRow>)}
          <button
            class="pr-session-btn"
            title="Open session on this branch"
            onclick={() => onOpenPrSession(pr)}
          >+</button>
          {#if action.type === 'merge-pr'}
            <TuiButton
              variant="success"
              size="sm"
              href={pr.url}
              target="_blank"
              rel="noopener noreferrer"
              title="Ready to merge on GitHub"
            >
              {action.label}
            </TuiButton>
          {:else if action.type !== 'none' && action.label}
            <TuiButton
              variant={action.color === 'success' ? 'success' : action.color === 'error' ? 'danger' : action.color === 'info' ? 'info' : action.color === 'accent' ? 'primary' : 'ghost'}
              size="sm"
              title={action.label}
              disabled={action.type === 'checks-running'}
              onclick={() => onPrAction(pr)}
            >
              {action.label}
            </TuiButton>
          {/if}
        {/snippet}
        <DataTable
          columns={prColumns}
          rows={processedPrs}
          {sortBy}
          {sortDir}
          onSort={(col) => {
            if (col === sortBy) sortDir = sortDir === 'asc' ? 'desc' : 'asc';
            else { sortBy = col; sortDir = 'asc'; }
          }}
          loading={isLoading}
          error={isError ? 'Could not load pull requests.' : undefined}
          emptyMessage={`No open PRs for ${workspaceName}.`}
          filteredEmptyMessage={`No results for '${searchQuery}'.`}
          hasActiveFilters={searchQuery.length > 0}
          onClearFilters={() => searchQuery = ''}
          onRowAction={(pr) => onOpenPrSession?.(pr)}
        >
          {#snippet row(pr, _index)}
            {@const action = prActionForRow(pr)}
            <div class="pr-cell pr-cell--status" style:width="36px" style:flex="none">
              <StatusDot status={derivePrDotStatus(pr)} />
            </div>
            <div class="pr-cell pr-cell--title" style:flex="1">
              <a class="pr-title-link" href={pr.url} target="_blank" rel="noopener noreferrer">
                {pr.title}
              </a>
              <div class="pr-row-meta">
                <span class="pr-num">#{pr.number}</span>
                <span class="pr-sep">&middot;</span>
                <span class="pr-role">{prRoleLabel(pr)}</span>
                <span class="pr-sep">&middot;</span>
                <span class="pr-time">{formatRelativeTime(pr.updatedAt)}</span>
              </div>
            </div>
            <div class="pr-cell pr-cell--role" style:width="60px" style:flex="none">
              <span class="pr-role-text">{pr.role === 'author' ? 'Author' : 'Review'}</span>
            </div>
            <div class="pr-cell pr-cell--age" style:width="50px" style:flex="none">
              <span class="pr-age-text">{formatRelativeTime(pr.updatedAt)}</span>
            </div>
            <div class="pr-cell pr-cell--action" style:width="160px" style:flex="none">
              <div class="pr-row-actions">
                {@render prActionPills(pr, action)}
              </div>
            </div>
          {/snippet}

          {#snippet mobileCard(pr, _index)}
            {@const action = prActionForRow(pr)}
            <div class="mobile-pr-card">
              <div class="mobile-pr-top">
                <StatusDot status={derivePrDotStatus(pr)} />
                <a class="pr-title-link" href={pr.url} target="_blank" rel="noopener noreferrer">
                  {pr.title}
                </a>
              </div>
              <div class="pr-row-meta">
                <span class="pr-num">#{pr.number}</span>
                <span class="pr-sep">&middot;</span>
                <span class="pr-role">{prRoleLabel(pr)}</span>
                <span class="pr-sep">&middot;</span>
                <span class="pr-time">{formatRelativeTime(pr.updatedAt)}</span>
              </div>
              <div class="pr-row-actions mobile-pr-actions">
                {@render prActionPills(pr, action)}
              </div>
            </div>
          {/snippet}
        </DataTable>
      {/if}
    </section>

    <!-- RECENT ACTIVITY section -->
    <section class="dashboard-section dashboard-section--scroll">
      <div class="section-heading">recent activity</div>

      {#if isLoading}
        <div class="scroll-container">
          <div class="activity-list">
            {#each [1, 2, 3] as _ (_)}
              <div class="activity-row skeleton">
                <div class="skeleton-line skeleton-activity"></div>
              </div>
            {/each}
          </div>
        </div>
      {:else if data && data.activity.length === 0}
        <div class="section-message">No recent commits (24h)</div>
      {:else if data}
        <div class="scroll-container">
          <div class="activity-list">
            {#each data.activity as entry (entry.hash)}
              <div class="activity-row">
                <span class="commit-hash">{entry.shortHash}</span>
                <span class="commit-msg">{entry.message}</span>
                {#if entry.branches.length > 0}
                  <span class="commit-branch">{activityBranches(entry)}</span>
                {/if}
                <span class="commit-time">{entry.timeAgo}</span>
              </div>
            {/each}
          </div>
        </div>
      {/if}
    </section>
  {/if}

  <!-- CTA buttons — always shown -->
  <div class="cta-row">
    <TuiButton variant="primary" onclick={onNewSession}>+ Start Session</TuiButton>
    {#if !data || data.isGitRepo}
      <TuiButton variant="primary" onclick={onNewWorktree} disabled={creatingWorktree}>
        {creatingWorktree ? 'Creating...' : '+ New Worktree'}
      </TuiButton>
    {/if}
  </div>
</div>

<style>
  .repo-dashboard {
    display: flex;
    flex-direction: column;
    gap: 20px;
    padding: 20px;
    background: var(--bg);
    min-height: 0;
    max-width: none;
    overflow: hidden;
    flex: 1;
  }

  /* -- Section -- */
  .dashboard-section {
    display: flex;
    flex-direction: column;
    gap: 8px;
    flex-shrink: 0;
  }

  .dashboard-section--scroll {
    flex: 1;
    min-height: 120px;
    overflow: hidden;
  }

  /* -- Scroll container with gradient fades (activity section) -- */
  .scroll-container {
    position: relative;
    flex: 1;
    min-height: 0;
    overflow-y: auto;
    overflow-x: hidden;
  }

  .dashboard-section--scroll {
    position: relative;
  }

  .dashboard-section--scroll::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 32px;
    background: linear-gradient(to bottom, transparent, var(--bg));
    pointer-events: none;
    z-index: 1;
  }

  .section-heading {
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    letter-spacing: 0.08em;
    color: var(--text-muted);
    padding-bottom: 6px;
    border-bottom: 1px solid var(--border);
  }

  .section-message {
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    color: var(--text-muted);
    padding: 8px 0;
  }

  .section-message.info a {
    color: var(--accent);
    text-decoration: none;
  }

  .section-message.info a:hover {
    text-decoration: underline;
  }

  /* -- PR cell layout (DataTable row) -- */
  .pr-cell {
    display: flex;
    align-items: center;
    padding: 8px 8px;
    min-width: 0;
  }

  .pr-cell--status {
    justify-content: center;
  }

  .pr-cell--title {
    flex-direction: column;
    align-items: flex-start;
    gap: 4px;
  }

  .pr-cell--role,
  .pr-cell--age {
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--text-muted);
  }

  .pr-cell--action {
    justify-content: flex-end;
  }

  .pr-title-link {
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    color: var(--text);
    text-decoration: none;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
    max-width: 100%;
  }

  .pr-title-link:hover {
    color: var(--accent);
    text-decoration: underline;
  }

  .pr-row-actions {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-shrink: 0;
  }

  .pr-session-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    border-radius: 0;
    border: 1px solid var(--border);
    background: transparent;
    color: var(--text-muted);
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    cursor: pointer;
    transition: background 0.12s, color 0.12s, border-color 0.12s;
    flex-shrink: 0;
  }

  .pr-session-btn:hover {
    background: color-mix(in srgb, var(--accent) 12%, transparent);
    border-color: var(--accent);
    color: var(--accent);
  }

  .pr-row-meta {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--text-muted);
  }

  .pr-sep {
    opacity: 0.4;
  }

  .pr-role-text,
  .pr-age-text {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  /* -- Mobile PR card -- */
  .mobile-pr-card {
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 12px 12px;
    width: 100%;
  }

  .mobile-pr-top {
    display: flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
  }

  .mobile-pr-actions {
    align-self: flex-end;
    margin-top: 4px;
  }

  /* -- Activity list -- */
  .activity-list {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .activity-row {
    display: flex;
    align-items: baseline;
    gap: 8px;
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    min-width: 0;
  }

  .commit-hash {
    color: var(--text-muted);
    flex-shrink: 0;
    letter-spacing: 0.02em;
  }

  .commit-msg {
    color: var(--text);
    flex: 1;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
  }

  .commit-branch {
    color: var(--text-muted);
    flex-shrink: 0;
    white-space: nowrap;
  }

  .commit-time {
    color: var(--text-muted);
    flex-shrink: 0;
    white-space: nowrap;
    opacity: 0.6;
  }

  /* -- Non-git notice -- */
  .non-git-notice {
    padding: 8px 0;
  }

  .non-git-msg {
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    color: var(--text-muted);
  }

  /* -- CTA buttons -- */
  .cta-row {
    display: flex;
    align-items: center;
    gap: 8px;
    padding-top: 4px;
    flex-shrink: 0;
  }

  /* -- Skeletons (activity section only) -- */
  .skeleton {
    pointer-events: none;
  }

  .skeleton-line {
    background: var(--border);
    animation: skeleton-pulse 1.4s ease-in-out infinite;
  }

  @keyframes skeleton-pulse {
    0%, 100% { opacity: 0.4; }
    50% { opacity: 0.7; }
  }

  .skeleton-activity {
    height: 12px;
    width: 75%;
  }

  /* -- Mobile -- */
  @media (max-width: 600px) {
    .repo-dashboard {
      padding: 16px;
    }
  }
</style>
