// frontend/src/components/SessionTabBar.svelte
<script lang="ts">
  import type { SessionSummary } from '../lib/types.js';

  let {
    sessions,
    activeSessionId,
    onSelectSession,
    onCloseSession,
    onNewAgent,
    onNewTerminal,
    onCustomize,
  }: {
    sessions: SessionSummary[];
    activeSessionId: string | null;
    onSelectSession: (id: string) => void;
    onCloseSession: (id: string) => void;
    onNewAgent: () => void;
    onNewTerminal: () => void;
    onCustomize: () => void;
  } = $props();

  let newMenuOpen = $state(false);
  let newMenuBtnEl = $state<HTMLButtonElement | null>(null);

  // Stable tab names scoped to the provided session list. Closing a tab does not renumber others.
  let tabNames = $state(new Map<string, string>());
  let nextAgentIndex = $state(0);
  let nextTerminalIndex = $state(0);

  $effect(() => {
    let updated = new Map(tabNames);
    let changed = false;
    for (const s of sessions) {
      if (!updated.has(s.id)) {
        if (s.type === 'terminal') {
          nextTerminalIndex = nextTerminalIndex + 1;
          updated.set(s.id, `Terminal ${nextTerminalIndex}`);
        } else {
          nextAgentIndex = nextAgentIndex + 1;
          updated.set(s.id, `Agent ${nextAgentIndex}`);
        }
        changed = true;
      }
    }
    if (changed) {
      tabNames = updated;
    }
  });

  function tabName(id: string): string {
    return tabNames.get(id) ?? id;
  }

  const terminalSvg = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" width="14" height="14"><path d="M4 17l6-6-6-6"/><path d="M12 19h8"/></svg>`;
  const agentSvg = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" width="14" height="14"><rect x="3" y="3" width="18" height="18"/><path d="M3 9h18"/><path d="M9 21V9"/></svg>`;

  function tabIcon(session: SessionSummary): string {
    return session.type === 'terminal' ? terminalSvg : agentSvg;
  }

  function handleCloseClick(e: MouseEvent, id: string) {
    e.stopPropagation();
    onCloseSession(id);
  }

  function handleCloseKeydown(e: KeyboardEvent, id: string) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.stopPropagation();
      onCloseSession(id);
    }
  }

  function toggleNewMenu() {
    newMenuOpen = !newMenuOpen;
  }

  function selectNewAgent() {
    newMenuOpen = false;
    onNewAgent();
  }

  function selectNewTerminal() {
    newMenuOpen = false;
    onNewTerminal();
  }

  function selectCustomize() {
    newMenuOpen = false;
    onCustomize();
  }

  function onWindowClick(e: MouseEvent) {
    if (
      newMenuOpen &&
      newMenuBtnEl &&
      document.contains(e.target as Node) &&
      !newMenuBtnEl.closest('.new-btn-wrap')?.contains(e.target as Node)
    ) {
      newMenuOpen = false;
    }
  }

  function onMenuKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && newMenuOpen) {
      newMenuOpen = false;
      newMenuBtnEl?.focus();
    }
  }
</script>

<svelte:window onclick={onWindowClick} />

<div class="session-tab-bar" role="tablist" aria-label="Sessions">
  <div class="tabs-scroll">
    {#each sessions as session (session.id)}
      {@const isActive = session.id === activeSessionId}
      <button
        class="tab"
        class:tab--active={isActive}
        role="tab"
        aria-selected={isActive}
        aria-label="{tabName(session.id)}"
        tabindex={isActive ? 0 : -1}
        data-track="session-tab.select"
        onclick={() => onSelectSession(session.id)}
      >
        <span class="tab-icon" aria-hidden="true">{@html tabIcon(session)}</span>
        <span class="tab-name">{tabName(session.id)}</span>
        <!-- svelte-ignore a11y_interactive_supports_focus -->
        <span
          class="tab-close"
          role="button"
          aria-label="Close {tabName(session.id)}"
          data-track="session-tab.close"
          onclick={(e) => handleCloseClick(e, session.id)}
          onkeydown={(e) => handleCloseKeydown(e, session.id)}
        >×</span>
      </button>
    {/each}
  </div>

  <!-- New session button -->
  <div class="new-btn-wrap">
    <button
      bind:this={newMenuBtnEl}
      class="tab-new"
      aria-label="New session"
      aria-haspopup="menu"
      aria-expanded={newMenuOpen}
      data-track="session-tab.new-menu"
      onclick={toggleNewMenu}
      onkeydown={onMenuKeydown}
    >+</button>

    {#if newMenuOpen}
      <div class="new-menu" role="menu" tabindex="-1" onkeydown={onMenuKeydown}>
        <button
          class="new-menu-item"
          role="menuitem"
          data-track="session-tab.new-agent"
          onclick={selectNewAgent}
        >
          <span class="new-menu-icon">{@html agentSvg}</span>
          New Agent
        </button>
        <button
          class="new-menu-item"
          role="menuitem"
          data-track="session-tab.new-terminal"
          onclick={selectNewTerminal}
        >
          <span class="new-menu-icon">{@html terminalSvg}</span>
          New Terminal
        </button>
        <div class="new-menu-divider"></div>
        <button
          class="new-menu-item"
          role="menuitem"
          data-track="session-tab.customize"
          onclick={selectCustomize}
        >
          <span class="new-menu-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" width="14" height="14"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1-1.51V15H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg></span>
          Customize...
        </button>
      </div>
    {/if}
  </div>
</div>

<style>
  .session-tab-bar {
    display: flex;
    align-items: stretch;
    height: 32px;
    background: var(--bg);
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
  }

  /* Scrollable tab strip */
  .tabs-scroll {
    display: flex;
    align-items: stretch;
    overflow-x: auto;
    overflow-y: hidden;
    flex: 1;
    min-width: 0;
    /* hide scrollbar on all browsers */
    scrollbar-width: none;
  }

  .tabs-scroll::-webkit-scrollbar {
    display: none;
  }

  /* ── Individual tab ─────────────────── */
  .tab {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    height: 32px;
    padding: 0 8px;
    background: transparent;
    border: none;
    border-bottom: 2px solid transparent;
    margin-bottom: -1px;
    color: var(--text-muted);
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    cursor: pointer;
    white-space: nowrap;
    flex-shrink: 0;
    position: relative;
    transition: color 0.12s, background 0.12s;
    border-radius: 0;
    /* ensure native button reset */
    -webkit-appearance: none;
    appearance: none;
  }

  .tab:hover {
    color: var(--text);
    background: var(--surface-hover);
  }

  .tab--active {
    background: var(--surface);
    color: var(--text);
    border-bottom-color: var(--accent);
  }

  .tab--active:hover {
    background: var(--surface);
  }

  .tab-icon {
    font-size: var(--font-size-xs);
    line-height: 1;
    flex-shrink: 0;
  }

  .tab-name {
    max-width: 120px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  /* Close button */
  .tab-close {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    cursor: pointer;
    line-height: 1;
    flex-shrink: 0;
    border-radius: 0;
    width: 14px;
    height: 14px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    opacity: 0; /* hidden until hover on desktop */
    transition: opacity 0.1s, color 0.1s, background 0.1s;
  }

  .tab:hover .tab-close {
    opacity: 1;
  }

  .tab-close:hover {
    color: var(--text);
    background: var(--border);
  }

  .tab--active .tab-close {
    opacity: 0;
  }

  .tab--active:hover .tab-close {
    opacity: 1;
  }

  /* ── New button wrap ─────────────────── */
  .new-btn-wrap {
    position: relative;
    display: flex;
    align-items: center;
    flex-shrink: 0;
    border-left: 1px solid var(--border);
  }

  .tab-new {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    background: none;
    border: none;
    color: var(--text-muted);
    font-size: var(--font-size-lg);
    cursor: pointer;
    font-family: var(--font-mono);
    transition: color 0.12s, background 0.12s;
    -webkit-appearance: none;
    appearance: none;
    line-height: 1;
  }

  .tab-new:hover {
    color: var(--text);
    background: var(--surface-hover);
  }

  /* Dropdown menu */
  .new-menu {
    position: absolute;
    top: calc(100% + 2px);
    right: 0;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 0;
    z-index: 200;
    min-width: 180px;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.5);
    padding: 4px 0;
  }

  .new-menu-item {
    display: flex;
    align-items: center;
    gap: 8px;
    width: 100%;
    padding: 8px 12px;
    background: none;
    border: none;
    color: var(--text-muted);
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    cursor: pointer;
    text-align: left;
    transition: background 0.1s, color 0.1s;
    -webkit-appearance: none;
    appearance: none;
    white-space: nowrap;
  }

  .new-menu-item:hover {
    background: var(--surface-hover);
    color: var(--text);
  }

  .new-menu-icon {
    font-size: var(--font-size-xs);
    flex-shrink: 0;
  }

  .new-menu-divider {
    height: 1px;
    background: var(--border);
    margin: 4px 0;
  }

  /* ── Mobile: bigger touch targets, always-visible close ─── */
  @media (max-width: 600px) {
    .session-tab-bar {
      height: 44px;
    }

    .tab {
      height: 44px;
      padding: 0 12px;
      min-width: 44px;
    }

    .tab-close {
      /* always visible on mobile */
      opacity: 1;
      width: 18px;
      height: 18px;
    }

    .tab--active .tab-close {
      opacity: 1;
    }

    .tab-new {
      width: 44px;
      height: 44px;
    }
  }
</style>

// frontend/src/components/SessionTabBar.tsx
import React, { useEffect, useRef, useState } from 'react';
import type { SessionSummary } from '../lib/types.js';
import './SessionTabBar.css';

export interface SessionTabBarProps {
  sessions: SessionSummary[];
  activeSessionId: string | null;
  onSelectSession: (id: string) => void;
  onCloseSession: (id: string) => void;
  onNewAgent: () => void;
  onNewTerminal: () => void;
  onCustomize: () => void;
}

const terminalSvg = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" width="14" height="14">
    <path d="M4 17l6-6-6-6" /><path d="M12 19h8" />
  </svg>
);

const agentSvg = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" width="14" height="14">
    <rect x="3" y="3" width="18" height="18" /><path d="M3 9h18" /><path d="M9 21V9" />
  </svg>
);

const customizeSvg = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" width="14" height="14">
    <circle cx="12" cy="12" r="3" />
    <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1-1.51V15H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
  </svg>
);

interface NewMenuProps {
  onNewAgent: () => void;
  onNewTerminal: () => void;
  onCustomize: () => void;
  onKeyDown: (e: React.KeyboardEvent) => void;
}

function NewMenu({ onNewAgent, onNewTerminal, onCustomize, onKeyDown }: NewMenuProps) {
  return (
    <div className="new-menu" role="menu" tabIndex={-1} onKeyDown={onKeyDown}>
      <button className="new-menu-item" role="menuitem" data-track="session-tab.new-agent" onClick={onNewAgent} type="button">
        <span className="new-menu-icon">{agentSvg}</span>New Agent
      </button>
      <button className="new-menu-item" role="menuitem" data-track="session-tab.new-terminal" onClick={onNewTerminal} type="button">
        <span className="new-menu-icon">{terminalSvg}</span>New Terminal
      </button>
      <div className="new-menu-divider" />
      <button className="new-menu-item" role="menuitem" data-track="session-tab.customize" onClick={onCustomize} type="button">
        <span className="new-menu-icon">{customizeSvg}</span>Customize...
      </button>
    </div>
  );
}

interface TabProps {
  session: SessionSummary;
  tabName: string;
  isActive: boolean;
  onSelect: () => void;
  onClose: (e: React.MouseEvent) => void;
  onCloseKeyDown: (e: React.KeyboardEvent) => void;
}

function SessionTab({ session, tabName, isActive, onSelect, onClose, onCloseKeyDown }: TabProps) {
  const icon = session.type === 'terminal' ? terminalSvg : agentSvg;
  return (
    <button
      className={['tab', isActive && 'tab--active'].filter(Boolean).join(' ')}
      role="tab" aria-selected={isActive} aria-label={tabName}
      tabIndex={isActive ? 0 : -1} data-track="session-tab.select"
      onClick={onSelect} type="button"
    >
      <span className="tab-icon" aria-hidden="true">{icon}</span>
      <span className="tab-name">{tabName}</span>
      <span className="tab-close" role="button" aria-label={`Close ${tabName}`}
        data-track="session-tab.close" onClick={onClose} onKeyDown={onCloseKeyDown}>
        &times;
      </span>
    </button>
  );
}

export function SessionTabBar({ sessions, activeSessionId, onSelectSession, onCloseSession, onNewAgent, onNewTerminal, onCustomize }: SessionTabBarProps) {
  const [newMenuOpen, setNewMenuOpen] = useState(false);
  const [tabNames, setTabNames] = useState<Map<string, string>>(new Map());
  const nextAgentIndexRef = useRef(0);
  const nextTerminalIndexRef = useRef(0);
  const newMenuBtnRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    setTabNames((prev) => {
      const updated = new Map(prev);
      let changed = false;
      for (const s of sessions) {
        if (!updated.has(s.id)) {
          if (s.type === 'terminal') {
            nextTerminalIndexRef.current += 1;
            updated.set(s.id, `Terminal ${nextTerminalIndexRef.current}`);
          } else {
            nextAgentIndexRef.current += 1;
            updated.set(s.id, `Agent ${nextAgentIndexRef.current}`);
          }
          changed = true;
        }
      }
      return changed ? updated : prev;
    });
  }, [sessions]);

  useEffect(() => {
    if (!newMenuOpen) return;
    const handleClick = (e: MouseEvent) => {
      const wrap = newMenuBtnRef.current?.closest('.new-btn-wrap');
      if (e.target && wrap && !wrap.contains(e.target as Node)) setNewMenuOpen(false);
    };
    window.addEventListener('click', handleClick);
    return () => window.removeEventListener('click', handleClick);
  }, [newMenuOpen]);

  const onMenuKeydown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape' && newMenuOpen) { setNewMenuOpen(false); newMenuBtnRef.current?.focus(); }
  };

  return (
    <div className="session-tab-bar" role="tablist" aria-label="Sessions">
      <div className="tabs-scroll">
        {sessions.map((session) => (
          <SessionTab
            key={session.id}
            session={session}
            tabName={tabNames.get(session.id) ?? session.id}
            isActive={session.id === activeSessionId}
            onSelect={() => onSelectSession(session.id)}
            onClose={(e) => { e.stopPropagation(); onCloseSession(session.id); }}
            onCloseKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.stopPropagation(); onCloseSession(session.id); } }}
          />
        ))}
      </div>
      <div className="new-btn-wrap">
        <button ref={newMenuBtnRef} className="tab-new" aria-label="New session" aria-haspopup="menu"
          aria-expanded={newMenuOpen} data-track="session-tab.new-menu"
          onClick={() => setNewMenuOpen((v) => !v)} onKeyDown={onMenuKeydown} type="button">+</button>
        {newMenuOpen ? (
          <NewMenu
            onNewAgent={() => { setNewMenuOpen(false); onNewAgent(); }}
            onNewTerminal={() => { setNewMenuOpen(false); onNewTerminal(); }}
            onCustomize={() => { setNewMenuOpen(false); onCustomize(); }}
            onKeyDown={onMenuKeydown}
          />
        ) : null}
      </div>
    </div>
  );
}

export default SessionTabBar;
