// frontend/src/components/SplitPaneLayout.svelte
<script lang="ts">
  import { getUi, saveRightSidebarWidth, saveFileViewerRatio, MIN_RIGHT_SIDEBAR_WIDTH, MAX_RIGHT_SIDEBAR_WIDTH } from '../lib/state/ui.svelte.js';
  import type { Snippet } from 'svelte';

  let {
    terminal,
    fileViewer,
    rightSidebar,
  }: {
    terminal: Snippet;
    fileViewer: Snippet;
    rightSidebar: Snippet;
  } = $props();

  const ui = getUi();

  const MIN_TERMINAL_WIDTH = 300;
  const MIN_FILE_VIEWER_WIDTH = 300;

  // ── Resize state ──
  let dragging = $state<'right-sidebar' | 'file-viewer' | null>(null);
  let containerEl = $state<HTMLDivElement | undefined>();

  // Whether file viewer is open (has open tabs)
  let fileViewerOpen = $derived(ui.openFileTabs.length > 0);

  // Right sidebar effective width (0 when collapsed — sidebar is fully hidden)
  let rightSidebarEffectiveWidth = $derived(
    ui.rightSidebarCollapsed ? 0 : ui.rightSidebarWidth
  );

  function handlePointerDown(handle: 'right-sidebar' | 'file-viewer', e: PointerEvent): void {
    e.preventDefault();
    dragging = handle;
    (e.target as HTMLElement).setPointerCapture(e.pointerId);
  }

  function handlePointerMove(e: PointerEvent): void {
    if (!dragging || !containerEl) return;
    const rect = containerEl.getBoundingClientRect();

    if (dragging === 'right-sidebar') {
      const rightEdge = rect.right;
      const newRightWidth = rightEdge - e.clientX;
      const clamped = Math.max(MIN_RIGHT_SIDEBAR_WIDTH, Math.min(MAX_RIGHT_SIDEBAR_WIDTH, newRightWidth));
      ui.rightSidebarWidth = clamped;
    } else if (dragging === 'file-viewer') {
      // Available space = container width - right sidebar
      const available = rect.width - rightSidebarEffectiveWidth;
      const fileViewerWidth = rect.right - rightSidebarEffectiveWidth - e.clientX;
      const terminalWidth = e.clientX - rect.left;

      if (terminalWidth < MIN_TERMINAL_WIDTH || fileViewerWidth < MIN_FILE_VIEWER_WIDTH) return;

      ui.fileViewerRatio = fileViewerWidth / available;
    }
  }

  function handlePointerUp(): void {
    if (dragging === 'right-sidebar') {
      saveRightSidebarWidth();
    } else if (dragging === 'file-viewer') {
      saveFileViewerRatio();
    }
    dragging = null;
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="split-pane-layout"
  bind:this={containerEl}
  onpointermove={handlePointerMove}
  onpointerup={handlePointerUp}
>
  <!-- Terminal zone -->
  <div
    class="pane-terminal"
    style={fileViewerOpen ? `flex: ${1 - ui.fileViewerRatio}` : 'flex: 1'}
  >
    {@render terminal()}
  </div>

  <!-- File viewer zone (on demand) -->
  {#if fileViewerOpen}
    <div
      class="resize-handle"
      class:active={dragging === 'file-viewer'}
      role="separator"
      aria-label="resize terminal and file viewer"
      onpointerdown={(e) => handlePointerDown('file-viewer', e)}
    ></div>

    <div
      class="pane-file-viewer"
      style="flex: {ui.fileViewerRatio}"
    >
      {@render fileViewer()}
    </div>
  {/if}

  <!-- Resize handle + right sidebar (hidden entirely when collapsed) -->
  {#if !ui.rightSidebarCollapsed}
    <div
      class="resize-handle"
      class:active={dragging === 'right-sidebar'}
      role="separator"
      aria-label="resize right sidebar"
      onpointerdown={(e) => handlePointerDown('right-sidebar', e)}
    ></div>

    <div class="pane-right-sidebar">
      {@render rightSidebar()}
    </div>
  {/if}
</div>

<style>
  .split-pane-layout {
    display: flex;
    flex-direction: row;
    flex: 1;
    min-width: 0;
    height: 100%;
    overflow: hidden;
  }

  .pane-terminal {
    display: flex;
    flex-direction: column;
    min-width: 300px;
    height: 100%;
    overflow: hidden;
  }

  .pane-file-viewer {
    min-width: 300px;
    height: 100%;
    overflow: hidden;
  }

  .pane-right-sidebar {
    flex-shrink: 0;
    height: 100%;
    overflow: hidden;
  }

  /* Resize handles */
  .resize-handle {
    width: 8px;
    cursor: col-resize;
    position: relative;
    flex-shrink: 0;
    z-index: 5;
  }

  .resize-handle::after {
    content: '';
    position: absolute;
    top: 0;
    bottom: 0;
    left: 3px;
    width: 1px;
    background: var(--border, #333);
    pointer-events: none;
  }

  .resize-handle:hover::after,
  .resize-handle.active::after {
    background: var(--accent, #d97757);
  }

  /* Mobile: hide right sidebar entirely */
  @media (max-width: 767px) {
    .pane-right-sidebar {
      display: none;
    }

    .resize-handle {
      display: none;
    }
  }
</style>

// frontend/src/components/SplitPaneLayout.tsx
import React, { useCallback, useRef, useState } from 'react';
import './SplitPaneLayout.css';

const MIN_RIGHT_SIDEBAR_WIDTH = 200;
const MAX_RIGHT_SIDEBAR_WIDTH = 600;
const MIN_TERMINAL_WIDTH = 300;
const MIN_FILE_VIEWER_WIDTH = 300;

export interface SplitPaneLayoutProps {
  terminal: React.ReactNode;
  fileViewer?: React.ReactNode;
  rightSidebar?: React.ReactNode;
  /** Whether the file viewer pane is open (has content) */
  fileViewerOpen?: boolean;
  /** Whether the right sidebar is collapsed */
  rightSidebarCollapsed?: boolean;
  /** Current right sidebar width in px */
  rightSidebarWidth?: number;
  /** Current file viewer ratio (0-1) */
  fileViewerRatio?: number;
  onRightSidebarWidthChange?: (width: number) => void;
  onFileViewerRatioChange?: (ratio: number) => void;
}

export function SplitPaneLayout({
  terminal,
  fileViewer,
  rightSidebar,
  fileViewerOpen = false,
  rightSidebarCollapsed = false,
  rightSidebarWidth: externalRightSidebarWidth,
  fileViewerRatio: externalFileViewerRatio,
  onRightSidebarWidthChange,
  onFileViewerRatioChange,
}: SplitPaneLayoutProps) {
  const [internalRightSidebarWidth, setInternalRightSidebarWidth] = useState(320);
  const [internalFileViewerRatio, setInternalFileViewerRatio] = useState(0.4);
  const [dragging, setDragging] = useState<'right-sidebar' | 'file-viewer' | null>(null);

  const rightSidebarWidthValue = externalRightSidebarWidth ?? internalRightSidebarWidth;
  const fileViewerRatioValue = externalFileViewerRatio ?? internalFileViewerRatio;

  const containerRef = useRef<HTMLDivElement>(null);

  const rightSidebarEffectiveWidth = rightSidebarCollapsed ? 0 : rightSidebarWidthValue;

  const handlePointerDown = useCallback(
    (handle: 'right-sidebar' | 'file-viewer', e: React.PointerEvent<HTMLDivElement>) => {
      e.preventDefault();
      setDragging(handle);
      (e.target as HTMLElement).setPointerCapture(e.pointerId);
    },
    []
  );

  const handlePointerMove = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if (!dragging || !containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();

      if (dragging === 'right-sidebar') {
        const rightEdge = rect.right;
        const newRightWidth = rightEdge - e.clientX;
        const clamped = Math.max(MIN_RIGHT_SIDEBAR_WIDTH, Math.min(MAX_RIGHT_SIDEBAR_WIDTH, newRightWidth));
        setInternalRightSidebarWidth(clamped);
        onRightSidebarWidthChange?.(clamped);
      } else if (dragging === 'file-viewer') {
        const available = rect.width - rightSidebarEffectiveWidth;
        const fileViewerWidth = rect.right - rightSidebarEffectiveWidth - e.clientX;
        const terminalWidth = e.clientX - rect.left;
        if (terminalWidth < MIN_TERMINAL_WIDTH || fileViewerWidth < MIN_FILE_VIEWER_WIDTH) return;
        const ratio = fileViewerWidth / available;
        setInternalFileViewerRatio(ratio);
        onFileViewerRatioChange?.(ratio);
      }
    },
    [dragging, rightSidebarEffectiveWidth, onRightSidebarWidthChange, onFileViewerRatioChange]
  );

  const handlePointerUp = useCallback(() => {
    setDragging(null);
  }, []);

  return (
    <div
      className="split-pane-layout"
      ref={containerRef}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
    >
      <div
        className="pane-terminal"
        style={{ flex: fileViewerOpen ? String(1 - fileViewerRatioValue) : '1' }}
      >
        {terminal}
      </div>

      {fileViewerOpen ? (
        <>
          <div
            className={['resize-handle', dragging === 'file-viewer' && 'active'].filter(Boolean).join(' ')}
            role="separator"
            aria-label="resize terminal and file viewer"
            onPointerDown={(e) => handlePointerDown('file-viewer', e)}
          />
          <div
            className="pane-file-viewer"
            style={{ flex: String(fileViewerRatioValue) }}
          >
            {fileViewer}
          </div>
        </>
      ) : null}

      {!rightSidebarCollapsed ? (
        <>
          <div
            className={['resize-handle', dragging === 'right-sidebar' && 'active'].filter(Boolean).join(' ')}
            role="separator"
            aria-label="resize right sidebar"
            onPointerDown={(e) => handlePointerDown('right-sidebar', e)}
          />
          <div
            className="pane-right-sidebar"
            style={{ width: rightSidebarWidthValue }}
          >
            {rightSidebar}
          </div>
        </>
      ) : null}
    </div>
  );
}

export default SplitPaneLayout;
