// frontend/src/components/StartWorkModal.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import type { GitHubIssue, JiraIssue, AnyIssue, Repo } from '../lib/types.js';
import { createSession, ConflictError, fetchWorkspaces } from '../lib/api.js';
import { TuiButton } from './TuiButton.js';
import './StartWorkModal.css';

export interface StartWorkModalProps {
  issue: AnyIssue;
  open: boolean;
  onClose: () => void;
  onSessionCreated: (sessionId: string) => void;
}

function detectSource(i: AnyIssue): 'github' | 'jira' {
  if ('number' in i && 'labels' in i) return 'github';
  return 'jira';
}

function buildDefaultBranch(issue: AnyIssue, source: 'github' | 'jira'): string {
  if (source === 'github') return `gh-${(issue as GitHubIssue).number}`;
  return (issue as JiraIssue).key.toLowerCase();
}

function buildTicketDisplay(issue: AnyIssue, source: 'github' | 'jira'): string {
  if (source === 'github') return `#${(issue as GitHubIssue).number} — ${issue.title}`;
  return `${(issue as JiraIssue).key} — ${issue.title}`;
}

type TicketContext = { ticketId: string; title: string; url: string; repoPath: string; repoName: string; source: 'github' | 'jira' };

function useWorkspaceLoader(source: 'github' | 'jira', open: boolean) {
  const [workspaces, setWorkspaces] = useState<Repo[]>([]);
  const [selectedPath, setSelectedPath] = useState('');

  useEffect(() => {
    if (source !== 'jira' || !open) return;
    fetchWorkspaces()
      .then((ws) => {
        setWorkspaces(ws);
        setSelectedPath((prev) => (!prev && ws.length > 0 ? ws[0]!.path : prev));
      })
      .catch(() => {});
  }, [source, open]);

  return { workspaces, selectedPath, setSelectedPath };
}

function useStartWork(repoPath: string, branchName: string, buildCtx: () => TicketContext, onSessionCreated: (id: string) => void, onClose: () => void) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleStart = useCallback(async () => {
    if (loading || !repoPath) {
      if (!repoPath) setError('No workspace selected. Jira tickets require a workspace context.');
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const session = await createSession({ repoPath, worktreePath: null, type: 'agent', branchName, ticketContext: buildCtx() });
      onSessionCreated(session.id);
      onClose();
    } catch (err) {
      if (err instanceof ConflictError) { onSessionCreated(err.sessionId); onClose(); return; }
      setError(err instanceof Error ? err.message : 'Failed to start work');
    } finally {
      setLoading(false);
    }
  }, [loading, repoPath, branchName, buildCtx, onSessionCreated, onClose]);

  return { loading, error, handleStart };
}


export function StartWorkModal({ issue, open, onClose, onSessionCreated }: StartWorkModalProps) {
  const source = detectSource(issue);
  const defaultBranch = buildDefaultBranch(issue, source);
  const ticketDisplay = buildTicketDisplay(issue, source);
  const [branchName, setBranchName] = useState('');
  const [branchInitialized, setBranchInitialized] = useState(false);
  const { workspaces, selectedPath, setSelectedPath } = useWorkspaceLoader(source, open);
  const backdropRef = useRef<HTMLDivElement>(null);

  const repoPath = source === 'github' ? (issue as GitHubIssue).repoPath : selectedPath;
  const repoName = source === 'github' ? (issue as GitHubIssue).repoName : (workspaces.find((w) => w.path === selectedPath)?.name ?? '');

  const buildCtx = useCallback((): TicketContext => {
    if (source === 'github') {
      const gh = issue as GitHubIssue;
      return { ticketId: `GH-${gh.number}`, title: gh.title, url: gh.url, source: 'github', repoPath: gh.repoPath, repoName: gh.repoName };
    }
    const jira = issue as JiraIssue;
    return { ticketId: jira.key, title: jira.title, url: jira.url, source: 'jira', repoPath, repoName };
  }, [source, issue, repoPath, repoName]);

  const { loading, error, handleStart } = useStartWork(repoPath, branchName, buildCtx, onSessionCreated, onClose);

  useEffect(() => {
    if (open && !branchInitialized) { setBranchName(defaultBranch); setBranchInitialized(true); }
    if (!open) setBranchInitialized(false);
  }, [open, branchInitialized, defaultBranch]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'Enter' && !loading) void handleStart();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, loading, onClose, handleStart]);

  const handleBackdropClick = useCallback((e: React.MouseEvent) => { if (e.target === backdropRef.current) onClose(); }, [onClose]);

  if (!open) return null;
  return (
    <div className="start-work-modal-backdrop" ref={backdropRef} onClick={handleBackdropClick}>
      <div className="start-work-modal">
        <div className="modal-header">
          <span className="modal-title">Start Work</span>
          <button className="modal-close" onClick={onClose}>&times;</button>
        </div>
        <div className="modal-body">
          <div className="ticket-info">
            <span className="ticket-info-label">Ticket</span>
            <span className="ticket-info-value">{ticketDisplay}</span>
          </div>
          {source === 'github' ? (
            <div className="ticket-info">
              <span className="ticket-info-label">Repo</span>
              <span className="ticket-info-value">{repoName}</span>
            </div>
          ) : (
            <div className="field">
              <label className="field-label" htmlFor="workspace-select">Workspace</label>
              {workspaces.length > 0 ? (
                <select id="workspace-select" className="field-input" value={selectedPath} onChange={(e) => setSelectedPath(e.target.value)}>
                  {workspaces.map((ws) => <option key={ws.path} value={ws.path}>{ws.name}</option>)}
                </select>
              ) : (
                <span className="ticket-info-value" style={{ opacity: 0.5 }}>Loading workspaces...</span>
              )}
            </div>
          )}
          <div className="field">
            <label className="field-label" htmlFor="branch-name">Branch Name</label>
            <input id="branch-name" className="field-input" type="text" value={branchName} placeholder={defaultBranch} onChange={(e) => setBranchName(e.target.value)} />
          </div>
          {error && <div className="error-msg">{error}</div>}
        </div>
        <div className="modal-footer">
          <TuiButton variant="ghost" onClick={onClose} disabled={loading}>Cancel</TuiButton>
          <TuiButton variant="primary" onClick={() => void handleStart()} disabled={loading}>
            {loading ? 'Starting...' : 'Start Work'}
          </TuiButton>
        </div>
      </div>
    </div>
  );
}

export default StartWorkModal;

// frontend/src/components/StartWorkModal.svelte
<script lang="ts">
  import type { GitHubIssue, JiraIssue, AnyIssue, Repo } from '../lib/types.js';
  import { createSession, ConflictError, fetchWorkspaces } from '../lib/api.js';
  import TuiButton from './TuiButton.svelte';

  let {
    issue,
    open = false,
    onClose,
    onSessionCreated,
  }: {
    issue: AnyIssue;
    open: boolean;
    onClose: () => void;
    onSessionCreated: (sessionId: string) => void;
  } = $props();

  function detectSource(i: AnyIssue): 'github' | 'jira' {
    if ('number' in i && 'labels' in i) return 'github';
    return 'jira';
  }

  let source = $derived(detectSource(issue));

  let ticketDisplay = $derived(
    source === 'github' ? `#${(issue as GitHubIssue).number} — ${issue.title}` :
    `${(issue as JiraIssue).key} — ${issue.title}`
  );

  let defaultBranch = $derived(
    source === 'github' ? `gh-${(issue as GitHubIssue).number}` :
    (issue as JiraIssue).key.toLowerCase()
  );

  // For Jira, user selects a workspace since issues are cross-repo
  let workspaces = $state<Repo[]>([]);
  let selectedWorkspacePath = $state('');

  let repoPath = $derived(
    source === 'github' ? (issue as GitHubIssue).repoPath : selectedWorkspacePath
  );
  let repoName = $derived.by(() => {
    if (source === 'github') return (issue as GitHubIssue).repoName;
    const ws = workspaces.find(w => w.path === selectedWorkspacePath);
    return ws?.name ?? '';
  });

  let branchName = $state('');
  let loading = $state(false);
  let error = $state<string | null>(null);

  // Load workspaces for Jira, and initialize branch name
  let branchInitialized = false;
  $effect(() => {
    if (open && !branchInitialized) {
      branchName = defaultBranch;
      branchInitialized = true;
    }
    if (!open) {
      branchInitialized = false;
    }
    if (source !== 'github' && open) {
      fetchWorkspaces().then(ws => {
        workspaces = ws;
        if (ws.length > 0 && !selectedWorkspacePath) {
          selectedWorkspacePath = ws[0]!.path;
        }
      }).catch(() => {});
    }
  });

  function buildTicketContext() {
    if (source === 'github') {
      const gh = issue as GitHubIssue;
      return {
        ticketId: `GH-${gh.number}`,
        title: gh.title,
        url: gh.url,
        source: 'github' as const,
        repoPath: gh.repoPath,
        repoName: gh.repoName,
      };
    } else {
      const jira = issue as JiraIssue;
      return {
        ticketId: jira.key,
        title: jira.title,
        url: jira.url,
        source: 'jira' as const,
        repoPath: repoPath,
        repoName: repoName,
      };
    }
  }

  async function handleStart() {
    if (loading) return;

    if (!repoPath) {
      error = 'No workspace selected. Jira tickets require a workspace context.';
      return;
    }

    loading = true;
    error = null;

    try {
      const session = await createSession({
        repoPath: repoPath,
        worktreePath: null,
        type: 'agent',
        branchName,
        ticketContext: buildTicketContext(),
      });

      onSessionCreated(session.id);
      onClose();
    } catch (err) {
      if (err instanceof ConflictError) {
        onSessionCreated(err.sessionId);
        onClose();
        return;
      }
      error = err instanceof Error ? err.message : 'Failed to start work';
    } finally {
      loading = false;
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') onClose();
    if (e.key === 'Enter' && !loading) handleStart();
  }
</script>

{#if open}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal-backdrop" onkeydown={handleKeydown} onclick={onClose}>
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="modal" onclick={(e) => e.stopPropagation()}>
      <div class="modal-header">
        <span class="modal-title">Start Work</span>
        <button class="modal-close" onclick={onClose}>&times;</button>
      </div>

      <div class="modal-body">
        <div class="ticket-info">
          <span class="ticket-info-label">Ticket</span>
          <span class="ticket-info-value">{ticketDisplay}</span>
        </div>

        {#if source === 'github'}
          <div class="ticket-info">
            <span class="ticket-info-label">Repo</span>
            <span class="ticket-info-value">{repoName}</span>
          </div>
        {:else}
          <div class="field">
            <label class="field-label" for="workspace-select">Workspace</label>
            {#if workspaces.length > 0}
              <select
                id="workspace-select"
                class="field-input"
                bind:value={selectedWorkspacePath}
              >
                {#each workspaces as ws (ws.path)}
                  <option value={ws.path}>{ws.name}</option>
                {/each}
              </select>
            {:else}
              <span class="ticket-info-value" style="opacity: 0.5">Loading workspaces...</span>
            {/if}
          </div>
        {/if}

        <div class="field">
          <label class="field-label" for="branch-name">Branch Name</label>
          <input
            id="branch-name"
            class="field-input"
            type="text"
            bind:value={branchName}
            placeholder={defaultBranch}
          />
        </div>

        {#if error}
          <div class="error-msg">{error}</div>
        {/if}
      </div>

      <div class="modal-footer">
        <TuiButton variant="ghost" onclick={onClose} disabled={loading}>Cancel</TuiButton>
        <TuiButton variant="primary" onclick={handleStart} disabled={loading}>
          {#if loading}Starting...{:else}Start Work{/if}
        </TuiButton>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
  }

  .modal {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 0;
    width: 90%;
    max-width: 420px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  }

  .modal-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 16px 16px;
    border-bottom: 1px solid var(--border);
  }

  .modal-title {
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    font-weight: 700;
    letter-spacing: 0.08em;
    color: var(--text);
  }

  .modal-close {
    background: none;
    border: none;
    color: var(--text-muted);
    font-size: 18px;
    cursor: pointer;
    padding: 0 4px;
    line-height: 1;
  }

  .modal-close:hover {
    color: var(--text);
  }

  .modal-body {
    padding: 16px;
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .ticket-info {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .ticket-info-label {
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--text-muted);
    letter-spacing: 0.06em;
  }

  .ticket-info-value {
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    color: var(--text);
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .field-label {
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--text-muted);
    letter-spacing: 0.06em;
  }

  .field-input {
    padding: 8px 12px;
    font-size: var(--font-size-sm);
    font-family: var(--font-mono);
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 0;
    color: var(--text);
    outline: none;
    transition: border-color 0.12s;
  }

  .field-input:focus {
    border-color: var(--accent);
  }

  .error-msg {
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--status-error);
    padding: 8px 8px;
    background: rgba(255, 100, 100, 0.1);
    border-radius: 0;
  }

  .modal-footer {
    display: flex;
    justify-content: flex-end;
    gap: 8px;
    padding: 12px 16px;
    border-top: 1px solid var(--border);
  }

</style>
