// frontend/src/components/WorkspaceGroup.tsx
import React, { useMemo } from 'react';
import type { Workspace, Repo, SessionSummary, WorktreeInfo, PullRequest } from '../lib/types.js';
import { deriveColor } from '../lib/colors.js';
import CipherText from './CipherText.js';
import TuiButton from './TuiButton.js';
import TuiProgress from './TuiProgress.js';
import WorkspaceItem from './WorkspaceItem.js';
import './WorkspaceGroup.css';

export interface WorkspaceGroupProps {
  workspace: Workspace;
  repos: Repo[];
  sessions?: SessionSummary[];
  worktrees?: WorktreeInfo[];
  loading?: boolean;
  collapsed?: boolean;
  launching?: boolean;
  activeRepoPath?: string | null;
  activeSessionId?: string | null;
  onToggleCollapse: () => void;
  onLaunchSession: (workspaceId: string) => void;
  onSelectSession: (id: string) => void;
  onSelectWorkspace: (path: string) => void;
  onNewWorktree: (workspace: Repo) => void;
  onOpenSettings: (workspace?: Repo) => void;
  onDeleteSession?: (id: string) => void;
  onDeleteWorktree?: (wt: WorktreeInfo) => void;
  orgPrs?: PullRequest[];
  loadingItems?: Set<string>;
}

function getSessionGroupsForRepo(repo: Repo, sessions: SessionSummary[]): Map<string, SessionSummary[]> {
  const map = new Map<string, SessionSummary[]>();
  map.set(repo.path, []);
  for (const s of sessions) {
    if (s.repoPath !== repo.path) continue;
    const key = s.worktreePath ?? repo.path;
    const existing = map.get(key) ?? [];
    existing.push(s);
    map.set(key, existing);
  }
  return map;
}

function getInactiveWorktreesForRepo(repo: Repo, sessions: SessionSummary[], worktrees: WorktreeInfo[]): WorktreeInfo[] {
  const activeWorktreePaths = new Set(
    sessions.filter((s) => s.repoPath === repo.path && s.worktreePath !== null).map((s) => s.worktreePath as string)
  );
  return worktrees.filter((wt) => wt.repoPath === repo.path && !activeWorktreePaths.has(wt.path));
}

interface GroupBodyProps extends WorkspaceGroupProps {
  workspaceSessions: SessionSummary[];
  sessions: SessionSummary[];
  worktrees: WorktreeInfo[];
}

function GroupBody({ workspace, repos, sessions, worktrees, launching, activeRepoPath, activeSessionId, workspaceSessions, orgPrs, loadingItems, onLaunchSession, onSelectSession, onSelectWorkspace, onNewWorktree, onOpenSettings, onDeleteSession, onDeleteWorktree }: GroupBodyProps) {
  return (
    <div className="group-body">
      {workspaceSessions.length > 0 ? (
        <ul className="workspace-sessions">
          {workspaceSessions.map((session) => (
            <li key={session.id} className="ws-session-row" onClick={() => onSelectSession(session.id)}>
              <span className="ws-badge">workspace</span>
              <span className="ws-session-name">{session.displayName}</span>
            </li>
          ))}
        </ul>
      ) : null}
      <div className="launch-row">
        <TuiButton variant="primary" disabled={launching} onClick={(e) => { e.stopPropagation(); onLaunchSession(workspace.id); }}>
          {launching ? <><TuiProgress variant="braille" />&nbsp;launching...</> : '> launch workspace session'}
        </TuiButton>
      </div>
      {repos.length === 0 ? (
        <div className="empty-repos">no repos</div>
      ) : (
        repos.map((repo) => (
          <WorkspaceItem
            key={repo.path}
            workspace={repo}
            sessionGroups={getSessionGroupsForRepo(repo, sessions)}
            inactiveWorktrees={getInactiveWorktreesForRepo(repo, sessions, worktrees)}
            isActive={activeRepoPath === repo.path && !activeSessionId}
            activeSessionId={activeSessionId}
            onSelectWorkspace={onSelectWorkspace}
            onSelectSession={onSelectSession}
            onNewWorktree={onNewWorktree}
            onOpenSettings={onOpenSettings}
            onDeleteSession={(id) => onDeleteSession?.(id)}
            onDeleteWorktree={(wt) => onDeleteWorktree?.(wt)}
            orgPrs={orgPrs ?? []}
            loadingItems={loadingItems}
          />
        ))
      )}
    </div>
  );
}

export function WorkspaceGroup({ workspace, repos, sessions = [], worktrees = [], loading = false, collapsed = false, launching = false, activeRepoPath = null, activeSessionId = null, onToggleCollapse, onLaunchSession, onSelectSession, onSelectWorkspace, onNewWorktree, onOpenSettings, onDeleteSession, onDeleteWorktree, orgPrs, loadingItems = new Set() }: WorkspaceGroupProps) {
  const themeColor = workspace.themeColor ?? deriveColor(workspace.name);
  const accentBorder = `color-mix(in srgb, ${themeColor} 30%, transparent)`;
  const workspaceSessions = useMemo(() => sessions.filter((s) => s.workspaceId === workspace.id), [sessions, workspace.id]);
  const sessionCount = sessions.length;

  return (
    <div
      className={['workspace-group', collapsed && 'collapsed'].filter(Boolean).join(' ')}
      style={{ ['--theme-color' as string]: themeColor, ['--accent-border' as string]: accentBorder }}
    >
      <div className="group-header" onClick={onToggleCollapse}>
        <div className="header-left">
          <span className="chevron">{collapsed ? '›' : '⌄'}</span>
          <span className="group-name"><CipherText text={workspace.name} loading={loading} /></span>
          {collapsed && sessionCount > 0 ? <span className="session-count">{sessionCount}</span> : null}
        </div>
      </div>
      {!collapsed ? (
        <GroupBody
          workspace={workspace} repos={repos} sessions={sessions} worktrees={worktrees}
          launching={launching} activeRepoPath={activeRepoPath} activeSessionId={activeSessionId}
          workspaceSessions={workspaceSessions} orgPrs={orgPrs} loadingItems={loadingItems}
          onLaunchSession={onLaunchSession} onSelectSession={onSelectSession}
          onSelectWorkspace={onSelectWorkspace} onNewWorktree={onNewWorktree}
          onOpenSettings={onOpenSettings} onDeleteSession={onDeleteSession} onDeleteWorktree={onDeleteWorktree}
          onToggleCollapse={onToggleCollapse} collapsed={collapsed} loading={loading}
        />
      ) : null}
    </div>
  );
}

export default WorkspaceGroup;

// frontend/src/components/WorkspaceGroup.svelte
<script lang="ts">
  import type { Workspace, Repo, SessionSummary, WorktreeInfo, PullRequest } from '../lib/types.js';
  import { toggleWorkspaceCollapse, isWorkspaceCollapsed } from '../lib/state/ui.svelte.js';
  import { isItemLoading } from '../lib/state/sessions.svelte.js';
  import { deriveColor } from '../lib/colors.js';
  import { SvelteMap } from 'svelte/reactivity';
  import CipherText from './CipherText.svelte';
  import TuiButton from './TuiButton.svelte';
  import TuiProgress from './TuiProgress.svelte';
  import WorkspaceItem from './WorkspaceItem.svelte';

  let {
    workspace,
    repos,
    sessions = [],
    worktrees = [],
    loading = false,
    activeRepoPath = null,
    activeSessionId = null,
    onLaunchSession,
    onSelectSession,
    onSelectWorkspace,
    onNewWorktree,
    onOpenSettings,
    onDeleteSession,
    onDeleteWorktree,
    orgPrs,
  }: {
    workspace: Workspace;
    repos: Repo[];
    sessions?: SessionSummary[];
    worktrees?: WorktreeInfo[];
    loading?: boolean;
    activeRepoPath?: string | null;
    activeSessionId?: string | null;
    onLaunchSession: (workspaceId: string) => void;
    onSelectSession: (id: string) => void;
    onSelectWorkspace: (path: string) => void;
    onNewWorktree: (workspace: Repo) => void;
    onOpenSettings: (workspace?: Repo) => void;
    onDeleteSession?: (id: string) => void;
    onDeleteWorktree?: (wt: WorktreeInfo) => void;
    orgPrs?: PullRequest[];
  } = $props();

  let collapsed = $derived(isWorkspaceCollapsed(workspace.id));
  let themeColor = $derived(workspace.themeColor ?? deriveColor(workspace.name));
  let accentBorder = $derived(`color-mix(in srgb, ${themeColor} 30%, transparent)`);
  let launching = $derived(isItemLoading(`ws-launch:${workspace.id}`));

  // Sessions launched at the workspace level (have workspaceId set directly)
  let workspaceSessions = $derived(
    sessions.filter(s => s.workspaceId === workspace.id)
  );

  // Total session count for the collapsed badge
  let sessionCount = $derived(sessions.length);

  // Build sessionGroups map and inactiveWorktrees per repo for WorkspaceItem
  function getSessionGroupsForRepo(repo: Repo): SvelteMap<string, SessionSummary[]> {
    const map = new SvelteMap<string, SessionSummary[]>();
    // Seed root entry so it's always present
    map.set(repo.path, []);
    for (const s of sessions) {
      if (s.repoPath !== repo.path) continue;
      const key = s.worktreePath ?? repo.path;
      const existing = map.get(key) ?? [];
      existing.push(s);
      map.set(key, existing);
    }
    return map;
  }

  function getInactiveWorktreesForRepo(repo: Repo): WorktreeInfo[] {
    const activeWorktreePaths = new Set(
      sessions
        .filter(s => s.repoPath === repo.path && s.worktreePath !== null)
        .map(s => s.worktreePath as string)
    );
    return worktrees.filter(
      wt => wt.repoPath === repo.path && !activeWorktreePaths.has(wt.path)
    );
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="workspace-group"
  class:collapsed
  style:--theme-color={themeColor}
  style:--accent-border={accentBorder}
>
  <!-- Header row -->
  <div
    class="group-header"
    onclick={() => toggleWorkspaceCollapse(workspace.id)}
  >
    <div class="header-left">
      <span class="chevron">{collapsed ? '›' : '⌄'}</span>
      <span class="group-name">
        <CipherText text={workspace.name} {loading} />
      </span>
      {#if collapsed && sessionCount > 0}
        <span class="session-count">{sessionCount}</span>
      {/if}
    </div>
  </div>

  {#if !collapsed}
    <div class="group-body">
      <!-- Workspace-level sessions (badge: workspace) -->
      {#if workspaceSessions.length > 0}
        <ul class="workspace-sessions">
          {#each workspaceSessions as session (session.id)}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
            <li
              class="ws-session-row"
              onclick={() => onSelectSession(session.id)}
            >
              <span class="ws-badge">workspace</span>
              <span class="ws-session-name">{session.displayName}</span>
            </li>
          {/each}
        </ul>
      {/if}

      <!-- Launch button -->
      <div class="launch-row">
        <TuiButton
          variant="primary"
          disabled={launching}
          onclick={(e) => { e.stopPropagation(); onLaunchSession(workspace.id); }}
        >
          {#if launching}
            <TuiProgress variant="braille" />&nbsp;launching...
          {:else}
            &gt; launch workspace session
          {/if}
        </TuiButton>
      </div>

      <!-- Nested repo items -->
      {#if repos.length === 0}
        <div class="empty-repos">no repos</div>
      {:else}
        {#each repos as repo (repo.path)}
          <WorkspaceItem
            workspace={repo}
            sessionGroups={getSessionGroupsForRepo(repo)}
            inactiveWorktrees={getInactiveWorktreesForRepo(repo)}
            isActive={activeRepoPath === repo.path && !activeSessionId}
            {onSelectWorkspace}
            {onSelectSession}
            {onNewWorktree}
            {onOpenSettings}
            onDeleteSession={(id) => onDeleteSession?.(id)}
            onDeleteWorktree={(wt) => onDeleteWorktree?.(wt)}
            orgPrs={orgPrs ?? []}
          />
        {/each}
      {/if}
    </div>
  {/if}
</div>

<style>
  .workspace-group {
    display: flex;
    flex-direction: column;
    font-family: var(--font-mono);
    border-radius: 0;
  }

  /* Collapsed: 2px left accent only */
  .workspace-group.collapsed {
    border-left: 2px solid var(--accent-border);
    border-top: none;
    border-right: none;
    border-bottom: none;
  }

  /* Expanded: full 1px rectangular outline */
  .workspace-group:not(.collapsed) {
    border: 1px solid var(--accent-border);
  }

  /* Header */
  .group-header {
    display: flex;
    align-items: center;
    padding: 8px 12px;
    cursor: pointer;
    min-height: 44px;
    transition: background 0.12s;
  }

  .group-header:hover {
    background: var(--surface-hover);
  }

  .header-left {
    display: flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
    flex: 1;
  }

  .chevron {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 16px;
    height: 16px;
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    flex-shrink: 0;
  }

  .group-name {
    font-size: var(--font-size-sm);
    font-weight: 700;
    color: var(--text);
    font-family: var(--font-mono);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
    text-transform: lowercase;
  }

  .session-count {
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--text-muted);
    background: var(--border);
    padding: 2px 8px;
    flex-shrink: 0;
  }

  /* Group body — base background to contrast with header */
  .group-body {
    background: var(--bg);
    display: flex;
    flex-direction: column;
  }

  /* Workspace-level sessions */
  .workspace-sessions {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .ws-session-row {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 12px 6px 28px;
    cursor: pointer;
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--text-muted);
    min-height: 36px;
    transition: background 0.1s;
  }

  .ws-session-row:hover {
    background: var(--surface-hover);
    color: var(--text);
  }

  /* Orange outline workspace badge — zero border-radius, outline-only */
  .ws-badge {
    display: inline-flex;
    align-items: center;
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: #fb923c;
    border: 1px solid #fb923c;
    border-radius: 0;
    padding: 1px 5px;
    flex-shrink: 0;
    text-transform: lowercase;
  }

  .ws-session-name {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    min-width: 0;
  }

  /* Launch row */
  .launch-row {
    padding: 8px 12px;
    display: flex;
  }

  .launch-row :global(.tui-btn) {
    width: 100%;
    justify-content: center;
    text-transform: lowercase;
  }

  /* Empty repos */
  .empty-repos {
    padding: 8px 12px 8px 28px;
    font-size: var(--font-size-xs);
    font-family: var(--font-mono);
    color: var(--text-muted);
  }
</style>
