// frontend/src/components/dialogs/CustomizeSessionDialog.svelte
<script lang="ts">
  import { createSession } from '../../lib/api.js';
  import { estimateTerminalDimensions } from '../../lib/utils.js';
  import { refreshAll } from '../../lib/state/sessions.svelte.js';
  import { getConfigState, refreshConfig } from '../../lib/state/config.svelte.js';
  import type { AgentType, Repo } from '../../lib/types.js';
  import DialogShell from './DialogShell.svelte';
  import TuiButton from '../TuiButton.svelte';
  import TuiCheckbox from '../TuiCheckbox.svelte';

  let {
    onSessionCreated,
  }: {
    onSessionCreated?: (sessionId: string) => void;
  } = $props();

  const config = getConfigState();

  let shellRef = $state<DialogShell | undefined>(undefined);

  // Repo info
  let repoPath = $state('');
  let workspaceName = $state('');

  // Form state
  let claudeArgsInput = $state('');
  let selectedAgent = $state<AgentType>('claude');
  let yoloMode = $state(false);
  let continueExisting = $state(false);
  let useTmux = $state(false);
  let creating = $state(false);

  function reset() {
    claudeArgsInput = '';
    yoloMode = false;
    continueExisting = false;
    useTmux = false;
  }

  export async function open(workspace: Pick<Repo, 'name' | 'path'>) {
    reset();
    repoPath = workspace.path;
    workspaceName = workspace.name;

    await refreshConfig();
    selectedAgent = config.defaultAgent as AgentType;
    yoloMode = config.defaultYolo;
    continueExisting = config.defaultContinue;
    useTmux = config.launchInTmux;

    shellRef?.open();
  }

  export function close() {
    shellRef?.close();
  }

  async function handleSubmit() {
    if (!repoPath || creating) return;
    creating = true;

    const claudeArgs = claudeArgsInput.trim().split(/\s+/).filter(Boolean);
    const { cols, rows } = estimateTerminalDimensions();

    try {
      const session = await createSession({
        repoPath,
        worktreePath: null,
        type: 'agent',
        continue: continueExisting,
        yolo: yoloMode,
        claudeArgs: claudeArgs.length > 0 ? claudeArgs : undefined,
        agent: selectedAgent,
        useTmux,
        cols,
        rows,
      });
      shellRef?.close();
      await refreshAll();
      if (session?.id) {
        onSessionCreated?.(session.id);
      }
    } catch (err: unknown) {
      if (err instanceof Error && 'sessionId' in err) {
        const conflictErr = err as Error & { sessionId?: string };
        shellRef?.close();
        await refreshAll();
        if (conflictErr.sessionId) {
          onSessionCreated?.(conflictErr.sessionId);
        }
      }
    } finally {
      creating = false;
    }
  }
</script>

<DialogShell
  bind:this={shellRef}
  width="480px"
  title="Customize Session"
>
  {#snippet footer()}
    <div class="footer-row">
      <TuiButton variant="ghost" onclick={() => shellRef?.close()} disabled={creating}>Cancel</TuiButton>
      <TuiButton
        variant="primary"
        data-track="dialog.customize-session.create"
        onclick={handleSubmit}
        disabled={!repoPath || creating}
      >
        {creating ? 'Creating...' : 'Start Session'}
      </TuiButton>
    </div>
  {/snippet}

  <div class="body-fields">
    {#if workspaceName}
      <p class="workspace-name">— {workspaceName}</p>
    {/if}

    <!-- Coding agent select -->
    <div class="dialog-field">
      <label class="dialog-label" for="cs-agent">Coding agent</label>
      <select
        id="cs-agent"
        class="dialog-select"
        data-track="dialog.customize-session.agent"
        bind:value={selectedAgent}
      >
        <option value="claude">Claude</option>
        <option value="codex">Codex</option>
      </select>
    </div>

    <!-- Continue existing -->
    <TuiCheckbox bind:checked={continueExisting}>Continue existing session</TuiCheckbox>

    <!-- Yolo mode -->
    <TuiCheckbox bind:checked={yoloMode}>Yolo mode (skip permission checks)</TuiCheckbox>

    <!-- Launch in tmux -->
    <TuiCheckbox bind:checked={useTmux}>Launch in tmux</TuiCheckbox>

    <!-- Extra args -->
    <div class="dialog-field">
      <label class="dialog-label" for="cs-args">Extra args (optional)</label>
      <input
        id="cs-args"
        type="text"
        class="dialog-input"
        placeholder="e.g. --verbose"
        bind:value={claudeArgsInput}
        autocomplete="off"
      />
    </div>
  </div>
</DialogShell>

<style>
  .footer-row {
    display: flex;
    justify-content: flex-end;
    gap: 8px;
  }

  .workspace-name {
    font-weight: 400;
    color: var(--text-muted);
    font-size: var(--font-size-base);
    margin: 0 0 4px;
  }

  .body-fields {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }

  .dialog-field {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .dialog-field--inline {
    flex-direction: row;
    align-items: center;
    gap: 8px;
  }

  .dialog-label {
    font-size: var(--font-size-sm);
    color: var(--text-muted);
  }

  .dialog-label-inline {
    font-size: var(--font-size-base);
    cursor: pointer;
  }

  .dialog-select,
  .dialog-input {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 0;
    color: var(--text);
    font-size: var(--font-size-base);
    font-family: var(--font-mono);
    padding: 8px 8px;
    width: 100%;
    box-sizing: border-box;
  }

  .dialog-select:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>

// frontend/src/components/dialogs/CustomizeSessionDialog.tsx
import { forwardRef, useImperativeHandle, useRef, useState } from 'react';
import DialogShell, { type DialogShellHandle } from './DialogShell.js';
import TuiButton from '../TuiButton.js';
import TuiCheckbox from '../TuiCheckbox.js';
import { estimateTerminalDimensions } from '../../lib/utils.js';
import { useConfigStore } from '../../lib/stores/config.js';
import { createAgentSession } from '../../lib/session-utils.js';
import type { AgentType } from '../../lib/types.js';
import './CustomizeSessionDialog.css';

export interface CustomizeSessionDialogHandle {
  open(
    workspace: { name: string; path: string },
    worktreePath?: string | null,
    preselectedFramework?: AgentType
  ): Promise<void>;
  close(): void;
}

interface Props {
  onSessionCreated?: (sessionId: string) => void;
}

interface FormState {
  claudeArgsInput: string;
  selectedAgent: AgentType;
  yoloMode: boolean;
  continueExisting: boolean;
  useTmux: boolean;
}

function defaultForm(): FormState {
  return {
    claudeArgsInput: '',
    selectedAgent: 'claude',
    yoloMode: false,
    continueExisting: false,
    useTmux: false,
  };
}

async function createSessionFromForm(
  workspacePath: string,
  worktreePath: string | null,
  form: FormState
) {
  const claudeArgs = form.claudeArgsInput.trim().split(/\s+/).filter(Boolean);
  const { cols, rows } = estimateTerminalDimensions();
  return createAgentSession({
    repoPath: workspacePath,
    worktreePath,
    type: 'agent',
    continue: form.continueExisting,
    yolo: form.yoloMode,
    claudeArgs: claudeArgs.length > 0 ? claudeArgs : undefined,
    agent: form.selectedAgent,
    useTmux: form.useTmux,
    cols,
    rows,
  });
}

interface BodyProps {
  workspaceName: string;
  form: FormState;
  onFormChange: (patch: Partial<FormState>) => void;
}

function CustomizeSessionBody({
  workspaceName,
  form,
  onFormChange,
}: BodyProps) {
  const frameworks = useConfigStore((state) => state.frameworks);
  const frameworkOptions =
    frameworks.length > 0
      ? frameworks
      : [
          {
            id: form.selectedAgent,
            displayName: form.selectedAgent,
          },
        ];

  return (
    <div className="customize-session-body-fields">
      {workspaceName && (
        <p className="customize-session-workspace-name">— {workspaceName}</p>
      )}
      <div className="customize-session-dialog-field">
        <label className="customize-session-dialog-label" htmlFor="cs-agent">
          Coding agent
        </label>
        <select
          id="cs-agent"
          className="customize-session-dialog-select"
          data-track="dialog.customize-session.agent"
          value={form.selectedAgent}
          onChange={(e) =>
            onFormChange({ selectedAgent: e.currentTarget.value as AgentType })
          }
        >
          {frameworkOptions.map((framework) => (
            <option key={framework.id} value={framework.id}>
              {framework.displayName}
            </option>
          ))}
        </select>
      </div>
      <TuiCheckbox
        checked={form.continueExisting}
        onChange={(checked) => onFormChange({ continueExisting: checked })}
      >
        Continue existing session
      </TuiCheckbox>
      <TuiCheckbox
        checked={form.yoloMode}
        onChange={(checked) => onFormChange({ yoloMode: checked })}
      >
        Yolo mode (skip permission checks)
      </TuiCheckbox>
      <TuiCheckbox
        checked={form.useTmux}
        onChange={(checked) => onFormChange({ useTmux: checked })}
      >
        Launch in tmux
      </TuiCheckbox>
      <div className="customize-session-dialog-field">
        <label className="customize-session-dialog-label" htmlFor="cs-args">
          Extra args (optional)
        </label>
        <input
          id="cs-args"
          type="text"
          className="customize-session-dialog-input"
          placeholder="e.g. --verbose"
          value={form.claudeArgsInput}
          onChange={(e) =>
            onFormChange({ claudeArgsInput: e.currentTarget.value })
          }
          autoComplete="off"
        />
      </div>
    </div>
  );
}

const CustomizeSessionDialog = forwardRef<CustomizeSessionDialogHandle, Props>(
  function CustomizeSessionDialog({ onSessionCreated }, ref) {
    const shellRef = useRef<DialogShellHandle>(null);
    const [workspacePath, setWorkspacePath] = useState('');
    const [worktreePath, setWorktreePath] = useState<string | null>(null);
    const [workspaceName, setWorkspaceName] = useState('');
    const [form, setForm] = useState<FormState>(defaultForm());
    const [creating, setCreating] = useState(false);

    useImperativeHandle(ref, () => ({
      async open(
        workspace: { name: string; path: string },
        nextWorktreePath?: string | null,
        preselectedFramework?: AgentType
      ) {
        setForm(defaultForm());
        setWorkspacePath(workspace.path);
        setWorktreePath(nextWorktreePath ?? null);
        setWorkspaceName(workspace.name);
        await useConfigStore.getState().refreshConfig();
        const config = useConfigStore.getState();
        setForm({
          claudeArgsInput: '',
          selectedAgent:
            preselectedFramework ?? (config.defaultAgent as AgentType),
          yoloMode: config.defaultYolo,
          continueExisting: config.defaultContinue,
          useTmux: config.launchInTmux,
        });
        shellRef.current?.open();
      },
      close() {
        shellRef.current?.close();
      },
    }));

    async function handleSubmit() {
      if (!workspacePath || creating) return;
      setCreating(true);
      const { session, error } = await createSessionFromForm(
        workspacePath,
        worktreePath,
        form
      );
      try {
        if (error && !session) return;
        shellRef.current?.close();
        if (session?.id) onSessionCreated?.(session.id);
      } finally {
        setCreating(false);
      }
    }

    const footer = (
      <div className="customize-session-footer-row">
        <TuiButton
          variant="ghost"
          onClick={() => shellRef.current?.close()}
          disabled={creating}
        >
          Cancel
        </TuiButton>
        <TuiButton
          variant="primary"
          data-track="dialog.customize-session.create"
          onClick={handleSubmit}
          disabled={!workspacePath || creating}
        >
          {creating ? 'Creating...' : 'Start Session'}
        </TuiButton>
      </div>
    );

    return (
      <DialogShell
        ref={shellRef}
        width="480px"
        title="Customize Session"
        footer={footer}
      >
        <CustomizeSessionBody
          workspaceName={workspaceName}
          form={form}
          onFormChange={(patch) => setForm((f) => ({ ...f, ...patch }))}
        />
      </DialogShell>
    );
  }
);

export default CustomizeSessionDialog;
