// frontend/src/components/dialogs/SettingsDialog.tsx
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  useCallback,
} from 'react';
import DialogShell, { type DialogShellHandle } from './DialogShell.js';
import TuiButton from '../TuiButton.js';
import TuiCheckbox from '../TuiCheckbox.js';
import SettingRow from './SettingRow.js';
import SettingsToc from './SettingsToc.js';
import GitHubIntegration from './integrations/GitHubIntegration.js';
import WebhookIntegration from './integrations/WebhookIntegration.js';
import JiraIntegration from './integrations/JiraIntegration.js';
import {
  setDefaultAgent, setDefaultContinue, setDefaultYolo, setLaunchInTmux,
  setDefaultNotifications, checkVersion, triggerUpdate, fetchAnalyticsSize, clearAnalytics,
  fetchGitHubStatus, fetchWebhookStatus, fetchDefaultAgent, fetchDefaultContinue,
  fetchDefaultYolo, fetchLaunchInTmux, fetchDefaultNotifications,
  fetchUpdateChannel, setUpdateChannel,
} from '../../lib/api.js';
import { useSessionsStore } from '../../lib/stores/sessions.js';
import { requestPermission, getPermissionState, syncPushSubscription } from '../../lib/notifications.js';
import './SettingsDialog.css';

export interface SettingsDialogHandle {
  open(scrollToId?: string): void;
  close(): void;
}

interface ConfigState {
  defaultAgent: string;
  defaultContinue: boolean;
  defaultYolo: boolean;
  launchInTmux: boolean;
  defaultNotifications: boolean;
}

const DEFAULT_CONFIG: ConfigState = {
  defaultAgent: 'claude', defaultContinue: true, defaultYolo: false,
  launchInTmux: false, defaultNotifications: true,
};

const TOC_SECTIONS = [
  { id: 'section-general', label: 'general' },
  { id: 'section-integrations', label: 'integrations', children: [
    { id: 'integration-github', label: 'GitHub' },
    { id: 'integration-webhooks', label: 'Webhooks' },
    { id: 'integration-jira', label: 'Jira' },
  ]},
  { id: 'section-advanced', label: 'advanced' },
  { id: 'section-about', label: 'about' },
];

const SECTION_KEYWORDS: Record<string, string[]> = {
  general: ['default coding agent', 'continue', 'yolo', 'tmux', 'notifications'],
  integrations: ['github', 'webhooks', 'jira', 'real-time', 'ci', 'pr', 'tickets'],
  advanced: ['developer tools', 'analytics', 'debug panel'],
  about: ['version', 'update', 'channel', 'nightly', 'stable'],
};

async function loadConfig(): Promise<ConfigState> {
  const [agent, cont, yolo, tmux, notif] = await Promise.all([
    fetchDefaultAgent().catch(() => DEFAULT_CONFIG.defaultAgent),
    fetchDefaultContinue().catch(() => DEFAULT_CONFIG.defaultContinue),
    fetchDefaultYolo().catch(() => DEFAULT_CONFIG.defaultYolo),
    fetchLaunchInTmux().catch(() => DEFAULT_CONFIG.launchInTmux),
    fetchDefaultNotifications().catch(() => DEFAULT_CONFIG.defaultNotifications),
  ]);
  return { defaultAgent: agent, defaultContinue: cont, defaultYolo: yolo, launchInTmux: tmux, defaultNotifications: notif };
}

function sectionClass(id: string, query: string): string {
  if (!query.trim()) return 'settings-dialog-section';
  const q = query.toLowerCase();
  const key = id.replace('section-', '');
  const matches = key.includes(q) || (SECTION_KEYWORDS[key]?.some((t) => t.includes(q)) ?? false);
  return ['settings-dialog-section', !matches ? 'dimmed' : ''].filter(Boolean).join(' ');
}

function useConfigHandlers(config: ConfigState, setConfig: React.Dispatch<React.SetStateAction<ConfigState>>, setError: (e: string) => void, notifPerm: NotificationPermission | 'unsupported', setNotifPerm: (p: NotificationPermission | 'unsupported') => void) {
  async function handleAgentChange(v: string) {
    const prev = config.defaultAgent;
    setConfig((c) => ({ ...c, defaultAgent: v })); setError('');
    try { await setDefaultAgent(v); }
    catch { setConfig((c) => ({ ...c, defaultAgent: prev })); setError('Failed to update default agent.'); }
  }
  async function handleContinueChange(v: boolean) {
    const prev = config.defaultContinue;
    setConfig((c) => ({ ...c, defaultContinue: v })); setError('');
    try { await setDefaultContinue(v); }
    catch { setConfig((c) => ({ ...c, defaultContinue: prev })); setError('Failed to update continue default.'); }
  }
  async function handleYoloChange(v: boolean) {
    const prev = config.defaultYolo;
    setConfig((c) => ({ ...c, defaultYolo: v })); setError('');
    try { await setDefaultYolo(v); }
    catch { setConfig((c) => ({ ...c, defaultYolo: prev })); setError('Failed to update yolo default.'); }
  }
  async function handleTmuxChange(v: boolean) {
    const prev = config.launchInTmux;
    setConfig((c) => ({ ...c, launchInTmux: v })); setError('');
    try { await setLaunchInTmux(v); }
    catch (err) { setConfig((c) => ({ ...c, launchInTmux: prev })); setError(err instanceof Error ? err.message : 'Failed to update tmux setting.'); }
  }
  async function handleNotifChange(v: boolean) {
    const prev = config.defaultNotifications;
    setConfig((c) => ({ ...c, defaultNotifications: v })); setError('');
    if (v && notifPerm !== 'granted') {
      const perm = await requestPermission(); setNotifPerm(perm);
      if (perm !== 'granted') {
        setConfig((c) => ({ ...c, defaultNotifications: prev }));
        setError(perm === 'unsupported' ? 'Notifications are not supported in this browser.' : perm === 'default' ? 'Notification permission is required.' : 'Notifications blocked by browser.');
        return;
      }
    }
    try {
      await setDefaultNotifications(v);
      if (notifPerm === 'granted') await syncPushSubscription(useSessionsStore.getState().getNotificationSessionIds());
    } catch { setConfig((c) => ({ ...c, defaultNotifications: prev })); setError('Failed to update notifications default.'); }
  }
  return { handleAgentChange, handleContinueChange, handleYoloChange, handleTmuxChange, handleNotifChange };
}

const SettingsDialog = forwardRef<SettingsDialogHandle>(function SettingsDialog(_props, ref) {
  const shellRef = useRef<DialogShellHandle>(null);
  const contentElRef = useRef<HTMLDivElement | null>(null);
  const [contentEl, setContentEl] = useState<HTMLDivElement | undefined>(undefined);
  const [config, setConfig] = useState<ConfigState>(DEFAULT_CONFIG);
  const [error, setError] = useState('');
  const [versionInfo, setVersionInfo] = useState({ current: '', latest: null as string | null, available: false, checked: false, updating: false, status: '' });
  const [analyticsSize, setAnalyticsSize] = useState<number | null>(null);
  const [clearing, setClearing] = useState(false);
  const [githubConnected, setGithubConnected] = useState(false);
  const [webhookCount, setWebhookCount] = useState(0);
  const [notifPerm, setNotifPerm] = useState<NotificationPermission | 'unsupported'>(getPermissionState());
  const [devtoolsEnabled, setDevtoolsEnabled] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [tocOpen, setTocOpen] = useState(false);

  const contentRefCallback = useCallback((el: HTMLDivElement | null) => {
    contentElRef.current = el; setContentEl(el ?? undefined);
  }, []);

  const configHandlers = useConfigHandlers(config, setConfig, setError, notifPerm, setNotifPerm);

  async function loadAllData() {
    const [cfg] = await Promise.all([
      loadConfig(),
      checkVersion().then((d) => setVersionInfo((v) => ({ ...v, current: d.current, latest: d.latest, available: d.updateAvailable, checked: true }))).catch(() => setVersionInfo((v) => ({ ...v, status: 'Failed to check for updates.' }))),
      fetchAnalyticsSize().then((d) => setAnalyticsSize(d.bytes)).catch(() => undefined),
      fetchGitHubStatus().then(async (s) => { setGithubConnected(s.connected); if (s.connected) { const ws = await fetchWebhookStatus().catch(() => null); if (ws?.configured) setWebhookCount(1); } }).catch(() => undefined),
    ]);
    setConfig(cfg);
  }

  useImperativeHandle(ref, () => ({
    open(scrollToId?: string) {
      setError(''); setVersionInfo((v) => ({ ...v, status: '', checked: false, updating: false }));
      setDevtoolsEnabled(localStorage.getItem('devtools-enabled') === 'true');
      setNotifPerm(getPermissionState());
      void loadAllData(); shellRef.current?.open();
      if (scrollToId) requestAnimationFrame(() => contentElRef.current?.querySelector(`#${scrollToId}`)?.scrollIntoView({ behavior: 'smooth' }));
    },
    close() { shellRef.current?.close(); void useSessionsStore.getState().refreshAll(); },
  }));

  async function handleClearAnalytics() {
    if (!confirm('Clear all analytics data? This cannot be undone.')) return;
    setClearing(true);
    try { await clearAnalytics(); setAnalyticsSize(0); }
    catch { setError('Failed to clear analytics.'); }
    finally { setClearing(false); }
  }

  async function handleUpdate() {
    setVersionInfo((v) => ({ ...v, updating: true, status: '' }));
    try {
      const result = await triggerUpdate();
      if (result.restarting) { setVersionInfo((v) => ({ ...v, status: 'Updated! Restarting\u2026', available: false })); setTimeout(() => location.reload(), 5000); }
      else setVersionInfo((v) => ({ ...v, status: 'Updated! Please restart the server manually.', available: false }));
    } catch { setVersionInfo((v) => ({ ...v, status: 'Update failed. Please try again.', updating: false })); }
  }

  const notifDescription = notifPerm === 'denied' ? 'Blocked by browser — check site settings' : notifPerm === 'unsupported' ? 'Not supported in this browser' : 'Notify when sessions need attention';
  const headerExtra = (
    <div className="settings-dialog-header-extra">
      <button className="settings-dialog-hamburger-btn" onClick={() => setTocOpen((v) => !v)} aria-label="Navigation">&#9776;</button>
      <input className="settings-dialog-search-input" type="text" placeholder="Search..." value={searchQuery} onChange={(e) => setSearchQuery(e.currentTarget.value)} aria-label="Search settings" />
    </div>
  );

  return (
    <DialogShell ref={shellRef} title="settings" variant="fullscreen" headerExtra={headerExtra}>
      <div className="settings-dialog-content" ref={contentRefCallback}>
        {error && <p className="error-msg">{error}</p>}
        <SettingsToc open={tocOpen} onclose={() => setTocOpen(false)} {...(contentEl ? { contentEl } : {})} sections={TOC_SECTIONS} />
        <div className="settings-dialog-sections">
          <GeneralSection config={config} notifDescription={notifDescription} notifPerm={notifPerm} searchQuery={searchQuery} handlers={configHandlers} />
          <IntegrationsSection searchQuery={searchQuery} githubConnected={githubConnected} webhookCount={webhookCount} onGitHubConnect={() => setGithubConnected(true)} onGitHubDisconnect={() => setGithubConnected(false)} />
          <AdvancedSection searchQuery={searchQuery} analyticsSize={analyticsSize} clearing={clearing} devtoolsEnabled={devtoolsEnabled} onDevtoolsChange={(v) => { setDevtoolsEnabled(v); localStorage.setItem('devtools-enabled', v ? 'true' : 'false'); window.dispatchEvent(new Event('devtools-changed')); }} onClearAnalytics={() => void handleClearAnalytics()} />
          <AboutSection searchQuery={searchQuery} versionInfo={versionInfo} onUpdate={() => void handleUpdate()} />
        </div>
      </div>
    </DialogShell>
  );
});

// ── Sub-sections ─────────────────────────────────────────────────────────────

type ConfigHandlers = ReturnType<typeof useConfigHandlers>;

function GeneralSection({ config, notifDescription, notifPerm, searchQuery, handlers }: { config: ConfigState; notifDescription: string; notifPerm: NotificationPermission | 'unsupported'; searchQuery: string; handlers: ConfigHandlers }) {
  const notifDisabled = (notifPerm === 'denied' || notifPerm === 'unsupported') && !config.defaultNotifications;
  return (
    <section id="section-general" className={sectionClass('section-general', searchQuery)}>
      <h3 className="settings-dialog-section-heading">general</h3>
      <SettingRow name="Default Coding Agent" description="Which AI agent to use for new sessions">
        <select className="settings-dialog-select" value={config.defaultAgent} onChange={(e) => void handlers.handleAgentChange(e.currentTarget.value)}>
          <option value="claude">Claude</option><option value="codex">Codex</option><option value="opencode">OpenCode</option>
        </select>
      </SettingRow>
      <SettingRow name="Continue existing session" description="Resume the last session when opening a repo">
        <TuiCheckbox checked={config.defaultContinue} onChange={(v) => void handlers.handleContinueChange(v)} />
      </SettingRow>
      <SettingRow name="YOLO mode" description="Skip permission checks for all sessions">
        <TuiCheckbox checked={config.defaultYolo} onChange={(v) => void handlers.handleYoloChange(v)} />
      </SettingRow>
      <SettingRow name="Launch in tmux" description="Wrap sessions in tmux for scroll and copy">
        <TuiCheckbox checked={config.launchInTmux} onChange={(v) => void handlers.handleTmuxChange(v)} />
      </SettingRow>
      <SettingRow name="Notifications" description={notifDescription}>
        <TuiCheckbox checked={config.defaultNotifications} onChange={(v) => void handlers.handleNotifChange(v)} disabled={notifDisabled} />
      </SettingRow>
    </section>
  );
}

function IntegrationsSection({ searchQuery, githubConnected, webhookCount, onGitHubConnect, onGitHubDisconnect }: { searchQuery: string; githubConnected: boolean; webhookCount: number; onGitHubConnect: () => void; onGitHubDisconnect: () => void }) {
  return (
    <section id="section-integrations" className={sectionClass('section-integrations', searchQuery)}>
      <h3 className="settings-dialog-section-heading">integrations</h3>
      <div id="integration-github"><GitHubIntegration onConnected={onGitHubConnect} onDisconnect={onGitHubDisconnect} webhookCount={webhookCount} /></div>
      <div id="integration-webhooks"><WebhookIntegration githubConnected={githubConnected} /></div>
      <div id="integration-jira"><JiraIntegration /></div>
    </section>
  );
}

function AdvancedSection({ searchQuery, analyticsSize, clearing, devtoolsEnabled, onDevtoolsChange, onClearAnalytics }: { searchQuery: string; analyticsSize: number | null; clearing: boolean; devtoolsEnabled: boolean; onDevtoolsChange: (v: boolean) => void; onClearAnalytics: () => void }) {
  return (
    <section id="section-advanced" className={sectionClass('section-advanced', searchQuery)}>
      <h3 className="settings-dialog-section-heading">advanced</h3>
      <SettingRow name="Developer Tools" description="Mobile debug panel">
        <TuiCheckbox checked={devtoolsEnabled} onChange={(v) => onDevtoolsChange(v)} />
      </SettingRow>
      <SettingRow name="Analytics" description="Local usage data">
        <div className="settings-dialog-analytics-action">
          {analyticsSize !== null && <span className="settings-dialog-analytics-size">{(analyticsSize / 1024 / 1024).toFixed(1)} MB</span>}
          <TuiButton variant="ghost" size="sm" onClick={onClearAnalytics} disabled={clearing}>{clearing ? 'Clearing\u2026' : 'Clear'}</TuiButton>
        </div>
      </SettingRow>
    </section>
  );
}

interface VersionInfo { current: string; latest: string | null; available: boolean; checked: boolean; updating: boolean; status: string }
function AboutSection({ searchQuery, versionInfo, onUpdate }: { searchQuery: string; versionInfo: VersionInfo; onUpdate: () => void }) {
  const [updateChannelValue, setUpdateChannelValue] = useState<'stable' | 'nightly'>('stable');
  const [savingChannel, setSavingChannel] = useState(false);

  useEffect(() => {
    fetchUpdateChannel().then(
      (ch) => setUpdateChannelValue(ch),
      () => setUpdateChannelValue('stable'),
    );
  }, []);

  const handleChannelChange = useCallback(async (channel: 'stable' | 'nightly') => {
    if (savingChannel || channel === updateChannelValue) return;
    setSavingChannel(true);
    try {
      await setUpdateChannel(channel);
      setUpdateChannelValue(channel);
    } catch {
      // ignore
    } finally {
      setSavingChannel(false);
    }
  }, [savingChannel, updateChannelValue]);

  return (
    <section id="section-about" className={sectionClass('section-about', searchQuery)}>
      <h3 className="settings-dialog-section-heading">about</h3>
      <SettingRow name="Version" description={versionInfo.current ? `v${versionInfo.current}` : ''}>
        {versionInfo.available ? (
          <TuiButton variant="primary" size="sm" onClick={onUpdate} disabled={versionInfo.updating}>{versionInfo.updating ? 'Updating\u2026' : `Update to v${versionInfo.latest}`}</TuiButton>
        ) : versionInfo.checked ? <span className="settings-dialog-version-ok">Up to date</span> : null}
      </SettingRow>
      <SettingRow name="Update Channel" description={updateChannelValue === 'nightly' ? 'Nightly builds' : 'Stable releases'}>
        <div className="settings-dialog-channel-selector">
          <button
            className={`settings-dialog-channel-btn${updateChannelValue === 'stable' ? ' active' : ''}`}
            disabled={savingChannel}
            onClick={() => handleChannelChange('stable')}
          >stable</button>
          <button
            className={`settings-dialog-channel-btn${updateChannelValue === 'nightly' ? ' active' : ''}`}
            disabled={savingChannel}
            onClick={() => handleChannelChange('nightly')}
          >nightly</button>
        </div>
      </SettingRow>
      {versionInfo.status && <p className="settings-dialog-update-status">{versionInfo.status}</p>}
    </section>
  );
}

export default SettingsDialog;

// frontend/src/components/dialogs/SettingsDialog.svelte
<script lang="ts">
  import DialogShell from './DialogShell.svelte';
  import TuiButton from '../TuiButton.svelte';
  import TuiCheckbox from '../TuiCheckbox.svelte';
  import SettingRow from './SettingRow.svelte';
  import SettingsToc from './SettingsToc.svelte';
  import GitHubIntegration from './integrations/GitHubIntegration.svelte';
  import WebhookIntegration from './integrations/WebhookIntegration.svelte';
  import JiraIntegration from './integrations/JiraIntegration.svelte';
  import WorkspaceEditor from './WorkspaceEditor.svelte';
  import type { Workspace } from '../../lib/types.js';
  import * as api from '../../lib/api.js';
  import {
    setDefaultAgent,
    setDefaultContinue,
    setDefaultYolo,
    setLaunchInTmux,
    setDefaultNotifications,
    checkVersion,
    triggerUpdate,
    fetchUpdateChannel,
    setUpdateChannel,
    fetchAnalyticsSize,
    clearAnalytics,
    fetchGitHubStatus,
    fetchWebhookStatus,
  } from '../../lib/api.js';
  import { refreshAll, getNotificationSessionIds, getSessionState } from '../../lib/state/sessions.svelte.js';
  import { getConfigState, refreshConfig } from '../../lib/state/config.svelte.js';
  import { requestPermission, getPermissionState, syncPushSubscription } from '../../lib/notifications.js';

  let shellRef = $state<ReturnType<typeof DialogShell> | undefined>(undefined);
  let contentEl = $state<HTMLDivElement | undefined>(undefined);

  const config = getConfigState();
  const sessionState = getSessionState();
  let error = $state('');

  // Workspace groups state
  let workspaceGroups = $state<Workspace[]>([]);

  // Version state
  let currentVersion = $state('');
  let latestVersion = $state<string | null>(null);
  let updateAvailable = $state(false);
  let versionChecked = $state(false);
  let updating = $state(false);
  let updateStatus = $state('');
  let updateChannelValue = $state<'stable' | 'nightly'>('stable');
  let savingChannel = $state(false);

  // Analytics state
  let analyticsSize = $state<number | null>(null);
  let clearing = $state(false);

  // GitHub state (for integration props)
  let githubConnected = $state(false);
  let webhookCount = $state(0);

  // Notification permission state
  let notificationPermission = $state<NotificationPermission | 'unsupported'>(getPermissionState());

  // Devtools state
  let devtoolsEnabled = $state(false);

  // Search state
  let searchQuery = $state('');

  // TOC drawer state
  let tocOpen = $state(false);

  function matchesSearch(sectionId: string): boolean {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    if (sectionId.includes(q)) return true;
    const sectionData: Record<string, string[]> = {
      general: ['default coding agent', 'continue existing session', 'yolo mode', 'launch in tmux', 'notifications', 'push notifications'],
      integrations: ['github', 'webhooks', 'jira', 'real-time', 'ci', 'pr', 'tickets'],
      workspaces: ['workspace', 'group', 'multi-repo', 'project'],
      advanced: ['developer tools', 'analytics', 'debug panel', 'usage data'],
      about: ['version', 'update'],
    };
    return sectionData[sectionId]?.some(term => term.includes(q)) ?? false;
  }

  async function loadWorkspaceGroups() {
    try { workspaceGroups = await api.fetchWorkspaceGroups(); } catch { /* silent */ }
  }

  async function checkVersionAsync() {
    updateStatus = '';
    try {
      const data = await checkVersion();
      currentVersion = data.current;
      latestVersion = data.latest;
      updateAvailable = data.updateAvailable;
      versionChecked = true;
    } catch {
      updateStatus = 'Failed to check for updates.';
    }
  }

  async function loadUpdateChannel() {
    try {
      updateChannelValue = await fetchUpdateChannel();
    } catch {
      updateChannelValue = 'stable';
    }
  }

  async function handleChannelChange(channel: 'stable' | 'nightly') {
    if (savingChannel || channel === updateChannelValue) return;
    savingChannel = true;
    try {
      await setUpdateChannel(channel);
      updateChannelValue = channel;
      versionChecked = false;
      await checkVersionAsync();
    } catch {
      error = 'Failed to update channel.';
    } finally {
      savingChannel = false;
    }
  }

  async function fetchAnalyticsSizeAsync() {
    try {
      const d = await fetchAnalyticsSize();
      analyticsSize = d.bytes;
    } catch {
      // ignore
    }
  }

  async function fetchGitHubStatusAsync() {
    try {
      const s = await fetchGitHubStatus();
      githubConnected = s.connected;
      // Check if webhooks are configured for disconnect confirmation
      if (s.connected) {
        try {
          const ws = await fetchWebhookStatus();
          if (ws.configured) webhookCount = 1; // indicates webhooks exist
        } catch { /* webhook status fetch is best-effort */ }
      }
    } catch {
      // ignore — githubConnected stays false
    }
  }

  export function open(scrollToId?: string) {
    error = '';
    updateStatus = '';
    versionChecked = false;
    updating = false;
    devtoolsEnabled = localStorage.getItem('devtools-enabled') === 'true';
    notificationPermission = getPermissionState();
    refreshConfig();
    loadUpdateChannel();
    checkVersionAsync();
    fetchAnalyticsSizeAsync();
    fetchGitHubStatusAsync();
    loadWorkspaceGroups();
    shellRef?.open();
    if (scrollToId) {
      requestAnimationFrame(() => {
        contentEl?.querySelector(`#${scrollToId}`)?.scrollIntoView({ behavior: 'smooth' });
      });
    }
  }

  export function close() {
    shellRef?.close();
    refreshAll();
  }

  // -- Handler functions (API calls with optimistic updates) --

  async function handleAgentChange() {
    const prev = config.defaultAgent;
    error = '';
    try {
      await setDefaultAgent(config.defaultAgent);
    } catch {
      config.defaultAgent = prev;
      error = 'Failed to update default agent.';
    }
  }

  async function handleContinueChange() {
    const prev = config.defaultContinue;
    error = '';
    try {
      await setDefaultContinue(config.defaultContinue);
    } catch {
      config.defaultContinue = prev;
      error = 'Failed to update continue default.';
    }
  }

  async function handleYoloChange() {
    const prev = config.defaultYolo;
    error = '';
    try {
      await setDefaultYolo(config.defaultYolo);
    } catch {
      config.defaultYolo = prev;
      error = 'Failed to update yolo default.';
    }
  }

  async function handleTmuxChange() {
    const prev = config.launchInTmux;
    error = '';
    try {
      await setLaunchInTmux(config.launchInTmux);
    } catch (err) {
      config.launchInTmux = prev;
      error = err instanceof Error ? err.message : 'Failed to update tmux setting.';
    }
  }

  async function handleNotificationsChange() {
    const prev = config.defaultNotifications;
    error = '';

    // When toggling ON, request browser permission if not already granted
    if (config.defaultNotifications && notificationPermission !== 'granted') {
      const permission = await requestPermission();
      notificationPermission = permission;

      if (permission !== 'granted') {
        config.defaultNotifications = prev;
        error = permission === 'unsupported'
          ? 'Notifications are not supported in this browser.'
          : permission === 'default'
          ? 'Notification permission is required. Please allow when prompted.'
          : 'Notifications blocked by browser. Check site settings to enable.';
        return;
      }
    }

    try {
      await setDefaultNotifications(config.defaultNotifications);

      // Register push subscription whenever notifications are enabled and permission is granted
      if (notificationPermission === 'granted') {
        await syncPushSubscription(getNotificationSessionIds());
      }
    } catch {
      config.defaultNotifications = prev;
      error = 'Failed to update notifications default.';
    }
  }

  function handleDevtoolsChange() {
    localStorage.setItem('devtools-enabled', devtoolsEnabled ? 'true' : 'false');
    window.dispatchEvent(new Event('devtools-changed'));
  }

  async function handleClearAnalytics() {
    if (!confirm('Clear all analytics data? This cannot be undone.')) return;
    clearing = true;
    try {
      await clearAnalytics();
      analyticsSize = 0;
    } catch {
      error = 'Failed to clear analytics.';
    } finally {
      clearing = false;
    }
  }

  async function handleUpdate() {
    updating = true;
    updateStatus = '';
    try {
      const result = await triggerUpdate();
      if (result.restarting) {
        updateStatus = 'Updated! Restarting server\u2026';
        setTimeout(() => { location.reload(); }, 5000);
      } else {
        updateStatus = 'Updated! Please restart the server manually.';
      }
      updateAvailable = false;
    } catch {
      updateStatus = 'Update failed. Please try again.';
      updating = false;
    }
  }

  function handleGitHubDisconnect() {
    githubConnected = false;
  }

  function scrollToSection(sectionId: string) {
    tocOpen = false;
    contentEl?.querySelector(`#${sectionId}`)?.scrollIntoView({ behavior: 'smooth' });
  }
</script>

{#snippet headerExtra()}
  <div class="header-extra-content">
    <button class="hamburger-btn" onclick={() => tocOpen = !tocOpen} aria-label="Navigation">&#9776;</button>
    <input
      class="search-input"
      type="text"
      placeholder="Search..."
      bind:value={searchQuery}
      aria-label="Search settings"
    />
  </div>
{/snippet}

<DialogShell bind:this={shellRef} title="settings" variant="fullscreen" header-extra={headerExtra}>
  <div class="settings-content" bind:this={contentEl}>
    {#if error}
      <p class="error-msg">{error}</p>
    {/if}

    <!-- TOC drawer with IntersectionObserver scroll tracking -->
    <SettingsToc
      open={tocOpen}
      onclose={() => tocOpen = false}
      {contentEl}
      sections={[
        { id: 'section-general', label: 'general' },
        { id: 'section-integrations', label: 'integrations', children: [
          { id: 'integration-github', label: 'GitHub' },
          { id: 'integration-webhooks', label: 'Webhooks' },
          { id: 'integration-jira', label: 'Jira' },
        ]},
        { id: 'section-workspaces', label: 'workspaces' },
        { id: 'section-advanced', label: 'advanced' },
        { id: 'section-about', label: 'about' },
      ]}
    />

    <div class="settings-sections">
    <!-- GENERAL section -->
    <section id="section-general" class="settings-section" class:dimmed={!matchesSearch('general')}>
      <h3 class="section-heading">general</h3>

      <SettingRow name="Default Coding Agent" description="Which AI agent to use for new sessions">
        <select bind:value={config.defaultAgent} onchange={handleAgentChange}>
          <option value="claude">Claude</option>
          <option value="codex">Codex</option>
        </select>
      </SettingRow>

      <SettingRow name="Continue existing session" description="Resume the last session when opening a repo">
        <TuiCheckbox bind:checked={config.defaultContinue} onchange={handleContinueChange} />
      </SettingRow>

      <SettingRow name="YOLO mode" description="Skip permission checks for all sessions">
        <TuiCheckbox bind:checked={config.defaultYolo} onchange={handleYoloChange} />
      </SettingRow>

      <SettingRow name="Launch in tmux" description="Wrap sessions in tmux for scroll and copy">
        <TuiCheckbox bind:checked={config.launchInTmux} onchange={handleTmuxChange} />
      </SettingRow>

      <SettingRow name="Notifications" description={
        notificationPermission === 'denied' ? 'Blocked by browser — check site settings to enable'
        : notificationPermission === 'unsupported' ? 'Not supported in this browser'
        : 'Notify when sessions need attention'
      }>
        <TuiCheckbox bind:checked={config.defaultNotifications} onchange={handleNotificationsChange}
          disabled={(notificationPermission === 'denied' || notificationPermission === 'unsupported') && !config.defaultNotifications} />
      </SettingRow>
    </section>

    <!-- INTEGRATIONS section -->
    <section id="section-integrations" class="settings-section" class:dimmed={!matchesSearch('integrations')}>
      <h3 class="section-heading">integrations</h3>
      <div id="integration-github">
        <GitHubIntegration
          onDisconnect={handleGitHubDisconnect}
          webhookCount={webhookCount}
        />
      </div>
      <div id="integration-webhooks">
        <WebhookIntegration
          githubConnected={githubConnected}
        />
      </div>
      <div id="integration-jira">
        <JiraIntegration />
      </div>
    </section>

    <!-- WORKSPACES section -->
    <section id="section-workspaces" class="settings-section" class:dimmed={!matchesSearch('workspaces')}>
      <h3 class="section-heading">workspaces</h3>
      <p class="section-description">group repos into workspaces for multi-repo sessions</p>

      {#if workspaceGroups.length === 0}
        <p style="color: var(--text-muted); font-size: var(--font-size-xs);">no workspaces yet</p>
      {/if}

      {#each workspaceGroups as ws (ws.id)}
        <WorkspaceEditor
          workspace={ws}
          repos={sessionState.repos}
          onsave={async (updates) => {
            await api.updateWorkspaceGroup(ws.id, updates);
            await loadWorkspaceGroups();
          }}
          ondelete={async () => {
            await api.deleteWorkspaceGroup(ws.id);
            await loadWorkspaceGroups();
          }}
        />
      {/each}

      <button
        class="ghost-btn"
        onclick={async () => {
          await api.createWorkspaceGroup({ name: 'new workspace', repos: [] });
          await loadWorkspaceGroups();
        }}
      >[ + new workspace ]</button>
    </section>

    <!-- ADVANCED section -->
    <section id="section-advanced" class="settings-section" class:dimmed={!matchesSearch('advanced')}>
      <h3 class="section-heading">advanced</h3>

      <SettingRow name="Developer Tools" description="Mobile debug panel">
        <TuiCheckbox bind:checked={devtoolsEnabled} onchange={handleDevtoolsChange} />
      </SettingRow>

      <SettingRow name="Analytics" description="Local usage data">
        <div class="analytics-action">
          {#if analyticsSize !== null}
            <span class="analytics-size">{(analyticsSize / 1024 / 1024).toFixed(1)} MB</span>
          {/if}
          <TuiButton variant="ghost" size="sm" onclick={handleClearAnalytics} disabled={clearing}>
            {clearing ? 'Clearing\u2026' : 'Clear'}
          </TuiButton>
        </div>
      </SettingRow>
    </section>

    <!-- ABOUT section -->
    <section id="section-about" class="settings-section" class:dimmed={!matchesSearch('about')}>
      <h3 class="section-heading">about</h3>

      <SettingRow name="Version" description={currentVersion ? `v${currentVersion}` : ''}>
        {#if updateAvailable}
          <TuiButton variant="primary" size="sm" onclick={handleUpdate} disabled={updating}>
            {updating ? 'Updating\u2026' : `Update to v${latestVersion}`}
          </TuiButton>
        {:else if versionChecked}
          <span class="version-ok">Up to date</span>
        {/if}
      </SettingRow>

      <SettingRow name="Update Channel" description={updateChannelValue === 'nightly' ? 'Nightly builds' : 'Stable releases'}>
        <div class="channel-selector">
          <button
            class="channel-btn"
            class:active={updateChannelValue === 'stable'}
            disabled={savingChannel}
            onclick={() => handleChannelChange('stable')}
          >Stable</button>
          <button
            class="channel-btn"
            class:active={updateChannelValue === 'nightly'}
            disabled={savingChannel}
            onclick={() => handleChannelChange('nightly')}
          >Nightly</button>
        </div>
      </SettingRow>

      {#if updateStatus}
        <p class="update-status">{updateStatus}</p>
      {/if}
    </section>
    </div>
  </div>
</DialogShell>

<style>
  .header-extra-content {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .settings-content {
    display: flex;
    flex-direction: column;
    gap: 32px;
    position: relative;
  }

  .settings-sections {
    display: flex;
    flex-direction: column;
    gap: 32px;
    flex: 1;
    min-width: 0;
    padding: 16px 20px;
  }

  /* Desktop: side-by-side TOC + scrollable content */
  @media (min-width: 601px) {
    .settings-content {
      flex-direction: row;
      gap: 0;
      height: 100%;
      overflow: hidden;
    }

    .settings-sections {
      overflow-y: auto;
    }
  }

  .settings-section {
    transition: opacity 200ms ease, max-height 200ms ease;
  }

  .settings-section.dimmed {
    opacity: 0.3;
    max-height: 0;
    overflow: hidden;
    padding: 0;
    margin: 0;
  }

  .section-heading {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    letter-spacing: 0.08em;
    margin: 0 -20px 12px;
    padding: 0 20px 8px;
    border-bottom: 1px solid var(--border);
  }

  .search-input {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 0;
    color: var(--text);
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    padding: 8px 12px;
    flex: 1;
    max-width: 200px;
    outline: none;
  }

  .search-input:focus {
    border-color: var(--accent);
  }

  .search-input::placeholder {
    color: var(--text-muted);
  }

  .hamburger-btn {
    background: none;
    border: 1px solid var(--border);
    border-radius: 0;
    color: var(--text-muted);
    font-size: var(--font-size-lg);
    cursor: pointer;
    padding: 4px 8px;
    line-height: 1;
    font-family: var(--font-mono);
  }

  .hamburger-btn:hover {
    background: var(--border);
    color: var(--text);
  }

  /* Desktop: hide hamburger, TOC is always visible */
  @media (min-width: 601px) {
    .hamburger-btn { display: none; }
  }

  .analytics-action {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .analytics-size {
    font-size: var(--font-size-sm);
    color: var(--text-muted);
    font-family: var(--font-mono);
  }

  .version-ok {
    font-size: var(--font-size-sm);
    color: var(--status-success);
  }

  .update-status {
    font-size: var(--font-size-sm);
    color: var(--text-muted);
    margin: 0;
  }

  select {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 0;
    color: var(--text);
    font-family: var(--font-mono);
    font-size: var(--font-size-sm);
    padding: 8px 8px;
    cursor: pointer;
  }

  select:focus {
    border-color: var(--accent);
    outline: none;
  }

  .section-description {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    margin: 0 0 12px;
    font-family: var(--font-mono);
  }

  .ghost-btn {
    background: none;
    border: 1px solid var(--border);
    color: var(--text-muted);
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    padding: 6px 10px;
    cursor: pointer;
    margin-top: 4px;
  }

  .ghost-btn:hover {
    border-color: var(--accent);
    color: var(--accent);
  }

  .channel-selector {
    display: flex;
    gap: 0;
    border: 1px solid var(--border);
  }

  .channel-btn {
    background: var(--bg);
    border: none;
    border-right: 1px solid var(--border);
    color: var(--text-muted);
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    padding: 6px 12px;
    cursor: pointer;
  }

  .channel-btn:last-child {
    border-right: none;
  }

  .channel-btn:hover:not(:disabled) {
    background: var(--surface-hover);
    color: var(--text);
  }

  .channel-btn.active {
    background: var(--accent);
    color: var(--bg);
  }

  .channel-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>
